# yaml-language-server: $schema=./values.schema.json
image:
  repository: ghcr.io/tautulli/tautulli
  pullPolicy: IfNotPresent
  tag: v2.18.2@sha256:1b5875fe3193d450a62e7b438eb6701195c841f14f3dcb962e545eda42d3696f
workload:
  main:
    podSpec:
      containers:
        main:
          command:
            - python
            - Tautulli.py
          args:
            - --config
            - /config/config.ini
            - --datadir
            - /config
service:
  main:
    ports:
      main:
        port: 8181
        targetPort: 8181
persistence:
  config:
    enabled: true
    mountPath: "/config"
