# yaml-language-server: $schema=./values.schema.json
image:
  repository: ghcr.io/tautulli/tautulli
  pullPolicy: IfNotPresent
  tag: v2.17.0@sha256:9c73937390116e6875970f4c816ddfa9d905cc88f76f2ddbf4eaca2ea2715006
workload:
  main:
    podSpec:
      containers:
        main:
          command:
            - python
            - Tautulli.py
          args:
            - --config
            - /config/config.ini
            - --datadir
            - /config
service:
  main:
    ports:
      main:
        port: 8181
        targetPort: 8181
persistence:
  config:
    enabled: true
    mountPath: "/config"
