# yaml-language-server: $schema=./values.schema.json
image:
  repository: docker.io/thelounge/thelounge
  pullPolicy: IfNotPresent
  tag: 4.5.0@sha256:9c3667236b1a82cf79b1b35e012ddf58e1e2de46f3596befbc699825c0793680
service:
  main:
    ports:
      main:
        port: 10061
        targetPort: 9000
persistence:
  config:
    enabled: true
    mountPath: "/config"

securityContext:
  container:
    runAsNonRoot: false
    runAsUser: 0
    runAsGroup: 0
workload:
  main:
    podSpec:
      containers:
        main:
          env:
            THELOUNGE_HOME: "/config"
