# yaml-language-server: $schema=./values.schema.json
image:
  repository: docker.io/thelounge/thelounge
  pullPolicy: IfNotPresent
  tag: 4.5.0@sha256:7f2fff6e264411ce8608bd1fdf5142a3cd980677b0479e7e3702aadf18cd1ae9
service:
  main:
    ports:
      main:
        port: 10061
        targetPort: 9000
persistence:
  config:
    enabled: true
    mountPath: "/config"

securityContext:
  container:
    runAsNonRoot: false
    runAsUser: 0
    runAsGroup: 0
workload:
  main:
    podSpec:
      containers:
        main:
          env:
            THELOUNGE_HOME: "/config"
