# yaml-language-server: $schema=./values.schema.json
image:
  repository: docker.io/thelounge/thelounge
  pullPolicy: IfNotPresent
  tag: 4.5.0@sha256:b624275b88f88a08f8ad56833d3b1b3400cc39faa410c3790ea30fa24d39b675
service:
  main:
    ports:
      main:
        port: 10061
        targetPort: 9000
persistence:
  config:
    enabled: true
    mountPath: "/config"

securityContext:
  container:
    runAsNonRoot: false
    runAsUser: 0
    runAsGroup: 0
workload:
  main:
    podSpec:
      containers:
        main:
          env:
            THELOUNGE_HOME: "/config"
