# yaml-language-server: $schema=./values.schema.json
image:
  repository: ghcr.io/calibrain/shelfmark
  pullPolicy: IfNotPresent
  tag: v1.4.0@sha256:4ef757349c3c7a7d90ba95b1e2a46ce4dd460a4776efbcf2aa1b1c476e7d5de5

service:
  main:
    ports:
      main:
        port: 8084
        protocol: http
        targetPort: 8084

persistence:
  config:
    enabled: true
    mountPath: /config

workload:
  main:
    podSpec:
      containers:
        main:
          env:
            LOG_ROOT: /var/logs
          probes:
            liveness:
              type: http
              path: /api/health
            readiness:
              type: http
              path: /api/health
            startup:
              type: http
              path: /api/health
