# yaml-language-server: $schema=./values.schema.json
# Fake external service image
image:
  repository: alpine
  pullPolicy: IfNotPresent
  tag: 3.24.2@sha256:294b683cb724975bec92580e1e685676bd4b50bda910ddb8c51d4cabeaec77e6

global:
  # Ignore isStopped
  ignoreIsStopped: true

service:
  main:
    type: ExternalIP
    externalIP: "1.1.1.1"
    useSlice: true
    ports:
      main:
        protocol: https
        port: 10003
        # Target port is the port of the "external service"
        # Defaults to "port" if not set
workload:
  main:
    enabled: false
    podSpec:
      containers:
        main:
          env: {}

ingress:
  main:
    annotations:
      traefik.frontend.passHostHeader: "false"
