image:
  repository: docker.io/brandawg93/peanut
  tag: 5.9.3@sha256:612d2b8037ea2dcba9cac0618dacb314ae639ab06deb47823dc129a2ccf2445c
  pullPolicy: IfNotPresent
securityContext:
  container:
    readOnlyRootFilesystem: false
    runAsGroup: 0
    runAsUser: 0
service:
  main:
    ports:
      main:
        port: 10688

persistence:
  config:
    enabled: true
    mountPath: "/config"
workload:
  main:
    podSpec:
      containers:
        main:
          env:
            WEB_PORT: "{{ .Values.service.main.ports.main.port }}"
