# yaml-language-server: $schema=./values.schema.json
image:
  repository: docker.io/b4bz/homer
  tag: v26.4.1@sha256:659b488ebc52be44ca050b9a990e44c152d99eaa6af0225809168a57f09b67a8
  pullPolicy: IfNotPresent
service:
  main:
    ports:
      main:
        port: 10178
        targetPort: 8080
persistence:
  config:
    enabled: true
    mountPath: "/www/assets"

securityContext:
  container:
    runAsUser: 1000
    runAsGroup: 1000
workload:
  main:
    podSpec:
      containers:
        main:
          env:
            INIT_ASSETS: true
