# yaml-language-server: $schema=./values.schema.json
image:
  repository: docker.io/traccar/traccar
  tag: 6.13@sha256:c0ef68cb2225a55d1ef6f40dfa2d0761e8d7ad707f0b2a62b5a34c5c8677b352
  pullPolicy: IfNotPresent
service:
  main:
    ports:
      main:
        port: 8082
        targetPort: 8082
persistence:
  data:
    enabled: true
    mountPath: "/opt/traccar/data"
cnpg:
  main:
    enabled: true
    user: traccar
    database: traccar
securityContext:
  container:
    runAsNonRoot: false
    readOnlyRootFilesystem: false
    runAsUser: 0
    runAsGroup: 0
workload:
  main:
    podSpec:
      containers:
        main:
          env:
            CONFIG_USE_ENVIRONMENT_VARIABLES: true
            LOGGER_CONSOLE: true
            DATABASE_DRIVER: "org.postgresql.Driver"
            DATABASE_USER: "{{ .Values.cnpg.main.user }}"
            DATABASE_PASSWORD:
              secretKeyRef:
                name: cnpg-main-user
                key: password
            DATABASE_URL:
              secretKeyRef:
                name: cnpg-main-urls
                key: jdbc
