# yaml-language-server: $schema=./values.schema.json
image:
  repository: docker.io/traccar/traccar
  tag: 6.14@sha256:f187e0be41503f1365fec62cb3075c8545fa6b325a5ac47e37667a47e7a31459
  pullPolicy: IfNotPresent
service:
  main:
    ports:
      main:
        port: 8082
        targetPort: 8082
persistence:
  data:
    enabled: true
    mountPath: "/opt/traccar/data"
cnpg:
  main:
    enabled: true
    user: traccar
    database: traccar
securityContext:
  container:
    runAsNonRoot: false
    readOnlyRootFilesystem: false
    runAsUser: 0
    runAsGroup: 0
workload:
  main:
    podSpec:
      containers:
        main:
          env:
            CONFIG_USE_ENVIRONMENT_VARIABLES: true
            LOGGER_CONSOLE: true
            DATABASE_DRIVER: "org.postgresql.Driver"
            DATABASE_USER: "{{ .Values.cnpg.main.user }}"
            DATABASE_PASSWORD:
              secretKeyRef:
                name: cnpg-main-user
                key: password
            DATABASE_URL:
              secretKeyRef:
                name: cnpg-main-urls
                key: jdbc
