# yaml-language-server: $schema=./values.schema.json
image:
  pullPolicy: IfNotPresent
  repository: docker.io/wabayang/jelu
  tag: latest@sha256:3a870b23330a3a571916d2b6f6c187d9ec95bf80d4d5f6cbaf8255380f3b2d73
persistence:
  config:
    enabled: true
    mountPath: /config
  databasepath:
    enabled: true
    mountPath: /database
  imagespath:
    enabled: true
    mountPath: /files/images
  importspath:
    enabled: true
    mountPath: /files/imports

securityContext:
  container:
    readOnlyRootFilesystem: false
    runAsGroup: 0
    runAsUser: 0
service:
  main:
    ports:
      main:
        port: 11111
        protocol: tcp
        targetPort: 11111
