# yaml-language-server: $schema=./values.schema.json
image:
  pullPolicy: IfNotPresent
  repository: docker.io/wabayang/jelu
  tag: latest@sha256:9c397db26085e3014e3137d64fef03fe76dd7ac8f802cd4f9be1ff6be41a4bcc
persistence:
  config:
    enabled: true
    mountPath: /config
  databasepath:
    enabled: true
    mountPath: /database
  imagespath:
    enabled: true
    mountPath: /files/images
  importspath:
    enabled: true
    mountPath: /files/imports

securityContext:
  container:
    readOnlyRootFilesystem: false
    runAsGroup: 0
    runAsUser: 0
service:
  main:
    ports:
      main:
        port: 11111
        protocol: tcp
        targetPort: 11111
