# yaml-language-server: $schema=./values.schema.json
image:
  pullPolicy: IfNotPresent
  repository: docker.io/wabayang/jelu
  tag: latest@sha256:ee436dc90ad0bc9ea84d6049b8d3d18a79478ce2ef0f27a974da93a72fb17c0d
persistence:
  config:
    enabled: true
    mountPath: /config
  databasepath:
    enabled: true
    mountPath: /database
  imagespath:
    enabled: true
    mountPath: /files/images
  importspath:
    enabled: true
    mountPath: /files/imports

securityContext:
  container:
    readOnlyRootFilesystem: false
    runAsGroup: 0
    runAsUser: 0
service:
  main:
    ports:
      main:
        port: 11111
        protocol: tcp
        targetPort: 11111
