# yaml-language-server: $schema=./values.schema.json
image:
  repository: docker.io/syncthing/syncthing
  pullPolicy: IfNotPresent
  tag: 2.0.15@sha256:1feffa2d4826b48f25faefed093d07c5f00304d7e7ac86fd7cda334d22651643
workload:
  main:
    podSpec:
      containers:
        main:
          probes:
            liveness:
              path: /rest/noauth/health
            readiness:
              path: /rest/noauth/health
            startup:
              path: /rest/noauth/health
service:
  main:
    ports:
      main:
        port: 8384
        targetPort: 8384
  listeners:
    enabled: true
    ports:
      tcp:
        enabled: true
        port: 22000
        targetPort: 22000
  listeners-udp:
    enabled: true
    ports:
      udp:
        enabled: true
        port: 22000
        targetPort: 22000
        protocol: udp
  discovery:
    enabled: true
    ports:
      discovery:
        enabled: true
        port: 21027
        targetPort: 21027
        protocol: udp
persistence:
  config:
    enabled: true
    mountPath: "/var/syncthing"
