# yaml-language-server: $schema=./values.schema.json
image:
  repository: docker.io/syncthing/syncthing
  pullPolicy: IfNotPresent
  tag: 2.0.16@sha256:4a961394ca471f4e48f31ad2cef50697e502c8799e2e98477a1c3844e0c5bc54
workload:
  main:
    podSpec:
      containers:
        main:
          probes:
            liveness:
              path: /rest/noauth/health
            readiness:
              path: /rest/noauth/health
            startup:
              path: /rest/noauth/health
service:
  main:
    ports:
      main:
        port: 8384
        targetPort: 8384
  listeners:
    enabled: true
    ports:
      tcp:
        enabled: true
        port: 22000
        targetPort: 22000
  listeners-udp:
    enabled: true
    ports:
      udp:
        enabled: true
        port: 22000
        targetPort: 22000
        protocol: udp
  discovery:
    enabled: true
    ports:
      discovery:
        enabled: true
        port: 21027
        targetPort: 21027
        protocol: udp
persistence:
  config:
    enabled: true
    mountPath: "/var/syncthing"
