# yaml-language-server: $schema=./values.schema.json
image:
  repository: docker.io/benzino77/tasmocompiler
  tag: latest@sha256:2b705fc3cea9219da71fb85612e2d819b79509a9b3ba7ac98aa7d3025d804f26
  pullPolicy: IfNotPresent

securityContext:
  container:
    readOnlyRootFilesystem: false
    runAsNonRoot: false
    runAsUser: 0
    runAsGroup: 0

service:
  main:
    ports:
      main:
        port: 14003
        protocol: http
        targetPort: 3000
