# yaml-language-server: $schema=./values.schema.json
image:
  repository: oci.trueforge.org/containerforge/theme-park
  pullPolicy: IfNotPresent
  tag: 1.23.0@sha256:4699077c3b02e53931e68ba9d688236a5bb8075e451522f7bb58e609178323d6
service:
  main:
    ports:
      main:
        port: 10244
        targetPort: 8080
persistence:
  config:
    enabled: true
    mountPath: "/config"
