# yaml-language-server: $schema=./values.schema.json
image:
  repository: oci.trueforge.org/containerforge/theme-park
  pullPolicy: IfNotPresent
  tag: 1.22.0@sha256:d35158e13605102a6587dd3a16d9e998d70aa436360864adf0e58e1bec9013b7
service:
  main:
    ports:
      main:
        port: 10244
        targetPort: 8080
persistence:
  config:
    enabled: true
    mountPath: "/config"
