# yaml-language-server: $schema=./values.schema.json
image:
  repository: oci.trueforge.org/containerforge/theme-park
  pullPolicy: IfNotPresent
  tag: 1.22.0@sha256:8d2a0d6c362fe2b206730bb6348f6d5beee18c6f200b489f5d092e349d68c975
service:
  main:
    ports:
      main:
        port: 10244
        targetPort: 8080
persistence:
  config:
    enabled: true
    mountPath: "/config"
