# yaml-language-server: $schema=./values.schema.json
image:
  repository: ghcr.io/linuxserver/freshrss
  pullPolicy: IfNotPresent
  tag: 1.29.1@sha256:d97008a26ee3ed730bf5e85cdb92a4d369d12964e6439f3a5eaa3862092d3dcf
securityContext:
  container:
    readOnlyRootFilesystem: false
    runAsNonRoot: false
    runAsUser: 0
    runAsGroup: 0
service:
  main:
    ports:
      main:
        port: 10010
        targetPort: 80
persistence:
  config:
    enabled: true
    mountPath: /config
