# yaml-language-server: $schema=./values.schema.json
image:
  repository: ghcr.io/linuxserver/freshrss
  pullPolicy: IfNotPresent
  tag: 1.29.1@sha256:699594b0bccd029e655052e18d69abd235dd5ddc071f44f3af3b407f01138954
securityContext:
  container:
    readOnlyRootFilesystem: false
    runAsNonRoot: false
    runAsUser: 0
    runAsGroup: 0
service:
  main:
    ports:
      main:
        port: 10010
        targetPort: 80
persistence:
  config:
    enabled: true
    mountPath: /config
