# yaml-language-server: $schema=./values.schema.json
image:
  repository: ghcr.io/linuxserver/freshrss
  pullPolicy: IfNotPresent
  tag: 1.29.1@sha256:b24ddde7d465f004847305b70d2479eb31c218e777bf2ab97d42dc75b54ed914
securityContext:
  container:
    readOnlyRootFilesystem: false
    runAsNonRoot: false
    runAsUser: 0
    runAsGroup: 0
service:
  main:
    ports:
      main:
        port: 10010
        targetPort: 80
persistence:
  config:
    enabled: true
    mountPath: /config
