# yaml-language-server: $schema=./values.schema.json
image:
  repository: ghcr.io/ellite/wallos
  tag: 4.6.2@sha256:ff4f09d93b23ae7ec6aba61e6b4a9b02fdd4f572ef54f4017a890c2414892e2c
  pullPolicy: IfNotPresent

securityContext:
  container:
    readOnlyRootFilesystem: false
    runAsNonRoot: false
    runAsUser: 0
    runAsGroup: 0

service:
  main:
    ports:
      main:
        port: 8282
        protocol: tcp
        targetPort: 80

persistence:
  database:
    enabled: true
    mountPath: "/var/www/html/db"
  logos:
    enabled: true
    mountPath: "/var/www/html/images/uploads/logos"
