# yaml-language-server: $schema=./values.schema.json
image:
  repository: ghcr.io/ellite/wallos
  tag: 4.8.0@sha256:a1894b1653a7aa9a44e887a06b4db9032c2e61d663fb5b7e7c7ad53f5689c409
  pullPolicy: IfNotPresent

securityContext:
  container:
    readOnlyRootFilesystem: false
    runAsNonRoot: false
    runAsUser: 0
    runAsGroup: 0

service:
  main:
    ports:
      main:
        port: 8282
        protocol: tcp
        targetPort: 80

persistence:
  database:
    enabled: true
    mountPath: "/var/www/html/db"
  logos:
    enabled: true
    mountPath: "/var/www/html/images/uploads/logos"
