# yaml-language-server: $schema=./values.schema.json
image:
  pullPolicy: IfNotPresent
  repository: docker.io/shaarli/shaarli
  tag: v0.16.2@sha256:73e527fb5a76adaf112847aa4d3183918392358a8cc20284ad1607f4a6f9b77a
persistence:
  cache:
    enabled: true
    mountPath: /var/www/shaarli/cache
  data:
    enabled: true
    mountPath: /var/www/shaarli/data

securityContext:
  container:
    readOnlyRootFilesystem: false
    runAsGroup: 0
    runAsUser: 0
service:
  main:
    ports:
      main:
        port: 8000
        protocol: tcp
        targetPort: 80
