# yaml-language-server: $schema=./values.schema.json
image:
  pullPolicy: IfNotPresent
  repository: docker.io/shaarli/shaarli
  tag: v0.16.3@sha256:c15f3458687a3f36edac9f02583efc5152da47ba669dd9a179a771193c23bb69
persistence:
  cache:
    enabled: true
    mountPath: /var/www/shaarli/cache
  data:
    enabled: true
    mountPath: /var/www/shaarli/data

securityContext:
  container:
    readOnlyRootFilesystem: false
    runAsGroup: 0
    runAsUser: 0
service:
  main:
    ports:
      main:
        port: 8000
        protocol: tcp
        targetPort: 80
