# yaml-language-server: $schema=./values.schema.json
image:
  pullPolicy: IfNotPresent
  repository: ghcr.io/shaarli/shaarli
  tag: v0.16.9@sha256:29d3e4f1489f05ab42bb189a8533d1d9f0a0bdee77cebd75a231238e15efa26a
persistence:
  cache:
    enabled: true
    mountPath: /var/www/shaarli/cache
  data:
    enabled: true
    mountPath: /var/www/shaarli/data

securityContext:
  container:
    readOnlyRootFilesystem: false
    runAsGroup: 0
    runAsUser: 0
service:
  main:
    ports:
      main:
        port: 8000
        protocol: tcp
        targetPort: 80
