# yaml-language-server: $schema=./values.schema.json
image:
  pullPolicy: IfNotPresent
  repository: docker.io/tiltedphoques/st-reborn-server
  tag: 1.8.3@sha256:4fb475ef36529c02871a82f37e163d95ca6889606fbd106dbc962119608839b7
persistence:
  config:
    enabled: true
    mountPath: /home/server/config
  data:
    enabled: true
    mountPath: /home/server/Data
  logs:
    enabled: true
    mountPath: /home/server/logs

service:
  main:
    ports:
      main:
        port: 10578
        protocol: udp
        targetPort: 10578
workload:
  main:
    podSpec:
      containers:
        main:
          probes:
            liveness:
              enabled: false
            readiness:
              enabled: false
            startup:
              enabled: false
