# yaml-language-server: $schema=./values.schema.json
image:
  pullPolicy: IfNotPresent
  repository: docker.io/tiltedphoques/st-reborn-server
  tag: 1.8.1@sha256:2d81cab0ccbd958ef920c81aa239a858b57288f230ae19908c77ee765d68cf84
persistence:
  config:
    enabled: true
    mountPath: /home/server/config
  data:
    enabled: true
    mountPath: /home/server/Data
  logs:
    enabled: true
    mountPath: /home/server/logs

service:
  main:
    ports:
      main:
        port: 10578
        protocol: udp
        targetPort: 10578
workload:
  main:
    podSpec:
      containers:
        main:
          probes:
            liveness:
              enabled: false
            readiness:
              enabled: false
            startup:
              enabled: false
