# yaml-language-server: $schema=./values.schema.json
image:
  repository: ghcr.io/linuxserver/remmina
  pullPolicy: IfNotPresent
  tag: 1.4.43@sha256:734369bb2adad5723467d0269617bb1b367e002e114dce7e21b4d1611c6593f5
service:
  main:
    ports:
      main:
        port: 10042
        targetPort: 3000
persistence:
  config:
    enabled: true
    mountPath: "/config"
  varrun:
    enabled: true

securityContext:
  container:
    readOnlyRootFilesystem: false
    runAsNonRoot: false
    runAsUser: 0
    runAsGroup: 0
