# yaml-language-server: $schema=./values.schema.json
image:
  repository: ghcr.io/linuxserver/remmina
  pullPolicy: IfNotPresent
  tag: 1.4.43@sha256:fa8e87a89b127e8619d091d0a0cdb4fbcba2d706a95fd68403544e97e9631f8c
service:
  main:
    ports:
      main:
        port: 10042
        targetPort: 3000
persistence:
  config:
    enabled: true
    mountPath: "/config"
  varrun:
    enabled: true

securityContext:
  container:
    readOnlyRootFilesystem: false
    runAsNonRoot: false
    runAsUser: 0
    runAsGroup: 0
