# yaml-language-server: $schema=./values.schema.json
image:
  repository: oci.trueforge.org/containerforge/nzbget
  pullPolicy: IfNotPresent
  tag: "26.2.0@sha256:83bc7a418603a357017350fc7ba18c832b2e63898a9e3f62ece14b4422cf2fd6"
service:
  main:
    ports:
      main:
        port: 10057
        targetPort: 6789
persistence:
  config:
    enabled: true
    mountPath: "/config"

workload:
  main:
    podSpec:
      containers:
        main:
          probes:
            liveness:
              enabled: false
            readiness:
              enabled: false
            startup:
              enabled: false
