# yaml-language-server: $schema=./values.schema.json
image:
  repository: oci.trueforge.org/containerforge/nzbget
  pullPolicy: IfNotPresent
  tag: "26.2.0@sha256:b7172d7575bba1bdd8a82ea6bf6fb2dce7e2c31d987d1f73f700fbc575eb40e9"
service:
  main:
    ports:
      main:
        port: 10057
        targetPort: 6789
persistence:
  config:
    enabled: true
    mountPath: "/config"

workload:
  main:
    podSpec:
      containers:
        main:
          probes:
            liveness:
              enabled: false
            readiness:
              enabled: false
            startup:
              enabled: false
