# yaml-language-server: $schema=./values.schema.json
image:
  repository: oci.trueforge.org/containerforge/nzbget
  pullPolicy: IfNotPresent
  tag: "26.2.0@sha256:d4978e0d7cd923c6fa15a3f534f11a3a424f2e0ecb8594c964a848d2f438e01c"
service:
  main:
    ports:
      main:
        port: 10057
        targetPort: 6789
persistence:
  config:
    enabled: true
    mountPath: "/config"

workload:
  main:
    podSpec:
      containers:
        main:
          probes:
            liveness:
              enabled: false
            readiness:
              enabled: false
            startup:
              enabled: false
