# yaml-language-server: $schema=./values.schema.json
image:
  repository: ghcr.io/taxel/plextraktsync
  tag: 0.35.18@sha256:ccee7b4c5d150a18e23dfd189c0c5ddec388a10f974a319fdc0c7e39a4bec52f
  pullPolicy: IfNotPresent

securityContext:
  container:
    runAsNonRoot: false
    readOnlyRootFilesystem: false
    runAsUser: 0
    runAsGroup: 0

service:
  main:
    enabled: false
    ports:
      main:
        enabled: false

plextraktsync:
  cron_enabled: true
  task: "sync"
  schedule: "0 */6 * * *"

workload:
  main:
    podSpec:
      containers:
        main:
          tty: true
          stdin: true
          probes:
            liveness:
              enabled: false
            readiness:
              enabled: false
            startup:
              enabled: false
  plextraktsync-cron:
    enabled: "{{ .Values.plextraktsync.cron_enabled }}"
    type: CronJob
    schedule: "{{ .Values.plextraktsync.schedule }}"
    podSpec:
      restartPolicy: Never
      containers:
        cron:
          primary: true
          enabled: true
          imageSelector: "image"
          probes:
            liveness:
              enabled: false
            readiness:
              enabled: false
            startup:
              enabled: false
          args:
            - "{{ .Values.plextraktsync.task }}"

persistence:
  config:
    enabled: true
    targetSelector:
      main:
        main:
          mountPath: /app/config
      plextraktsync-cron:
        cron:
          mountPath: /app/config
