# yaml-language-server: $schema=./values.schema.json
image:
  repository: docker.io/iyuucn/iyuuplus
  pullPolicy: IfNotPresent
  tag: latest@sha256:db94aeb1866522e7d2d855e57abc6ad2a033f5d87f5ec9a86f6e314f216ee04c
service:
  main:
    ports:
      main:
        targetPort: 8787
        port: 10188
persistence:
  config:
    enabled: true
    mountPath: "/IYUU/db"
  torrents:
    enabled: true
    mountPath: "/torrents"
  btbackup:
    enabled: true
    mountPath: "/BT_backup"

securityContext:
  container:
    readOnlyRootFilesystem: false
    runAsNonRoot: false
    runAsUser: 0
    runAsGroup: 0
