# yaml-language-server: $schema=./values.schema.json
image:
  repository: docker.io/iyuucn/iyuuplus
  pullPolicy: IfNotPresent
  tag: latest@sha256:fc79a454cdf570b2466ca0978b71a5f855ef533eb18e26a501e7a279b2876104
service:
  main:
    ports:
      main:
        targetPort: 8787
        port: 10188
persistence:
  config:
    enabled: true
    mountPath: "/IYUU/db"
  torrents:
    enabled: true
    mountPath: "/torrents"
  btbackup:
    enabled: true
    mountPath: "/BT_backup"

securityContext:
  container:
    readOnlyRootFilesystem: false
    runAsNonRoot: false
    runAsUser: 0
    runAsGroup: 0
