# yaml-language-server: $schema=./values.schema.json
image:
  repository: docker.io/iyuucn/iyuuplus
  pullPolicy: IfNotPresent
  tag: latest@sha256:b6c19d58f37101944fe9e84bcfcac5ced91ea44103f239ab306daf81abc872a8
service:
  main:
    ports:
      main:
        targetPort: 8787
        port: 10188
persistence:
  config:
    enabled: true
    mountPath: "/IYUU/db"
  torrents:
    enabled: true
    mountPath: "/torrents"
  btbackup:
    enabled: true
    mountPath: "/BT_backup"

securityContext:
  container:
    readOnlyRootFilesystem: false
    runAsNonRoot: false
    runAsUser: 0
    runAsGroup: 0
