# yaml-language-server: $schema=./values.schema.json
image:
  repository: ghcr.io/linuxserver/mysql-workbench
  pullPolicy: IfNotPresent
  tag: 8.0.47@sha256:f357eccdec64f11e76024b0b73deb4d97357f2b808bdd1b84037b31c8b0cc0f5
service:
  main:
    ports:
      main:
        targetPort: 3000
        protocol: http
        port: 10134
persistence:
  config:
    enabled: true
    mountPath: "/config"
  varrun:
    enabled: true

securityContext:
  container:
    runAsNonRoot: false
    readOnlyRootFilesystem: false
    capabilities:
      add:
        - IPC_LOCK
    runAsUser: 0
    runAsGroup: 0
