# yaml-language-server: $schema=./values.schema.json
image:
  repository: ghcr.io/linuxserver/mysql-workbench
  pullPolicy: IfNotPresent
  tag: 8.0.47@sha256:50222952191631e68dec748dddb2f047ffddbde21e6d8d8df9ed0be4480f7f58
service:
  main:
    ports:
      main:
        targetPort: 3000
        protocol: http
        port: 10134
persistence:
  config:
    enabled: true
    mountPath: "/config"
  varrun:
    enabled: true

securityContext:
  container:
    runAsNonRoot: false
    readOnlyRootFilesystem: false
    capabilities:
      add:
        - IPC_LOCK
    runAsUser: 0
    runAsGroup: 0
