# yaml-language-server: $schema=./values.schema.json
image:
  pullPolicy: IfNotPresent
  repository: docker.io/lswl/vertex
  tag: stable@sha256:6695f6b9c107157bef331e908ff5c64ec0ca5787943b2b9191bb1c710fae3dde
persistence:
  config:
    enabled: true
    mountPath: /vertex

securityContext:
  container:
    readOnlyRootFilesystem: false
    runAsGroup: 0
    runAsUser: 0
service:
  main:
    ports:
      main:
        port: 3000
        protocol: tcp
        targetPort: 3000
workload:
  main:
    podSpec:
      containers:
        main:
          env:
            PORT: "3000"
