# yaml-language-server: $schema=./values.schema.json
image:
  repository: ghcr.io/itzg/mc-proxy
  tag: 2026.9.0-java21@sha256:972d94ac11818f8b6772648e16ece477f823e7bedda18b9649bc033bc5f46ffb
  pullPolicy: Always
j8Image:
  repository: ghcr.io/itzg/mc-proxy
  tag: 2026.9.0-java8@sha256:15be33cdd77c6df148d242d14d69065026cfe2b312b7788fb3cec1723a35b2a3
  pullPolicy: Always
j17Image:
  repository: ghcr.io/itzg/mc-proxy
  tag: 2026.9.0-java17@sha256:0ed98056f9bfaab13f653e67fa83c26106966ac29224f792ffa4ff1ca0bd3954
  pullPolicy: Always
j25Image:
  repository: ghcr.io/itzg/mc-proxy
  tag: 2026.9.0-java25@sha256:029efbec914f9345360fb819319f40abadb5db803abfb493ec8e73cb73b70193
  pullPolicy: Always
service:
  main:
    ports:
      main:
        port: 25565
        targetPort: 25577
  rcon:
    enabled: true
    ports:
      rcon:
        enabled: true
        port: 25578
workload:
  main:
    podSpec:
      containers:
        main:
          imageSelector: image
          tty: true
          stdin: true
          probes:
            liveness:
              type: tcp
            readiness:
              type: tcp
            startup:
              type: tcp
          env:
            RCON_PORT: "{{ .Values.service.rcon.ports.rcon.port }}"
            RCON_PASSWORD: "secretrconpass"
            TYPE: "BUNGEECORD"
            ONLINE_MODE: false
            MEMORY: 512M
            INIT_MEMORY: 512M
            MAX_MEMORY: 512M
            NETWORKADDRESS_CACHE_TTL: 60
            REPLACE_ENV_VARIABLES: false
            ENV_VARIABLE_PREFIX: "CFG_"
            # GENERIC_PACKS: "configs-v9.0.1,mods-v4.3.6"
            # GENERIC_PACKS_PREFIX: "https://cdn.example.org/"
            # GENERIC_PACKS_SUFFIX="".zip"
            # JVM_OPTS: ""
            # JVM_XX_OPTS: ""
            # PLUGINS: ""
persistence:
  config:
    enabled: true
    mountPath: "/config"
  server:
    enabled: true
    mountPath: "/server"
  plugins:
    enabled: true
    mountPath: "/plugins"
