# yaml-language-server: $schema=./values.schema.json
image:
  repository: ghcr.io/itzg/mc-proxy
  tag: 2026.9.2-java21@sha256:b2cdc31453e86263bd21f5fe2b1c9974f46abfcf51492fb0f43d8359d7d2b9e7
  pullPolicy: Always
j8Image:
  repository: ghcr.io/itzg/mc-proxy
  tag: 2026.9.2-java8@sha256:f0bbe7b448207494f4878a0ec796bf1e04fc8bae51af34b99aaf301377a0f579
  pullPolicy: Always
j17Image:
  repository: ghcr.io/itzg/mc-proxy
  tag: 2026.9.2-java17@sha256:1b42c5350cd621fca95218650269aee5b7d4ab064e69c5561fe59e02edc3afb4
  pullPolicy: Always
j25Image:
  repository: ghcr.io/itzg/mc-proxy
  tag: 2026.9.2-java25@sha256:f95e6c0364a6be9ff983208943c807da70d584d935b25a23b605966a71f33411
  pullPolicy: Always
service:
  main:
    ports:
      main:
        port: 25565
        targetPort: 25577
  rcon:
    enabled: true
    ports:
      rcon:
        enabled: true
        port: 25578
workload:
  main:
    podSpec:
      containers:
        main:
          imageSelector: image
          tty: true
          stdin: true
          probes:
            liveness:
              type: tcp
            readiness:
              type: tcp
            startup:
              type: tcp
          env:
            RCON_PORT: "{{ .Values.service.rcon.ports.rcon.port }}"
            RCON_PASSWORD: "secretrconpass"
            TYPE: "BUNGEECORD"
            ONLINE_MODE: false
            MEMORY: 512M
            INIT_MEMORY: 512M
            MAX_MEMORY: 512M
            NETWORKADDRESS_CACHE_TTL: 60
            REPLACE_ENV_VARIABLES: false
            ENV_VARIABLE_PREFIX: "CFG_"
            # GENERIC_PACKS: "configs-v9.0.1,mods-v4.3.6"
            # GENERIC_PACKS_PREFIX: "https://cdn.example.org/"
            # GENERIC_PACKS_SUFFIX="".zip"
            # JVM_OPTS: ""
            # JVM_XX_OPTS: ""
            # PLUGINS: ""
persistence:
  config:
    enabled: true
    mountPath: "/config"
  server:
    enabled: true
    mountPath: "/server"
  plugins:
    enabled: true
    mountPath: "/plugins"
