# yaml-language-server: $schema=./values.schema.json
image:
  repository: ghcr.io/itzg/mc-proxy
  tag: 2026.8.2-java21@sha256:f9120301cbb0220b0f1a590a9ff2f2ef03cb0dfe6903c14dde3d0d40d0248b9b
  pullPolicy: Always
j8Image:
  repository: ghcr.io/itzg/mc-proxy
  tag: 2026.8.2-java8@sha256:af7647db5c93666c78d3eca2444a2f32eb1fe0bef98f9f7854bf02f01062b0b7
  pullPolicy: Always
j17Image:
  repository: ghcr.io/itzg/mc-proxy
  tag: 2026.8.2-java17@sha256:9fe3ee1a63ee97f3b7d091e3b2ccb39041a42bde63de63668f37e882475cf3c4
  pullPolicy: Always
j25Image:
  repository: ghcr.io/itzg/mc-proxy
  tag: 2026.8.2-java25@sha256:49dddc3d80e72374d5c1e869d1940100bde97b04e10ece00eb2a4a559436dfc5
  pullPolicy: Always
service:
  main:
    ports:
      main:
        port: 25565
        targetPort: 25577
  rcon:
    enabled: true
    ports:
      rcon:
        enabled: true
        port: 25578
workload:
  main:
    podSpec:
      containers:
        main:
          imageSelector: image
          tty: true
          stdin: true
          probes:
            liveness:
              type: tcp
            readiness:
              type: tcp
            startup:
              type: tcp
          env:
            RCON_PORT: "{{ .Values.service.rcon.ports.rcon.port }}"
            RCON_PASSWORD: "secretrconpass"
            TYPE: "BUNGEECORD"
            ONLINE_MODE: false
            MEMORY: 512M
            INIT_MEMORY: 512M
            MAX_MEMORY: 512M
            NETWORKADDRESS_CACHE_TTL: 60
            REPLACE_ENV_VARIABLES: false
            ENV_VARIABLE_PREFIX: "CFG_"
            # GENERIC_PACKS: "configs-v9.0.1,mods-v4.3.6"
            # GENERIC_PACKS_PREFIX: "https://cdn.example.org/"
            # GENERIC_PACKS_SUFFIX="".zip"
            # JVM_OPTS: ""
            # JVM_XX_OPTS: ""
            # PLUGINS: ""
persistence:
  config:
    enabled: true
    mountPath: "/config"
  server:
    enabled: true
    mountPath: "/server"
  plugins:
    enabled: true
    mountPath: "/plugins"
