# yaml-language-server: $schema=./values.schema.json
image:
  repository: ghcr.io/linuxserver/doublecommander
  pullPolicy: IfNotPresent
  tag: latest@sha256:c359e9f2de564b75fc3a23ec98e87be6e52b1a1d1060da392acfc19225d9af7b
securityContext:
  container:
    readOnlyRootFilesystem: false
    runAsNonRoot: false
    runAsUser: 0
    runAsGroup: 0
service:
  main:
    ports:
      main:
        port: 10034
        targetPort: 3000
workload:
  main:
    podSpec:
      containers:
        main:
          securityContext:
            capabilities:
              add:
                - SYS_CHROOT
                - KILL
                - NET_BIND_SERVICE
          probes:
            liveness:
              type: http
              path: /
            readiness:
              type: http
              path: /
            startup:
              type: http
              path: /
persistence:
  config:
    enabled: true
    mountPath: /config
