# yaml-language-server: $schema=./values.schema.json
image:
  repository: docker.io/victoriametrics/victoria-metrics
  tag: v1.145.0@sha256:c014fb5a711d38cb24fd0673197592cd1394bb903dbb16aea565620c9c8a3d70
  pullPolicy: IfNotPresent
service:
  main:
    ports:
      main:
        port: 8428
        targetPort: 8428
persistence:
  data:
    enabled: true
    mountPath: /victoria-metrics-data
    targetSelectAll: true

workload:
  main:
    podSpec:
      containers:
        main:
          probes:
            liveness:
              type: http
              path: /health
            readiness:
              type: http
              path: /health
            startup:
              enabled: false
