# yaml-language-server: $schema=./values.schema.json
image:
  repository: docker.io/victoriametrics/victoria-metrics
  tag: v1.153.0@sha256:5eff7af5341e401471002f58d106d399e614a62f3d240f2dbc21901e49eed5dd
  pullPolicy: IfNotPresent
service:
  main:
    ports:
      main:
        port: 8428
        targetPort: 8428
persistence:
  data:
    enabled: true
    mountPath: /victoria-metrics-data
    targetSelectAll: true

workload:
  main:
    podSpec:
      containers:
        main:
          probes:
            liveness:
              type: http
              path: /health
            readiness:
              type: http
              path: /health
            startup:
              enabled: false
