# yaml-language-server: $schema=./values.schema.json
image:
  repository: docker.io/victoriametrics/victoria-metrics
  tag: v1.146.0@sha256:b8703ff12ed437effad4fc36492fec14824277f2890a5876b8a9e6cfe5139839
  pullPolicy: IfNotPresent
service:
  main:
    ports:
      main:
        port: 8428
        targetPort: 8428
persistence:
  data:
    enabled: true
    mountPath: /victoria-metrics-data
    targetSelectAll: true

workload:
  main:
    podSpec:
      containers:
        main:
          probes:
            liveness:
              type: http
              path: /health
            readiness:
              type: http
              path: /health
            startup:
              enabled: false
