# yaml-language-server: $schema=./values.schema.json
image:
  repository: docker.io/modem7/docker-rickroll
  pullPolicy: IfNotPresent
  tag: latest@sha256:132bfacfc5184d4491464c1f86b40dc90ff202a418b9e892cd590fb7d94b8436
securityContext:
  container:
    runAsNonRoot: false
    readOnlyRootFilesystem: false
    runAsUser: 0
    runAsGroup: 0
service:
  main:
    ports:
      main:
        protocol: http
        port: 10289
        targetPort: 8080
workload:
  main:
    podSpec:
      containers:
        main:
          probes:
            liveness:
              type: http
            readiness:
              type: http
            startup:
              type: http
          env:
            TITLE: "Rickroll"
            HEIGHT: "100vh"
            WIDTH: "100%"
            HEADLINE: ""
