# yaml-language-server: $schema=./values.schema.json
image:
  repository: docker.io/modem7/docker-rickroll
  pullPolicy: IfNotPresent
  tag: latest@sha256:412c6f6044df75504b3fa940dda405df49830788265083e9262a6a7cf190f669
securityContext:
  container:
    runAsNonRoot: false
    readOnlyRootFilesystem: false
    runAsUser: 0
    runAsGroup: 0
service:
  main:
    ports:
      main:
        protocol: http
        port: 10289
        targetPort: 8080
workload:
  main:
    podSpec:
      containers:
        main:
          probes:
            liveness:
              type: http
            readiness:
              type: http
            startup:
              type: http
          env:
            TITLE: "Rickroll"
            HEIGHT: "100vh"
            WIDTH: "100%"
            HEADLINE: ""
