# yaml-language-server: $schema=./values.schema.json
image:
  pullPolicy: IfNotPresent
  repository: ghcr.io/coderaiser/cloudcmd
  tag: 19.9.6@sha256:44bb5f5132003b08ee621938f90e19474c6d1bbc4c8b225c765b879b8184e9ef
persistence:
  appdata:
    enabled: true
    mountPath: /root
  mountpath:
    enabled: true
    mountPath: /UNRAID

securityContext:
  container:
    readOnlyRootFilesystem: false
    runAsGroup: 0
    runAsUser: 0
service:
  main:
    ports:
      main:
        port: 8765
        protocol: tcp
        targetPort: 8000
workload:
  main:
    podSpec:
      containers:
        main:
          env:
            HOME: /root
