# yaml-language-server: $schema=./values.schema.json
image:
  pullPolicy: IfNotPresent
  repository: ghcr.io/coderaiser/cloudcmd
  tag: 19.20.7@sha256:d18e8b4a3a8cb9b5c503950704b6a367a40ed40aa05d10c7c8db539809999454
persistence:
  appdata:
    enabled: true
    mountPath: /root
  mountpath:
    enabled: true
    mountPath: /UNRAID

securityContext:
  container:
    readOnlyRootFilesystem: false
    runAsGroup: 0
    runAsUser: 0
service:
  main:
    ports:
      main:
        port: 8765
        protocol: tcp
        targetPort: 8000
workload:
  main:
    podSpec:
      containers:
        main:
          env:
            HOME: /root
