# yaml-language-server: $schema=./values.schema.json
image:
  repository: oci.trueforge.org/containerforge/jackett
  pullPolicy: IfNotPresent
  tag: 0.24.2277@sha256:deca35aebd11ebff3bc581b5055217cd71159decaaca3c17cb2bf09a3948d30f
service:
  main:
    ports:
      main:
        protocol: http
        targetPort: 9117
        port: 9117
workload:
  main:
    podSpec:
      containers:
        main:
          probes:
            liveness:
              path: "/health"
            readiness:
              path: "/health"
            startup:
              path: "/health"
persistence:
  config:
    enabled: true
    mountPath: "/config"
