# yaml-language-server: $schema=./values.schema.json
image:
  repository: oci.trueforge.org/containerforge/jackett
  pullPolicy: IfNotPresent
  tag: 0.24.2353@sha256:1ef341eb09d8a0f814e64dae823982ddcbeb6857ae3159164ff6eadf874cb30f
service:
  main:
    ports:
      main:
        protocol: http
        targetPort: 9117
        port: 9117
workload:
  main:
    podSpec:
      containers:
        main:
          probes:
            liveness:
              path: "/health"
            readiness:
              path: "/health"
            startup:
              path: "/health"
persistence:
  config:
    enabled: true
    mountPath: "/config"
