# yaml-language-server: $schema=./values.schema.json
image:
  pullPolicy: IfNotPresent
  repository: docker.io/bndw/wifi-card
  tag: latest@sha256:f3ae8dc3b6741391c965f1a2c3afc77d51ce0d5af2c4c1203fb3991c1e13187b

securityContext:
  container:
    readOnlyRootFilesystem: false
    runAsGroup: 0
    runAsUser: 0

service:
  main:
    ports:
      main:
        protocol: http
        targetPort: 80
        port: 8888
