# yaml-language-server: $schema=./values.schema.json
image:
  pullPolicy: IfNotPresent
  repository: docker.io/bndw/wifi-card
  tag: latest@sha256:1ef3993bbb4548d6c6d1b043c9c304c154acbf60d4c48318848446e321483849

securityContext:
  container:
    readOnlyRootFilesystem: false
    runAsGroup: 0
    runAsUser: 0

service:
  main:
    ports:
      main:
        protocol: http
        targetPort: 80
        port: 8888
