# yaml-language-server: $schema=./values.schema.json
image:
  pullPolicy: IfNotPresent
  repository: docker.io/bndw/wifi-card
  tag: latest@sha256:c87998403ecca9bff49824a9a18f2d75ebfc2f91466388681fe8d4cc5e28d429

securityContext:
  container:
    readOnlyRootFilesystem: false
    runAsGroup: 0
    runAsUser: 0

service:
  main:
    ports:
      main:
        protocol: http
        targetPort: 80
        port: 8888
