image:
  repository: ghcr.io/wizarrrr/wizarr
  pullPolicy: IfNotPresent
  tag: 2025.7.5@sha256:eebc736c1eb23488e669d0816fe9eb9d4e48effb569f3c3f44404771d5cfe363
service:
  main:
    ports:
      main:
        protocol: http
        targetPort: 5690
        port: 10596
securityContext:
  container:
    runAsUser: 0
    runAsGroup: 0
    runAsNonRoot: false
    readOnlyRootFilesystem: false
workload:
  main:
    podSpec:
      containers:
        main:
          probes:
            liveness:
              path: "/"
              type: http
            readiness:
              path: "/"
              type: http
            startup:
              type: tcp
          env:
            DISABLE_BUILTIN_AUTH: false
persistence:
  database:
    enabled: true
    mountPath: /data/database
  varrun:
    enabled: false
    type: emptyDir
    mountPath: /var/run
  nginxrun:
    enabled: true
    type: emptyDir
    mountPath: /run/nginx
