# yaml-language-server: $schema=./values.schema.json
image:
  repository: docker.io/cyb3rjak3/dockeryourxyzzy
  pullPolicy: IfNotPresent
  tag: on-demand-v2.1.1@sha256:8c25e08714170685ae286b01d6a25de2b1042e6dc0704acf93b976689e3fd5cc
service:
  main:
    ports:
      main:
        port: 10094
        targetPort: 8080

securityContext:
  container:
    readOnlyRootFilesystem: false
    runAsNonRoot: false
    runAsUser: 0
    runAsGroup: 0
