# yaml-language-server: $schema=./values.schema.json
image:
  repository: docker.io/cyb3rjak3/dockeryourxyzzy
  tag: v2.1.1@sha256:adb0348932e76e56067e3b5fa304fc6918298242ec6a3943d9a216198c4df5be
  pullPolicy: IfNotPresent
service:
  main:
    ports:
      main:
        port: 10094
        targetPort: 8080

securityContext:
  container:
    readOnlyRootFilesystem: false
    runAsNonRoot: false
    runAsUser: 0
    runAsGroup: 0
