image:
  pullPolicy: IfNotPresent
  repository: docker.io/dlandon/zoneminder.unraid
  tag: latest@sha256:7734f2e6b3fa3220ccbca1cf65591361377bea82e3e80d6bafa2260f7576a344
persistence:
  varrun:
    enabled: false
  config:
    enabled: true
    mountPath: /config
  datapath:
    enabled: true
    mountPath: /var/cache/zoneminder

securityContext:
  container:
    readOnlyRootFilesystem: false
    runAsGroup: 0
    runAsUser: 0
service:
  main:
    ports:
      main:
        port: 10292
        protocol: https
        targetPort: 443
  zmninja:
    enabled: true
    ports:
      zmninja:
        enabled: true
        port: 10293
        protocol: tcp
        targetPort: 9000
workload:
  main:
    podSpec:
      containers:
        main:
          probes:
            liveness:
              path: /zm
            readiness:
              path: /zm
            startup:
              path: /zm
