# yaml-language-server: $schema=./values.schema.json
image:
  repository: ghcr.io/whyour/qinglong
  pullPolicy: IfNotPresent
  tag: 2.22.0@sha256:7bfdc8eeb96871d06818fbb8d6b99a8e2d3b66eaab15209393a5d9226268de4f
service:
  main:
    ports:
      main:
        targetPort: 5700
        port: 10176
persistence:
  data:
    enabled: true
    mountPath: "/ql/data"

securityContext:
  container:
    readOnlyRootFilesystem: false
    runAsNonRoot: false
    runAsUser: 0
    runAsGroup: 0
