# yaml-language-server: $schema=./values.schema.json
image:
  repository: docker.io/whyour/qinglong
  pullPolicy: IfNotPresent
  tag: 2.21.0@sha256:2e08e375f835cdfaa3b97d58dc2469a77f32217c5b424b597b838f9c0f9df7f8
service:
  main:
    ports:
      main:
        targetPort: 5700
        port: 10176
persistence:
  data:
    enabled: true
    mountPath: "/ql/data"

securityContext:
  container:
    readOnlyRootFilesystem: false
    runAsNonRoot: false
    runAsUser: 0
    runAsGroup: 0
