# yaml-language-server: $schema=./values.schema.json
image:
  repository: docker.io/whyour/qinglong
  pullPolicy: IfNotPresent
  tag: 2.21.0@sha256:8bf1c2cb4b6bc696d35318e8d8c209bac1d7f1641f6812fd893dd89554614637
service:
  main:
    ports:
      main:
        targetPort: 5700
        port: 10176
persistence:
  data:
    enabled: true
    mountPath: "/ql/data"

securityContext:
  container:
    readOnlyRootFilesystem: false
    runAsNonRoot: false
    runAsUser: 0
    runAsGroup: 0
