# yaml-language-server: $schema=./values.schema.json
image:
  repository: docker.io/privoce/vocechat-server
  pullPolicy: IfNotPresent
  tag: v0.5.25@sha256:c151519900cf65f5078c0ddfb0f9903e97180e0e6667bcd4cf265c24cc9b181f

service:
  main:
    ports:
      main:
        protocol: http
        port: 3009

vocechat:
  frontend_url: localhost:3009

workload:
  main:
    podSpec:
      containers:
        main:
          args:
            - --network.bind
            - 0.0.0.0:{{ .Values.service.main.ports.main.port }}
            - --network.frontend_url
            - "{{ .Values.vocechat.frontend_url }}"

persistence:
  data:
    enabled: true
    mountPath: "/home/vocechat-server/data"
