# yaml-language-server: $schema=./values.schema.json
image:
  repository: docker.io/privoce/vocechat-server
  pullPolicy: IfNotPresent
  tag: v0.5.16@sha256:d62875cd7d528621a10ce302ff6176d1596b9e8c9cce272b453b3a60d481a9ff

service:
  main:
    ports:
      main:
        protocol: http
        port: 3009

vocechat:
  frontend_url: localhost:3009

workload:
  main:
    podSpec:
      containers:
        main:
          args:
            - --network.bind
            - 0.0.0.0:{{ .Values.service.main.ports.main.port }}
            - --network.frontend_url
            - "{{ .Values.vocechat.frontend_url }}"

persistence:
  data:
    enabled: true
    mountPath: "/home/vocechat-server/data"
