# yaml-language-server: $schema=./values.schema.json
image:
  repository: oci.trueforge.org/containerforge/jellyseerr
  tag: "2.7.3@sha256:9afe374838fcdc23d2eb17b2f9d656c97cbd90064bc6b89f4c0e84c91684e7ea"
  pullPolicy: IfNotPresent
service:
  main:
    ports:
      main:
        port: 10241
persistence:
  config:
    enabled: true
    mountPath: "/app/config"

workload:
  main:
    podSpec:
      containers:
        main:
          env:
            PORT: "{{ .Values.service.main.ports.main.port }}"
            # User Defined
            JELLYFIN_TYPE: ""
            LOG_LEVEL: "info"
