image:
  repository: ghcr.io/fallenbagel/jellyseerr
  tag: 2.7.1@sha256:702603e935a295b8745bafe706373e2941b1df238de161e0319d5942e1fa432c
  pullPolicy: IfNotPresent
service:
  main:
    ports:
      main:
        port: 10241
persistence:
  config:
    enabled: true
    mountPath: "/app/config"

workload:
  main:
    podSpec:
      containers:
        main:
          env:
            PORT: "{{ .Values.service.main.ports.main.port }}"
            # User Defined
            JELLYFIN_TYPE: ""
            LOG_LEVEL: "info"
