# yaml-language-server: $schema=./values.schema.json
image:
  repository: docker.io/filebrowser/filebrowser
  pullPolicy: IfNotPresent
  tag: v2.63.18@sha256:c4c627f687668c5a02ab410d8473712c77be7f1f0ea4f8d624d2a1392c495e76
workload:
  main:
    podSpec:
      containers:
        main:
          probes:
            liveness:
              type: http
              path: /
            readiness:
              type: http
              path: /
            startup:
              type: http
              path: /
          env:
            FB_ADDRESS: ""
            FB_BASEURL: ""
            FB_DATABASE: "/database/filebrowser.db"
            FB_CONFIG: "/config/filebrowser.json"
            FB_ROOT: "/data"
            FB_PORT: "{{ .Values.service.main.ports.main.port }}"
service:
  main:
    ports:
      main:
        port: 10187
persistence:
  config:
    enabled: true
    mountPath: /config
  database:
    enabled: true
    mountPath: /database
  data:
    enabled: true
    mountPath: /data
