# yaml-language-server: $schema=./values.schema.json
image:
  repository: docker.io/filebrowser/filebrowser
  pullPolicy: IfNotPresent
  tag: v2.63.2@sha256:4dce87308b9f9cfbcf8d0a284fc9565d2b515530a6bae2d920b388161e093f26
workload:
  main:
    podSpec:
      containers:
        main:
          probes:
            liveness:
              type: http
              path: /
            readiness:
              type: http
              path: /
            startup:
              type: http
              path: /
          env:
            FB_ADDRESS: ""
            FB_BASEURL: ""
            FB_DATABASE: "/database/filebrowser.db"
            FB_CONFIG: "/config/filebrowser.json"
            FB_ROOT: "/data"
            FB_PORT: "{{ .Values.service.main.ports.main.port }}"
service:
  main:
    ports:
      main:
        port: 10187
persistence:
  config:
    enabled: true
    mountPath: /config
  database:
    enabled: true
    mountPath: /database
  data:
    enabled: true
    mountPath: /data
