# yaml-language-server: $schema=./values.schema.json
image:
  repository: docker.io/linuxserver/transmission
  pullPolicy: IfNotPresent
  tag: 4.1.1@sha256:bd9d4858be1138787cd3e4d05d2f8be72ab24685117361f47184f95d9215d859
service:
  main:
    ports:
      main:
        port: 9091
        targetPort: 9091
  torrent:
    enabled: true
    ports:
      torrent:
        enabled: true
        port: 51414
        protocol: tcp
      torrentudp:
        enabled: true
        port: "{{ .Values.service.torrent.ports.torrent.port }}"
        protocol: udp
securityContext:
  container:
    readOnlyRootFilesystem: false
    runAsNonRoot: false
    runAsUser: 0
    runAsGroup: 0
workload:
  main:
    podSpec:
      containers:
        main:
          probes:
            liveness:
              enabled: true
              type: tcp
            startup:
              enabled: true
              type: tcp
            readiness:
              enabled: true
              type: tcp
          env:
            PEERPORT: "{{ .Values.service.torrent.ports.torrent.port }}"
persistence:
  config:
    enabled: true
    mountPath: "/config"

manifestManager:
  enabled: false
