# yaml-language-server: $schema=./values.schema.json
image:
  repository: ghcr.io/ether/etherpad
  pullPolicy: IfNotPresent
  tag: 2.7.2@sha256:b723fe5f2594d5cf61f960a203a4eeb554a5d0435c3689722f575f91aa6ace50
securityContext:
  container:
    readOnlyRootFilesystem: false
    runAsNonRoot: false
    runAsUser: 0
    runAsGroup: 0
service:
  main:
    ports:
      main:
        port: 10060
        targetPort: 9001
workload:
  main:
    podSpec:
      containers:
        main:
          env:
            DB_TYPE: "postgres"
            DB_NAME: "{{ .Values.cnpg.main.database }}"
            DB_USER: "{{ .Values.cnpg.main.user }}"
            DB_PORT: "5432"
            DB_PASS:
              secretKeyRef:
                name: cnpg-main-user
                key: password
            DB_HOST:
              secretKeyRef:
                name: cnpg-main-urls
                key: host
            # User Defined

            TITLE: "Etherpad"
            FAVICON: "favicon.ico"
            DEFAULT_PAD_TEXT: "Welcome to Etherpad! This pad text is synchronized as you type, so that everyone viewing this page sees the same text. This allows you to collaborate seamlessly on documents! Get involved with Etherpad at https://etherpad.org"
            ADMIN_PASSWORD: "adminpass"
            USER_PASSWORD: "firstuserpass"
persistence:
  data:
    enabled: true
    mountPath: "/opt/etherpad-lite/var"
cnpg:
  main:
    enabled: true
    user: etherpad
    database: etherpad
