# yaml-language-server: $schema=./values.schema.json
image:
  repository: ghcr.io/ether/etherpad
  pullPolicy: IfNotPresent
  tag: 3.3.2@sha256:044e5b58686f22e2c8b792ed0a7c35a83986458e1ee91f12119276c1e2572bce
securityContext:
  container:
    readOnlyRootFilesystem: false
    runAsNonRoot: false
    runAsUser: 0
    runAsGroup: 0
service:
  main:
    ports:
      main:
        port: 10060
        targetPort: 9001
workload:
  main:
    podSpec:
      containers:
        main:
          env:
            DB_TYPE: "postgres"
            DB_NAME: "{{ .Values.cnpg.main.database }}"
            DB_USER: "{{ .Values.cnpg.main.user }}"
            DB_PORT: "5432"
            DB_PASS:
              secretKeyRef:
                name: cnpg-main-user
                key: password
            DB_HOST:
              secretKeyRef:
                name: cnpg-main-urls
                key: host
            # User Defined

            TITLE: "Etherpad"
            FAVICON: "favicon.ico"
            DEFAULT_PAD_TEXT: "Welcome to Etherpad! This pad text is synchronized as you type, so that everyone viewing this page sees the same text. This allows you to collaborate seamlessly on documents! Get involved with Etherpad at https://etherpad.org"
            ADMIN_PASSWORD: "adminpass"
            USER_PASSWORD: "firstuserpass"
persistence:
  data:
    enabled: true
    mountPath: "/opt/etherpad-lite/var"
cnpg:
  main:
    enabled: true
    user: etherpad
    database: etherpad
