# yaml-language-server: $schema=./values.schema.json
image:
  repository: ghcr.io/ether/etherpad
  pullPolicy: IfNotPresent
  tag: 3.3.1@sha256:c4bcd4b3365222b6a0e1d596dcebfddccd47bb2c80ebe4ab903d2393d8eeea9c
securityContext:
  container:
    readOnlyRootFilesystem: false
    runAsNonRoot: false
    runAsUser: 0
    runAsGroup: 0
service:
  main:
    ports:
      main:
        port: 10060
        targetPort: 9001
workload:
  main:
    podSpec:
      containers:
        main:
          env:
            DB_TYPE: "postgres"
            DB_NAME: "{{ .Values.cnpg.main.database }}"
            DB_USER: "{{ .Values.cnpg.main.user }}"
            DB_PORT: "5432"
            DB_PASS:
              secretKeyRef:
                name: cnpg-main-user
                key: password
            DB_HOST:
              secretKeyRef:
                name: cnpg-main-urls
                key: host
            # User Defined

            TITLE: "Etherpad"
            FAVICON: "favicon.ico"
            DEFAULT_PAD_TEXT: "Welcome to Etherpad! This pad text is synchronized as you type, so that everyone viewing this page sees the same text. This allows you to collaborate seamlessly on documents! Get involved with Etherpad at https://etherpad.org"
            ADMIN_PASSWORD: "adminpass"
            USER_PASSWORD: "firstuserpass"
persistence:
  data:
    enabled: true
    mountPath: "/opt/etherpad-lite/var"
cnpg:
  main:
    enabled: true
    user: etherpad
    database: etherpad
