# yaml-language-server: $schema=./values.schema.json
image:
  repository: ghcr.io/haveagitgat/tdarr_node
  pullPolicy: IfNotPresent
  tag: 2.94.03@sha256:6dc54a25e88b182aae9b2d8a9ab2eda002b325b827b5873e3aedfda845aa17d8
service:
  main:
    enabled: false
    ports:
      main:
        enabled: false
persistence:
  configs:
    enabled: true
    mountPath: "/app/configs"
  logs:
    enabled: true
    mountPath: "/app/logs"
  transcode-cache:
    enabled: true
    mountPath: "/temp"
  media:
    enabled: true
    mountPath: "/media"
  varrun:
    enabled: true

securityContext:
  container:
    readOnlyRootFilesystem: false
    runAsNonRoot: false
    runAsUser: 0
    runAsGroup: 0
workload:
  main:
    podSpec:
      containers:
        main:
          probes:
            liveness:
              enabled: false
            readiness:
              enabled: false
            startup:
              enabled: false
          env:
            # User Defined
            nodeID: "myFirstTdarrNode"
            serverIP: "0.0.0.0"
            serverPort: 8266
