# yaml-language-server: $schema=./values.schema.json
image:
  repository: docker.io/haveagitgat/tdarr_node
  pullPolicy: IfNotPresent
  tag: 2.84.01@sha256:9d8d3a24c88cc0ff2121565bb774ddd082694be3b6fb7cc0b5c9391e2c550db9
service:
  main:
    enabled: false
    ports:
      main:
        enabled: false
persistence:
  configs:
    enabled: true
    mountPath: "/app/configs"
  logs:
    enabled: true
    mountPath: "/app/logs"
  transcode-cache:
    enabled: true
    mountPath: "/temp"
  media:
    enabled: true
    mountPath: "/media"
  varrun:
    enabled: true

securityContext:
  container:
    readOnlyRootFilesystem: false
    runAsNonRoot: false
    runAsUser: 0
    runAsGroup: 0
workload:
  main:
    podSpec:
      containers:
        main:
          probes:
            liveness:
              enabled: false
            readiness:
              enabled: false
            startup:
              enabled: false
          env:
            # User Defined
            nodeID: "myFirstTdarrNode"
            serverIP: "0.0.0.0"
            serverPort: 8266
