# yaml-language-server: $schema=./values.schema.json
image:
  repository: ghcr.io/linuxserver/grav
  pullPolicy: IfNotPresent
  tag: 2.0.3@sha256:5178726262f8a5fcfff67c8c8e7103b9a2874e35742b09a6c70e8fd79e6b36fd
service:
  main:
    ports:
      main:
        port: 10012
        targetPort: 80
persistence:
  config:
    enabled: true
    mountPath: "/config"
  varrun:
    enabled: true

securityContext:
  container:
    readOnlyRootFilesystem: false
    runAsNonRoot: false
    runAsUser: 0
    runAsGroup: 0
