# yaml-language-server: $schema=./values.schema.json
image:
  repository: ghcr.io/linuxserver/grav
  pullPolicy: IfNotPresent
  tag: 2.0.9@sha256:1dfc09866cac79018e34b79065cdab973287e9eb7532078960cc19ead7cf1e2d
service:
  main:
    ports:
      main:
        port: 10012
        targetPort: 80
persistence:
  config:
    enabled: true
    mountPath: "/config"
  varrun:
    enabled: true

securityContext:
  container:
    readOnlyRootFilesystem: false
    runAsNonRoot: false
    runAsUser: 0
    runAsGroup: 0
