# yaml-language-server: $schema=./values.schema.json
image:
  repository: ghcr.io/linuxserver/grav
  pullPolicy: IfNotPresent
  tag: 2.1.6@sha256:b2a49695938cdb572827416e5bfbe7f1647d99f72f6f73ca5e5a6278ee474a11
service:
  main:
    ports:
      main:
        port: 10012
        targetPort: 80
persistence:
  config:
    enabled: true
    mountPath: "/config"
  varrun:
    enabled: true

securityContext:
  container:
    readOnlyRootFilesystem: false
    runAsNonRoot: false
    runAsUser: 0
    runAsGroup: 0
