# yaml-language-server: $schema=./values.schema.json
image:
  repository: ghcr.io/linuxserver/ombi
  pullPolicy: IfNotPresent
  tag: 4.53.10@sha256:527b0e9046f3ad38afad837206c5a02de2a2061ac69aee69a876a19d3b0d2996
service:
  main:
    ports:
      main:
        port: 3579
        targetPort: 3579
persistence:
  config:
    enabled: true
    mountPath: "/config"

securityContext:
  container:
    readOnlyRootFilesystem: false
    runAsUser: 0
    runAsGroup: 0
    allowPrivilegeEscalation: true
