# yaml-language-server: $schema=./values.schema.json
image:
  repository: ghcr.io/linuxserver/ombi
  pullPolicy: IfNotPresent
  tag: 4.53.5@sha256:fb6f5f8bdc66ea124c37cfb6b146b4121d27e171cd15d4c637fe9d3c3df6dea6
service:
  main:
    ports:
      main:
        port: 3579
        targetPort: 3579
persistence:
  config:
    enabled: true
    mountPath: "/config"

securityContext:
  container:
    readOnlyRootFilesystem: false
    runAsUser: 0
    runAsGroup: 0
    allowPrivilegeEscalation: true
