# yaml-language-server: $schema=./values.schema.json
image:
  repository: ghcr.io/linuxserver/ombi
  pullPolicy: IfNotPresent
  tag: 4.53.4@sha256:b9189f51a06300fce7ff0c71b48eca5b0d862aa3c750215e292ef348d545d9cf
service:
  main:
    ports:
      main:
        port: 3579
        targetPort: 3579
persistence:
  config:
    enabled: true
    mountPath: "/config"

securityContext:
  container:
    readOnlyRootFilesystem: false
    runAsUser: 0
    runAsGroup: 0
    allowPrivilegeEscalation: true
