# yaml-language-server: $schema=./values.schema.json
image:
  repository: docker.io/mtlynch/picoshare
  tag: v1.5.4@sha256:053fee7cbdc64894e924733d5405158a9baadbecd231bfe97ae69d16fd2c2639
  pullPolicy: IfNotPresent
service:
  main:
    ports:
      main:
        port: 10209
workload:
  main:
    podSpec:
      containers:
        main:
          env:
            PORT: "{{ .Values.service.main.ports.main.port }}"
            # web admin password
            PS_SHARED_SECRET: "somesecretcode"
            # optional
            LITESTREAM_BUCKET: ""
            LITESTREAM_ENDPOINT: ""
            LITESTREAM_ACCESS_KEY_ID: ""
            LITESTREAM_SECRET_ACCESS_KEY: ""
            LITESTREAM_RETENTION: 72h
persistence:
  data:
    enabled: true
    mountPath: "/data"
