# yaml-language-server: $schema=./values.schema.json
image:
  pullPolicy: IfNotPresent
  repository: docker.io/sublivion/gridcoinwalletgui
  tag: latest@sha256:04abc8ef06c9ef5f476c3fe6cc441209d325752316e1b9d8ed0116840be94fd4
persistence:
  appdataconfigpath:
    enabled: true
    mountPath: /headless/.GridcoinResearch/
  boincdatadir:
    enabled: true
    mountPath: /var/lib/boinc-client/

securityContext:
  container:
    readOnlyRootFilesystem: false
    runAsGroup: 0
    runAsUser: 0
service:
  main:
    ports:
      main:
        port: 6901
        protocol: http
        targetPort: 6901
  vncport:
    enabled: true
    ports:
      vncport:
        enabled: true
        port: 5901
        protocol: tcp
        targetPort: 5901
workload:
  main:
    podSpec:
      containers:
        main:
          env:
            VNC_PW: vncpassword
            VNC_RESOLUTION: 1920x1080
