# yaml-language-server: $schema=./values.schema.json
image:
  repository: docker.io/cglatot/pasta
  pullPolicy: IfNotPresent
  tag: 2.2.12@sha256:8d7cab9baed258be9255f9a6c00e85fd1dd7554553c6f5fbde49b55d5c9fcca5
service:
  main:
    ports:
      main:
        port: 10302
        protocol: http
        targetPort: 80

securityContext:
  container:
    readOnlyRootFilesystem: false
    runAsNonRoot: false
    runAsGroup: 0
    runAsUser: 0
