# yaml-language-server: $schema=./values.schema.json
image:
  repository: docker.io/cglatot/pasta
  pullPolicy: IfNotPresent
  tag: 2.2.10@sha256:f020e91e46a03a594a6c7b3e6533b12d1abdc12c656a704296dc4f06be5933cc
service:
  main:
    ports:
      main:
        port: 10302
        protocol: http
        targetPort: 80

securityContext:
  container:
    readOnlyRootFilesystem: false
    runAsNonRoot: false
    runAsGroup: 0
    runAsUser: 0
