# yaml-language-server: $schema=./values.schema.json
image:
  repository: docker.io/cglatot/pasta
  pullPolicy: IfNotPresent
  tag: 2.2.8@sha256:03fe1de8d67df5e9b948757631af46038d58bfdf79c540efb96d06b18cbb5b54
service:
  main:
    ports:
      main:
        port: 10302
        protocol: http
        targetPort: 80

securityContext:
  container:
    readOnlyRootFilesystem: false
    runAsNonRoot: false
    runAsGroup: 0
    runAsUser: 0
