# yaml-language-server: $schema=./values.schema.json
image:
  repository: ghcr.io/linuxserver/medusa
  pullPolicy: IfNotPresent
  tag: 1.0.26@sha256:baef2ac1a66ff62c4173cde170fe0b14a5726b3abfe63b1e8ee93ea04476b392
service:
  main:
    ports:
      main:
        port: 10068
        targetPort: 8081
persistence:
  config:
    enabled: true
    mountPath: "/config"
  varrun:
    enabled: true

securityContext:
  container:
    readOnlyRootFilesystem: false
    runAsNonRoot: false
    runAsUser: 0
    runAsGroup: 0
