# yaml-language-server: $schema=./values.schema.json
image:
  repository: ghcr.io/linuxserver/medusa
  pullPolicy: IfNotPresent
  tag: 1.0.25@sha256:dbe3ee467d36e32903b32cf03b9d2e502912ac47aa64a47768fbf6856eb481cb
service:
  main:
    ports:
      main:
        port: 10068
        targetPort: 8081
persistence:
  config:
    enabled: true
    mountPath: "/config"
  varrun:
    enabled: true

securityContext:
  container:
    readOnlyRootFilesystem: false
    runAsNonRoot: false
    runAsUser: 0
    runAsGroup: 0
