# yaml-language-server: $schema=./values.schema.json
image:
  repository: ghcr.io/linuxserver/medusa
  pullPolicy: IfNotPresent
  tag: 1.0.26@sha256:38c2f0afec20fb66c9a9dfdfdefa38f9a52a528a6a4930e6671522f30aaf9ef3
service:
  main:
    ports:
      main:
        port: 10068
        targetPort: 8081
persistence:
  config:
    enabled: true
    mountPath: "/config"
  varrun:
    enabled: true

securityContext:
  container:
    readOnlyRootFilesystem: false
    runAsNonRoot: false
    runAsUser: 0
    runAsGroup: 0
