# yaml-language-server: $schema=./values.schema.json
image:
  repository: ghcr.io/alexta69/metube
  tag: 2026.09.15@sha256:5ebff7a547bf175e614c024053e5602a0b9193586a20c107dd47d571c391e635
  pullPolicy: IfNotPresent
service:
  main:
    ports:
      main:
        port: 10216
        targetPort: 8081
persistence:
  config:
    enabled: true
    mountPath: /config
  downloads:
    enabled: true
    mountPath: /downloads

workload:
  main:
    podSpec:
      containers:
        main:
          env:
            STATE_DIR: /config
            DOWNLOAD_DIR: /downloads
            OUTPUT_TEMPLATE: "%(title)s.%(ext)s"
            YTDL_OPTIONS: "{}"
