# yaml-language-server: $schema=./values.schema.json
image:
  repository: ghcr.io/alexta69/metube
  tag: 2026.03.03@sha256:2abd785e515a632562deafd3cb97d318c7acc63b5cec0657b36f257d0254d8e4
  pullPolicy: IfNotPresent
service:
  main:
    ports:
      main:
        port: 10216
        targetPort: 8081
persistence:
  config:
    enabled: true
    mountPath: /config
  downloads:
    enabled: true
    mountPath: /downloads

workload:
  main:
    podSpec:
      containers:
        main:
          env:
            STATE_DIR: /config
            DOWNLOAD_DIR: /downloads
            OUTPUT_TEMPLATE: "%(title)s.%(ext)s"
            YTDL_OPTIONS: "{}"
