# yaml-language-server: $schema=./values.schema.json
image:
  repository: ghcr.io/alexta69/metube
  tag: 2026.07.21@sha256:b0a27dc1505460d2eaf9a6713b486a01d11733043622e49a2572ee5cbe9f0503
  pullPolicy: IfNotPresent
service:
  main:
    ports:
      main:
        port: 10216
        targetPort: 8081
persistence:
  config:
    enabled: true
    mountPath: /config
  downloads:
    enabled: true
    mountPath: /downloads

workload:
  main:
    podSpec:
      containers:
        main:
          env:
            STATE_DIR: /config
            DOWNLOAD_DIR: /downloads
            OUTPUT_TEMPLATE: "%(title)s.%(ext)s"
            YTDL_OPTIONS: "{}"
