# yaml-language-server: $schema=./values.schema.json
image:
  pullPolicy: IfNotPresent
  repository: ghcr.io/ngosang/amule
  tag: 3.1.0-1@sha256:3f57ba34afa28f6c4bfc8871fcb70ece57771738e69bcc3a30a9a82ce8716a1d
securityContext:
  container:
    readOnlyRootFilesystem: false
    runAsNonRoot: false
    runAsGroup: 0
    runAsUser: 0
service:
  main:
    ports:
      main:
        port: 4711
        protocol: http
        targetPort: 4711
  remote:
    enabled: true
    ports:
      gui:
        enabled: true
        port: 4712
        protocol: tcp
        targetPort: 4712
  ed2k:
    enabled: true
    ports:
      tcp:
        enabled: true
        port: 4662
        protocol: tcp
        targetPort: 4662
      # ed2k global search udp (tcp port +3)
      udp:
        enabled: true
        port: 4665
        protocol: udp
        targetPort: 4665
      udp2:
        enabled: true
        port: 4672
        protocol: udp
        targetPort: 4672
workload:
  main:
    podSpec:
      containers:
        main:
          probes:
            liveness:
              type: http
              path: /
            readiness:
              type: http
              path: /
            startup:
              type: http
              path: /
          env:
            WEBUI_PWD: "CHANGE_ME_VERY_SECURE"
            GUI_PWD: "CHANGE_ME_VERY_SECURE"
            # MOD_AUTO_RESTART_ENABLED: true
            # MOD_AUTO_RESTART_CRON: "0 6 * * *"

persistence:
  config:
    enabled: true
    mountPath: /home/amule/.aMule
  downloads:
    enabled: true
    mountPath: /downloads

# aMule stores completed downloads in /downloads/incoming and 
# incomplete downloads in /downloads/temp inside the container. 
# These paths can be changed with the INCOMING_DIR and TEMP_DIR environment variables.
# You can also mount /downloads/incoming and /downloads/temp as separate volumes,
# but be aware that completed files will be copied instead of moved,
# since they would reside on different filesystems.

