# yaml-language-server: $schema=./values.schema.json
image:
  pullPolicy: IfNotPresent
  repository: lscr.io/linuxserver/cops
  tag: 4.3.1@sha256:1f0e37568e57824d7264f7c666d9e867079e462467b70a2b1a2919dff7217480
securityContext:
  container:
    readOnlyRootFilesystem: false
    runAsNonRoot: false
    runAsGroup: 0
    runAsUser: 0
service:
  main:
    ports:
      main:
        port: 10609
        protocol: http
        targetPort: 80
persistence:
  config:
    enabled: true
    mountPath: /config
  books:
    enabled: true
    mountPath: /books
