# yaml-language-server: $schema=./values.schema.json
image:
  repository: public.ecr.aws/zinclabs/openobserve
  tag: v0.80.2@sha256:8c12855e86d06e93c8d0f959f2bea6153a5011bb9cd2d0bbe1e6230957b95b9f
  pullPolicy: IfNotPresent

persistence:
  data:
    enabled: true
    mountPath: "/data"

workload:
  main:
    podSpec:
      containers:
        main:
          env:
            ZO_ROOT_USER_EMAIL: admin@example.com
            ZO_ROOT_USER_PASSWORD: changeme
            ZO_DATA_DIR: /data
            ZO_WEB_URL: "https://logs.example.com"
            ZO_TELEMETRY: "false"
          probes:
            liveness:
              path: "/healthz"
            readiness:
              path: "/healthz"
            startup:
              path: "/healthz"

service:
  main:
    ports:
      main:
        port: 5080
