# yaml-language-server: $schema=./values.schema.json
image:
  repository: public.ecr.aws/zinclabs/openobserve
  tag: v1.0.0@sha256:d581789cb03b5f061ed56a3e864b5e4bbc86bbf6d317ec863372e98ee49b30d5
  pullPolicy: IfNotPresent

persistence:
  data:
    enabled: true
    mountPath: "/data"

workload:
  main:
    podSpec:
      containers:
        main:
          env:
            ZO_ROOT_USER_EMAIL: admin@example.com
            ZO_ROOT_USER_PASSWORD: Changemechangemechangemechange1!
            ZO_DATA_DIR: /data
            ZO_WEB_URL: "https://logs.example.com"
            ZO_TELEMETRY: "false"
          probes:
            liveness:
              path: "/healthz"
            readiness:
              path: "/healthz"
            startup:
              path: "/healthz"

service:
  main:
    ports:
      main:
        port: 5080
