# yaml-language-server: $schema=./values.schema.json
image:
  repository: public.ecr.aws/zinclabs/openobserve
  tag: v0.91.5@sha256:012c9701b4b7a2f7070f9264a85eb7ed6d4998e4763628341924f06cdc810e6f
  pullPolicy: IfNotPresent

persistence:
  data:
    enabled: true
    mountPath: "/data"

workload:
  main:
    podSpec:
      containers:
        main:
          env:
            ZO_ROOT_USER_EMAIL: admin@example.com
            ZO_ROOT_USER_PASSWORD: Changemechangemechangemechange1!
            ZO_DATA_DIR: /data
            ZO_WEB_URL: "https://logs.example.com"
            ZO_TELEMETRY: "false"
          probes:
            liveness:
              path: "/healthz"
            readiness:
              path: "/healthz"
            startup:
              path: "/healthz"

service:
  main:
    ports:
      main:
        port: 5080
