# yaml-language-server: $schema=./values.schema.json
image:
  pullPolicy: IfNotPresent
  repository: ghcr.io/m1k1o/neko/firefox
  tag: 3.1.1@sha256:208d2f1b9ed0e75deb48b41607ded3b1cd2b514c6ab8b0e6aada3d95df8f09bb
braveImage:
  pullPolicy: IfNotPresent
  repository: ghcr.io/m1k1o/neko/brave
  tag: 3.1.1@sha256:226b673af5b54364f8223e882923ab2b9657f90bb7e9160d1191672aa94314c1
chromeImage:
  pullPolicy: IfNotPresent
  repository: ghcr.io/m1k1o/neko/google-chrome
  tag: 3.1.1@sha256:73faedd7a2893409da1d06d998989777db6ba86f7a53e538f0dea8fa0d7bb4f1
chromiumImage:
  pullPolicy: IfNotPresent
  repository: ghcr.io/m1k1o/neko/chromium
  tag: 3.1.1@sha256:71a59a5f12d8079320a84660a8cddb24cf17166f4bb252083705a89a639d76ac
edgeImage:
  pullPolicy: IfNotPresent
  repository: ghcr.io/m1k1o/neko/microsoft-edge
  tag: 3.1.1@sha256:37489757bdbfbef78faf9f83bccb9ecf8519d884d60299118c0b01c7a65acc84
remminaImage:
  pullPolicy: IfNotPresent
  repository: ghcr.io/m1k1o/neko/remmina
  tag: 3.1.1@sha256:ecdf1c717147110ba49410ced68f076b52533fc00340e8101766cff2489aae38
torImage:
  pullPolicy: IfNotPresent
  repository: ghcr.io/m1k1o/neko/tor-browser
  tag: 3.1.1@sha256:bf0cbc94135cd0ffc265b55286dc4cb09383c1276ef52d266ef947f15172cd07
vivaldiImage:
  pullPolicy: IfNotPresent
  repository: ghcr.io/m1k1o/neko/vivaldi
  tag: 3.1.1@sha256:6a42d70cb08d858e447ff71fb7243729a3b4f751f8546c66ef1cef266f754a3f
vlcImage:
  pullPolicy: IfNotPresent
  repository: ghcr.io/m1k1o/neko/vlc
  tag: 3.1.1@sha256:d67e2ecf8882b7550809c1e3624ac21264a15108e4c05a3baaa415f3b75537dc
xfceImage:
  pullPolicy: IfNotPresent
  repository: ghcr.io/m1k1o/neko/xfce
  tag: 3.1.1@sha256:5b071cd063defe6fbd63c42e2b6d293d01456b681814dec622f9ee0f24b32873

securityContext:
  container:
    readOnlyRootFilesystem: false
    runAsGroup: 0
    runAsUser: 0

service:
  main:
    ports:
      main:
        port: 10294
        protocol: http
  mux:
    enabled: true
    ports:
      tcp:
        enabled: true
        port: 52100
        protocol: tcp
      udp:
        enabled: true
        port: "{{ .Values.service.mux.ports.tcp.port }}"
        protocol: udp

neko:
  ip: "0.0.0.0"
  auth:
    user_pass: ""
    admin_pass: ""
  proxy: false
  screen: "1920x1080@30"
  control_protection: false
  implicit_control: false
  locks:
    []
    # - control
    # - login
    # - file_transfer
  cors:
    - "*"

workload:
  main:
    podSpec:
      containers:
        main:
          imageSelector: image
          env:
            NEKO_BIND: '{{ printf ":%v" .Values.service.main.ports.main.port }}'
            NEKO_PATH_PREFIX: "/"
            NEKO_NAT1TO1: "{{ .Values.neko.ip }}"
            # NEKO_EPR
            NEKO_TCPMUX: "{{ .Values.service.mux.ports.tcp.port }}"
            NEKO_UDPMUX: "{{ .Values.service.mux.ports.tcp.port }}"
            NEKO_FILE_TRANSFER_ENABLED: true
            NEKO_FILE_TRANSFER_PATH: "{{.Values.persistence.downloads.mountPath }}"
            NEKO_CONTROL_PROTECTION: "{{ .Values.neko.control_protection }}"
            NEKO_IMPLICIT_CONTROL: "{{ .Values.neko.implicit_control }}"
            NEKO_LOCKS: '{{ join " " .Values.neko.locks }}'
            NEKO_PASSWORD: "{{ .Values.neko.auth.user_pass }}"
            NEKO_PASSWORD_ADMIN: "{{ .Values.neko.auth.admin_pass }}"
            NEKO_PROXY: "{{ .Values.neko.proxy }}"
            NEKO_SCREEN: "{{ .Values.neko.screen }}"
            NEKO_CORS: '{{ join " " .Values.neko.cors }}'
            # NEKO_NAT1TO1: ""
            # NEKO_IPFETCH: ""
            # NEKO_ICELITE: false
            # NEKO_ICESERVER: ""
            # NEKO_ICESERVERS

persistence:
  downloads:
    enabled: true
    mountPath: /home/neko/Downloads
