# yaml-language-server: $schema=./values.schema.json
image:
  pullPolicy: IfNotPresent
  repository: ghcr.io/m1k1o/neko/firefox
  tag: 3.1.6@sha256:f832b3e28492b9cc10f702cc9feb9da462320502944fc0ddbddbcab352428e02
braveImage:
  pullPolicy: IfNotPresent
  repository: ghcr.io/m1k1o/neko/brave
  tag: 3.1.6@sha256:8b124028986ddae82d931a66c97ce1aa3cd8293db081eaaf3b612aa3bc72b129
chromeImage:
  pullPolicy: IfNotPresent
  repository: ghcr.io/m1k1o/neko/google-chrome
  tag: 3.1.6@sha256:dce2a6286cfb7e747d7fb05fadd03b25bf2db155c4f71ae53e0f40be71837547
chromiumImage:
  pullPolicy: IfNotPresent
  repository: ghcr.io/m1k1o/neko/chromium
  tag: 3.1.6@sha256:2471119c7b4010067f76f3421a78a8bcf35e3c223b2d1f4db084914ec915fb30
edgeImage:
  pullPolicy: IfNotPresent
  repository: ghcr.io/m1k1o/neko/microsoft-edge
  tag: 3.1.6@sha256:49f68c95a45c343a6aaaa6d8c33b4d48b8d3762edf1b08a794b7c0903fb7de63
remminaImage:
  pullPolicy: IfNotPresent
  repository: ghcr.io/m1k1o/neko/remmina
  tag: 3.1.6@sha256:607878a5487fdc2f14b0f2bfe11201fd4d7e5ffefc4c75e3298726fcdb997bfa
torImage:
  pullPolicy: IfNotPresent
  repository: ghcr.io/m1k1o/neko/tor-browser
  tag: 3.1.6@sha256:f1d9a234dbc417a92aa5bb0f9146263886c8af361fcbc10ceddf523fc4b561b4
vivaldiImage:
  pullPolicy: IfNotPresent
  repository: ghcr.io/m1k1o/neko/vivaldi
  tag: 3.1.6@sha256:4ddf4a3fe1b8bfb25a372a5f3837e5f01c146789bb838c77ef692537c708c947
vlcImage:
  pullPolicy: IfNotPresent
  repository: ghcr.io/m1k1o/neko/vlc
  tag: 3.1.6@sha256:023af43b6e9a207028e9391e000940646009df3aac1139caacbf93742bcb6c5e
xfceImage:
  pullPolicy: IfNotPresent
  repository: ghcr.io/m1k1o/neko/xfce
  tag: 3.1.6@sha256:c3ccf7b7f57767923bfe855f4f86618ad5b31c0fe21a346e348f7fc1004f753c

securityContext:
  container:
    readOnlyRootFilesystem: false
    runAsGroup: 0
    runAsUser: 0

service:
  main:
    ports:
      main:
        port: 10294
        protocol: http
  mux:
    enabled: true
    ports:
      tcp:
        enabled: true
        port: 52100
        protocol: tcp
      udp:
        enabled: true
        port: "{{ .Values.service.mux.ports.tcp.port }}"
        protocol: udp

neko:
  ip: "0.0.0.0"
  auth:
    user_pass: ""
    admin_pass: ""
  proxy: false
  screen: "1920x1080@30"
  control_protection: false
  implicit_control: false
  locks:
    []
    # - control
    # - login
    # - file_transfer
  cors:
    - "*"

workload:
  main:
    podSpec:
      containers:
        main:
          imageSelector: image
          env:
            NEKO_BIND: '{{ printf ":%v" .Values.service.main.ports.main.port }}'
            NEKO_PATH_PREFIX: "/"
            NEKO_NAT1TO1: "{{ .Values.neko.ip }}"
            # NEKO_EPR
            NEKO_TCPMUX: "{{ .Values.service.mux.ports.tcp.port }}"
            NEKO_UDPMUX: "{{ .Values.service.mux.ports.tcp.port }}"
            NEKO_FILE_TRANSFER_ENABLED: true
            NEKO_FILE_TRANSFER_PATH: "{{.Values.persistence.downloads.mountPath }}"
            NEKO_CONTROL_PROTECTION: "{{ .Values.neko.control_protection }}"
            NEKO_IMPLICIT_CONTROL: "{{ .Values.neko.implicit_control }}"
            NEKO_LOCKS: '{{ join " " .Values.neko.locks }}'
            NEKO_PASSWORD: "{{ .Values.neko.auth.user_pass }}"
            NEKO_PASSWORD_ADMIN: "{{ .Values.neko.auth.admin_pass }}"
            NEKO_PROXY: "{{ .Values.neko.proxy }}"
            NEKO_SCREEN: "{{ .Values.neko.screen }}"
            NEKO_CORS: '{{ join " " .Values.neko.cors }}'
            # NEKO_NAT1TO1: ""
            # NEKO_IPFETCH: ""
            # NEKO_ICELITE: false
            # NEKO_ICESERVER: ""
            # NEKO_ICESERVERS

persistence:
  downloads:
    enabled: true
    mountPath: /home/neko/Downloads
