image:
  repository: oci.trueforge.org/containerforge/lazylibrarian
  pullPolicy: IfNotPresent
  tag: "rolling"
service:
  main:
    ports:
      main:
        port: 5299
        targetPort: 5299
persistence:
  config:
    enabled: true
    mountPath: "/config"
  varrun:
    enabled: true

securityContext:
  container:
    runAsNonRoot: false
    readOnlyRootFilesystem: false
    runAsUser: 0
    runAsGroup: 0
