# yaml-language-server: $schema=./values.schema.json
image:
  repository: oci.trueforge.org/containerforge/lazylibrarian
  pullPolicy: IfNotPresent
  tag: 7.0.0@sha256:fabd1f418eba4d21f267db526d192a0cd5256c9418f3f02af3803c5fe60fb1b5
service:
  main:
    ports:
      main:
        port: 5299
        targetPort: 5299
persistence:
  config:
    enabled: true
    mountPath: "/config"
  varrun:
    enabled: true

securityContext:
  container:
    runAsNonRoot: false
    readOnlyRootFilesystem: false
    runAsUser: 0
    runAsGroup: 0
