# yaml-language-server: $schema=./values.schema.json
image:
  repository: oci.trueforge.org/containerforge/lazylibrarian
  pullPolicy: IfNotPresent
  tag: 7.0.0@sha256:0249c39457d7a9daa1f19a9caa58e63fe893ebb8de8452523d06273aed1fdb07
service:
  main:
    ports:
      main:
        port: 5299
        targetPort: 5299
persistence:
  config:
    enabled: true
    mountPath: "/config"
  varrun:
    enabled: true

securityContext:
  container:
    runAsNonRoot: false
    readOnlyRootFilesystem: false
    runAsUser: 0
    runAsGroup: 0
