# yaml-language-server: $schema=./values.schema.json
image:
  pullPolicy: IfNotPresent
  repository: docker.io/ronnieroller/media-roller
  tag: latest@sha256:67ff9b760306dabb2d2f1bc9789b2938bd9371eec78f5168bc82f5a8f7ae2007
persistence:
  download:
    enabled: true
    mountPath: /download

securityContext:
  container:
    readOnlyRootFilesystem: false
    runAsGroup: 0
    runAsUser: 0
service:
  main:
    ports:
      main:
        port: 3000
        protocol: tcp
        targetPort: 3000
