# yaml-language-server: $schema=./values.schema.json
image:
  pullPolicy: IfNotPresent
  repository: docker.io/ronnieroller/media-roller
  tag: latest@sha256:9fe980bb21e00f89f1fbf7b26a9a1307f87deca36b1e5805e4c5f0c824ddcb72
persistence:
  download:
    enabled: true
    mountPath: /download

securityContext:
  container:
    readOnlyRootFilesystem: false
    runAsGroup: 0
    runAsUser: 0
service:
  main:
    ports:
      main:
        port: 3000
        protocol: tcp
        targetPort: 3000
