# yaml-language-server: $schema=./values.schema.json
image:
  pullPolicy: IfNotPresent
  repository: lscr.io/linuxserver/pyload-ng
  tag: latest@sha256:ca0ea1a4068656595d22049b334cb32da28f9d8e51409d72268d6c354b5cd950
persistence:
  config:
    enabled: true
    mountPath: /config
  pathdownloads:
    enabled: true
    mountPath: /downloads

securityContext:
  container:
    readOnlyRootFilesystem: false
    runAsGroup: 0
    runAsUser: 0
service:
  main:
    ports:
      main:
        port: 8000
        protocol: http
        targetPort: 8000
  port9666:
    enabled: true
    ports:
      port9666:
        enabled: true
        port: 9666
        protocol: tcp
        targetPort: 9666
workload:
  main:
    podSpec:
      containers:
        main:
          env:
