# yaml-language-server: $schema=./values.schema.json
image:
  pullPolicy: IfNotPresent
  repository: lscr.io/linuxserver/pyload-ng
  tag: latest@sha256:d244f68ecf151ed3d8d2de8bc6c58dd2c3919b7edd6452c56b10a627990cec7a
persistence:
  config:
    enabled: true
    mountPath: /config
  pathdownloads:
    enabled: true
    mountPath: /downloads

securityContext:
  container:
    readOnlyRootFilesystem: false
    runAsGroup: 0
    runAsUser: 0
service:
  main:
    ports:
      main:
        port: 8000
        protocol: http
        targetPort: 8000
  port9666:
    enabled: true
    ports:
      port9666:
        enabled: true
        port: 9666
        protocol: tcp
        targetPort: 9666
workload:
  main:
    podSpec:
      containers:
        main:
          env:
