# yaml-language-server: $schema=./values.schema.json
image:
  repository: ghcr.io/linuxserver/boinc
  pullPolicy: IfNotPresent
  tag: latest@sha256:9de8480e149700dd8ad691752d86c29fca91830c3cc3d61adaab998d76a27be0
securityContext:
  container:
    readOnlyRootFilesystem: false
    runAsNonRoot: false
    runAsUser: 0
    runAsGroup: 0
service:
  main:
    ports:
      main:
        targetPort: 8080
        protocol: http
        port: 10142
workload:
  main:
    podSpec:
      containers:
        main:
          env:
            PASSWORD: ""
persistence:
  config:
    enabled: true
    mountPath: /config
