# yaml-language-server: $schema=./values.schema.json
image:
  repository: ghcr.io/linuxserver/boinc
  pullPolicy: IfNotPresent
  tag: latest@sha256:5fea740221b42fd49b9a1692b5546cc395a023fa41ad4f904eac4d6efe645991
securityContext:
  container:
    readOnlyRootFilesystem: false
    runAsNonRoot: false
    runAsUser: 0
    runAsGroup: 0
service:
  main:
    ports:
      main:
        targetPort: 8080
        protocol: tcp
        port: 10142
workload:
  main:
    podSpec:
      containers:
        main:
          env:
            PASSWORD: ""
persistence:
  config:
    enabled: true
    mountPath: /config
