# yaml-language-server: $schema=./values.schema.json
image:
  repository: ghcr.io/linuxserver/boinc
  pullPolicy: IfNotPresent
  tag: latest@sha256:09f6118099c73055ab8d79e1625a500fed359f68ce1a26a16f1aa668ce627b97
securityContext:
  container:
    readOnlyRootFilesystem: false
    runAsNonRoot: false
    runAsUser: 0
    runAsGroup: 0
service:
  main:
    ports:
      main:
        targetPort: 8080
        protocol: tcp
        port: 10142
workload:
  main:
    podSpec:
      containers:
        main:
          env:
            PASSWORD: ""
persistence:
  config:
    enabled: true
    mountPath: /config
