# yaml-language-server: $schema=./values.schema.json
image:
  repository: ghcr.io/homarr-labs/homarr
  tag: v1.59.3@sha256:4ffa0d4b24e390fd0050a18103ecfcb009357f6b3a25409fd4dd8cb0b9f3443e
  pullPolicy: IfNotPresent
workload:
  main:
    podSpec:
      containers:
        main:
          env:
            SECRET_ENCRYPTION_KEY: "changemeplease"
service:
  main:
    ports:
      main:
        port: 10245
        targetPort: 7575
persistence:
  appdata:
    enabled: true
    mountPath: "/appdata"
  varrun:
    enabled: false
securityContext:
  container:
    readOnlyRootFilesystem: false
    runAsNonRoot: false
    runAsUser: 0
    runAsGroup: 0
