# yaml-language-server: $schema=./values.schema.json
image:
  repository: ghcr.io/homarr-labs/homarr
  tag: v1.57.1@sha256:dc1573b84221d5678ff731848978c1ce3548d1cce3146156bc7421e3f302896a
  pullPolicy: IfNotPresent
workload:
  main:
    podSpec:
      containers:
        main:
          env:
            SECRET_ENCRYPTION_KEY: "changemeplease"
service:
  main:
    ports:
      main:
        port: 10245
        targetPort: 7575
persistence:
  appdata:
    enabled: true
    mountPath: "/appdata"
  varrun:
    enabled: false
securityContext:
  container:
    readOnlyRootFilesystem: false
    runAsNonRoot: false
    runAsUser: 0
    runAsGroup: 0
