# yaml-language-server: $schema=./values.schema.json
image:
  repository: ghcr.io/homarr-labs/homarr
  tag: v1.77.2@sha256:d60120a04536ded5d8c3a478192dca549c3f16cae2f809ab094f95f011bb74e6
  pullPolicy: IfNotPresent
workload:
  main:
    podSpec:
      containers:
        main:
          env:
            SECRET_ENCRYPTION_KEY: "changemeplease"
service:
  main:
    ports:
      main:
        port: 10245
        targetPort: 7575
persistence:
  appdata:
    enabled: true
    mountPath: "/appdata"
  varrun:
    enabled: false
securityContext:
  container:
    readOnlyRootFilesystem: false
    runAsNonRoot: false
    runAsUser: 0
    runAsGroup: 0
