# yaml-language-server: $schema=./values.schema.json
image:
  pullPolicy: IfNotPresent
  repository: docker.io/songkong/songkong
  tag: latest@sha256:553e8ef029866a0b3b933c28a02ef6b0f0ab8bf1abefeb0fb38ab24cca90b5bc
persistence:
  music:
    enabled: true
    mountPath: /music
  songkongconfig:
    enabled: true
    mountPath: /songkong

securityContext:
  container:
    readOnlyRootFilesystem: false
    runAsGroup: 0
    runAsUser: 0
service:
  main:
    ports:
      main:
        port: 4567
        protocol: tcp
        targetPort: 4567
