# yaml-language-server: $schema=./values.schema.json
image:
  pullPolicy: IfNotPresent
  repository: docker.io/songkong/songkong
  tag: latest@sha256:514747b47ed0aa33a04d7a4bfae5a142eb7d64594b429933379e763d8e44a6f1
persistence:
  music:
    enabled: true
    mountPath: /music
  songkongconfig:
    enabled: true
    mountPath: /songkong

securityContext:
  container:
    readOnlyRootFilesystem: false
    runAsGroup: 0
    runAsUser: 0
service:
  main:
    ports:
      main:
        port: 4567
        protocol: tcp
        targetPort: 4567
