# yaml-language-server: $schema=./values.schema.json
image:
  pullPolicy: IfNotPresent
  repository: docker.io/songkong/songkong
  tag: latest@sha256:65fc50caac18949696a12d35e09617cd2bf5880e8056db5f14c00f528cad6dd4
persistence:
  music:
    enabled: true
    mountPath: /music
  songkongconfig:
    enabled: true
    mountPath: /songkong

securityContext:
  container:
    readOnlyRootFilesystem: false
    runAsGroup: 0
    runAsUser: 0
service:
  main:
    ports:
      main:
        port: 4567
        protocol: tcp
        targetPort: 4567
