# yaml-language-server: $schema=./values.schema.json
image:
  repository: docker.io/zwavejs/zwave-js-ui
  pullPolicy: IfNotPresent
  tag: 11.21.1@sha256:1193b96b31488e5a6c7895f16a27b2ead38f8a0c3d1bec335bb10b6d9f9e2905
service:
  main:
    ports:
      main:
        port: 8091
        targetPort: 8091
  ws:
    enabled: true
    ports:
      ws:
        enabled: true
        port: 10046
        targetPort: 3000
persistence:
  config:
    enabled: true
    mountPath: "/usr/src/app/store"
securityContext:
  container:
    readOnlyRootFilesystem: false
workload:
  main:
    podSpec:
      containers:
        main:
          probes:
            liveness:
              enabled: true
              # custom: true
              # spec:
              #   failureThreshold: 5
              #   httpGet:
              #     path: /health
              #     port: http
              #     httpHeaders:
              #       - name: Accept
              #         value: text/plain
              #   initialDelaySeconds: 30
              #   periodSeconds: 10
              #   timeoutSeconds: 10
            readiness:
              enabled: true
              # custom: true
              # spec:
              #   failureThreshold: 5
              #   httpGet:
              #     path: /health
              #     port: http
              #     httpHeaders:
              #       - name: Accept
              #         value: text/plain
              #   initialDelaySeconds: 30
              #   periodSeconds: 10
              #   timeoutSeconds: 10
            startup:
              enabled: false
              # custom: true
              # spec:
              #   failureThreshold: 5
              #   httpGet:
              #     path: /health
              #     port: http
              #     httpHeaders:
              #       - name: Accept
              #         value: text/plain
              #   initialDelaySeconds: 30
              #   periodSeconds: 10
              #   timeoutSeconds: 10
