# yaml-language-server: $schema=./values.schema.json
image:
  repository: ghcr.io/pocket-id/pocket-id
  pullPolicy: IfNotPresent
  tag: v2.13.0@sha256:018fcf61697db2ce168394a63a169289f2b3943898069305e308a9678028a2e7

service:
  main:
    ports:
      main:
        port: 1411
        protocol: http
        targetPort: 1411

persistence:
  data:
    enabled: true
    mountPath: /app/data

workload:
  main:
    podSpec:
      containers:
        main:
          probes:
            liveness:
              path: /healthz
              type: http
            readiness:
              path: /healthz
              type: http
            startup:
              path: /healthz
              type: http
          env:
            APP_URL: "{{ .Values.chartContext.appUrl }}"
            TRUST_PROXY: "true"
            ANALYTICS_DISABLED: "true"
            VERSION_CHECK_DISABLED: "false"
            MAXMIND_LICENSE_KEY: ""
            ENCRYPTION_KEY: changeme_changeme!!
            DB_CONNECTION_STRING: file:data/pocket-id.db
