# yaml-language-server: $schema=./values.schema.json
image:
  repository: docker.io/storjlabs/storagenode
  tag: latest@sha256:c7ac8eaae9f072f0f32b77d1437968191ed277b7095d33211a72e1ca598f04bb
  pullPolicy: IfNotPresent
service:
  main:
    ports:
      main:
        port: 14002
        targetPort: 14002
  coretcp:
    enabled: true
    ports:
      coretcp:
        enabled: true
        protocol: tcp
        port: 28967
        targetPort: 28967
  coreudp:
    enabled: true
    ports:
      coreudp:
        enabled: true
        protocol: udp
        port: 28967
        targetPort: 28967
persistence:
  identity:
    enabled: true
    mountPath: "/app/identity"
  storage:
    enabled: true
    mountPath: "/app/config"

securityContext:
  container:
    runAsNonRoot: false
    readOnlyRootFilesystem: false
    runAsUser: 0
    runAsGroup: 0
workload:
  main:
    podSpec:
      containers:
        main:
          env:
            SETUP: true
            EMAIL: ""
            ADDRESS: ""
            STORAGE: "500GB"
            WALLET: "walletaddress"
