# yaml-language-server: $schema=./values.schema.json
image:
  repository: docker.io/maintainerr/maintainerr
  pullPolicy: IfNotPresent
  tag: 3.17.1@sha256:95e429451ea45380430d260450ab301eed9ce91fbcba5f94cf8507bd0bac0d08

securityContext:
  container:
    readOnlyRootFilesystem: false
    runAsUser: 0
    runAsGroup: 0

service:
  main:
    ports:
      main:
        protocol: http
        targetPort: 6246
        port: 6246

persistence:
  data:
    enabled: true
    mountPath: "/opt/data"
