# yaml-language-server: $schema=./values.schema.json
image:
  repository: docker.io/maintainerr/maintainerr
  pullPolicy: IfNotPresent
  tag: 3.26.0@sha256:0ff47e2465704ceb90cd79a1516844bc1c74f6c8eef8317988618a01e5a680ea

securityContext:
  container:
    readOnlyRootFilesystem: false
    runAsUser: 0
    runAsGroup: 0

service:
  main:
    ports:
      main:
        protocol: http
        targetPort: 6246
        port: 6246

persistence:
  data:
    enabled: true
    mountPath: "/opt/data"
