# yaml-language-server: $schema=./values.schema.json
image:
  repository: docker.io/maintainerr/maintainerr
  pullPolicy: IfNotPresent
  tag: 3.15.1@sha256:fc23686db8c34f6383f0c4e900f1db64d5c73a8191f8554dc983e2e3fe91a7d5

securityContext:
  container:
    readOnlyRootFilesystem: false
    runAsUser: 0
    runAsGroup: 0

service:
  main:
    ports:
      main:
        protocol: http
        targetPort: 6246
        port: 6246

persistence:
  data:
    enabled: true
    mountPath: "/opt/data"
