# yaml-language-server: $schema=./values.schema.json
image:
  repository: ghcr.io/tphakala/birdnet-go
  tag: 20261010@sha256:d412e7cc07cd77e7a1ef9d91fbffad1428106277a745c5accd90904a7cfb8b73
  pullPolicy: IfNotPresent
service:
  main:
    ports:
      main:
        port: 8080
        targetPort: 8080
persistence:
  config:
    enabled: true
    mountPath: /config
  data:
    enabled: true
    mountPath: /data
