# yaml-language-server: $schema=./values.schema.json
image:
  repository: docker.io/bizmodeller/mymediaforalexa
  pullPolicy: IfNotPresent
  tag: 1.3.153.4@sha256:46c083ba7e59f2e235745aa20cf3c19c7dad5cac569c0dc942c7876558facded
service:
  main:
    ports:
      main:
        targetPort: 52051
        port: 52051
  sub:
    enabled: true
    ports:
      sub:
        enabled: true
        targetPort: 52050
        port: 52050
persistence:
  data:
    enabled: true
    mountPath: "/datadir"
  media:
    enabled: true
    mountPath: "/medialibrary"

securityContext:
  container:
    readOnlyRootFilesystem: false
    runAsNonRoot: false
    runAsUser: 0
    runAsGroup: 0
