# yaml-language-server: $schema=./values.schema.json
image:
  repository: docker.io/bizmodeller/mymediaforalexa
  pullPolicy: IfNotPresent
  tag: 1.3.154.2@sha256:a6d5db21beefc8eb7d0743a1509b930dba738f5c55b7298e234d5cb3805d07ed
service:
  main:
    ports:
      main:
        targetPort: 52051
        port: 52051
  sub:
    enabled: true
    ports:
      sub:
        enabled: true
        targetPort: 52050
        port: 52050
persistence:
  data:
    enabled: true
    mountPath: "/datadir"
  media:
    enabled: true
    mountPath: "/medialibrary"

securityContext:
  container:
    readOnlyRootFilesystem: false
    runAsNonRoot: false
    runAsUser: 0
    runAsGroup: 0
