# yaml-language-server: $schema=./values.schema.json
image:
  pullPolicy: IfNotPresent
  repository: docker.io/sonatype/nexus3
  tag: 3.94.0@sha256:6e8905c14210c595a8177910179ce080cdc22fa3f6b660a13e6dfa1f8378a866
persistence:
  data:
    enabled: true
    mountPath: /nexus-data

securityContext:
  container:
    runAsGroup: 200
    runAsUser: 200
  pod:
    fsGroup: 200
service:
  main:
    ports:
      main:
        port: 10288
        targetPort: 8081
workload:
  main:
    podSpec:
      containers:
        main:
          env:
            INSTALL4J_ADD_VM_PARAMS:
              -Xms2703m -Xmx2703m -XX:MaxDirectMemorySize=2703m
              -Djava.util.prefs.userRoot=${NEXUS_DATA}/javaprefs
