# yaml-language-server: $schema=./values.schema.json
image:
  pullPolicy: IfNotPresent
  repository: docker.io/sonatype/nexus3
  tag: 3.96.4@sha256:5f48f9085096e96f4111ec07d79d57ca5a4a1da5a2003a3028a0b60c62bea7d1
persistence:
  data:
    enabled: true
    mountPath: /nexus-data

securityContext:
  container:
    runAsGroup: 200
    runAsUser: 200
  pod:
    fsGroup: 200
service:
  main:
    ports:
      main:
        port: 10288
        targetPort: 8081
workload:
  main:
    podSpec:
      containers:
        main:
          env:
            INSTALL4J_ADD_VM_PARAMS:
              -Xms2703m -Xmx2703m -XX:MaxDirectMemorySize=2703m
              -Djava.util.prefs.userRoot=${NEXUS_DATA}/javaprefs
