# yaml-language-server: $schema=./values.schema.json
image:
  pullPolicy: IfNotPresent
  repository: docker.io/sonatype/nexus3
  tag: 3.93.0@sha256:65b9b1e418e5a068b0c4c958b91a4cea692b35901554398171b1f22808b24098
persistence:
  data:
    enabled: true
    mountPath: /nexus-data

securityContext:
  container:
    runAsGroup: 200
    runAsUser: 200
  pod:
    fsGroup: 200
service:
  main:
    ports:
      main:
        port: 10288
        targetPort: 8081
workload:
  main:
    podSpec:
      containers:
        main:
          env:
            INSTALL4J_ADD_VM_PARAMS:
              -Xms2703m -Xmx2703m -XX:MaxDirectMemorySize=2703m
              -Djava.util.prefs.userRoot=${NEXUS_DATA}/javaprefs
