# yaml-language-server: $schema=./values.schema.json
image:
  repository: ghcr.io/linuxserver/oscam
  pullPolicy: IfNotPresent
  tag: 11965-ls20@sha256:29048a3baf892d4bebdc6d73294c172414c62c5ab4c0783a7655b98ca3a899d8
service:
  main:
    ports:
      main:
        port: 10062
        targetPort: 8888
persistence:
  config:
    enabled: true
    mountPath: "/config"
  varrun:
    enabled: true

securityContext:
  container:
    readOnlyRootFilesystem: false
    runAsNonRoot: false
    runAsUser: 0
    runAsGroup: 20
