# yaml-language-server: $schema=./values.schema.json
image:
  repository: ghcr.io/linuxserver/oscam
  pullPolicy: IfNotPresent
  tag: 11968-ls25@sha256:1eca583d97ac9be7a40baf4c35a13718a71bd43fe1f462915c5067950f46365a
service:
  main:
    ports:
      main:
        port: 10062
        targetPort: 8888
persistence:
  config:
    enabled: true
    mountPath: "/config"
  varrun:
    enabled: true

securityContext:
  container:
    readOnlyRootFilesystem: false
    runAsNonRoot: false
    runAsUser: 0
    runAsGroup: 20
