# yaml-language-server: $schema=./values.schema.json
image:
  repository: docker.io/nodered/node-red
  pullPolicy: IfNotPresent
  tag: 5.0.8@sha256:14a10a45799133122d7ec2e38e01e53c88dda5ba2867000f4d08cc6d1bcd0a10
service:
  main:
    ports:
      main:
        port: 1880
        targetPort: 1880
persistence:
  data:
    enabled: true
    mountPath: "/data"

workload:
  main:
    podSpec:
      containers:
        main:
          env: {}
