# yaml-language-server: $schema=./values.schema.json
image:
  repository: docker.io/nodered/node-red
  pullPolicy: IfNotPresent
  tag: 5.0.2@sha256:c1956020594e674c3c0dd43172b43dd39f9aa743928eb0d076de234cf5d00467
service:
  main:
    ports:
      main:
        port: 1880
        targetPort: 1880
persistence:
  data:
    enabled: true
    mountPath: "/data"

workload:
  main:
    podSpec:
      containers:
        main:
          env: {}
