# yaml-language-server: $schema=./values.schema.json
image:
  repository: docker.io/nodered/node-red
  pullPolicy: IfNotPresent
  tag: 5.0.1@sha256:6cb1b27fa5a83deec6a662db62eec8bb32e55ac5412d6b7a653e874ce62055d5
service:
  main:
    ports:
      main:
        port: 1880
        targetPort: 1880
persistence:
  data:
    enabled: true
    mountPath: "/data"

workload:
  main:
    podSpec:
      containers:
        main:
          env: {}
