# yaml-language-server: $schema=./values.schema.json
image:
  repository: docker.io/wiserain/flexget
  pullPolicy: IfNotPresent
  tag: 3.20.10@sha256:5dcf4d5bd40c5ab37c5e1c33566588ba8b79a47b8b7688476ad0a6f13f608a69
securityContext:
  container:
    runAsNonRoot: false
    readOnlyRootFilesystem: false
    runAsUser: 0
    runAsGroup: 0
workload:
  main:
    podSpec:
      containers:
        main:
          probes:
            liveness:
              type: http
              path: /
            readiness:
              type: http
              path: /
            startup:
              type: http
              path: /
          env:
            FG_LOG_LEVEL: info
            FG_LOG_FILE: flexget.log
            FG_WEBUI_PASSWD: "jLeT78KBDPW"
service:
  main:
    ports:
      main:
        port: 10174
        targetPort: 5050
persistence:
  config:
    enabled: true
    mountPath: /config
  data:
    enabled: true
    mountPath: /data
