# yaml-language-server: $schema=./values.schema.json
image:
  repository: docker.io/wiserain/flexget
  pullPolicy: IfNotPresent
  tag: 3.19.14@sha256:7d78d1f4a337d99cbcc84ee61eaea6afd9d9719c8c36f5dc29e65446d946a9c1
securityContext:
  container:
    runAsNonRoot: false
    readOnlyRootFilesystem: false
    runAsUser: 0
    runAsGroup: 0
workload:
  main:
    podSpec:
      containers:
        main:
          probes:
            liveness:
              type: http
              path: /
            readiness:
              type: http
              path: /
            startup:
              type: http
              path: /
          env:
            FG_LOG_LEVEL: info
            FG_LOG_FILE: flexget.log
            FG_WEBUI_PASSWD: "jLeT78KBDPW"
service:
  main:
    ports:
      main:
        port: 10174
        targetPort: 5050
persistence:
  config:
    enabled: true
    mountPath: /config
  data:
    enabled: true
    mountPath: /data
