# yaml-language-server: $schema=./values.schema.json
image:
  repository: docker.io/aeonlucid/impostor
  tag: nightly@sha256:63d1187e3057b7dd66bf5c9bab34b73fcb051f0323b0282958dc9f0b9e7b1fed
  pullPolicy: IfNotPresent
