# yaml-language-server: $schema=./values.schema.json
image:
  repository: docker.io/aeonlucid/impostor
  tag: nightly@sha256:c3118149f1fdd6a40a3db501f9447adc719feaa6e8927e7a3dc12bedecd124f5
  pullPolicy: IfNotPresent
