# yaml-language-server: $schema=./values.schema.json
image:
  repository: docker.io/aeonlucid/impostor
  tag: nightly@sha256:1578f3e323b735ee3f4b12aa7a478d46e8775843b3530fe461b9bdf0bcf92dbe
  pullPolicy: IfNotPresent
