# yaml-language-server: $schema=./values.schema.json
image:
  pullPolicy: IfNotPresent
  repository: atdr.meo.ws/archiveteam/warrior-dockerfile
  tag: latest@sha256:ee40f3bd1be65864d7cce01b3d371362e92f4a8a9d870dbed6ab90cb1948e708

securityContext:
  container:
    readOnlyRootFilesystem: false
    runAsGroup: 0
    runAsUser: 0
service:
  main:
    ports:
      main:
        port: 8001
        protocol: tcp
        targetPort: 8001
