# yaml-language-server: $schema=./values.schema.json
image:
  pullPolicy: IfNotPresent
  repository: atdr.meo.ws/archiveteam/warrior-dockerfile
  tag: latest@sha256:c50a2daa364a876fe07dc402679d856525f393598a2792401c39a3321c3e9663

securityContext:
  container:
    readOnlyRootFilesystem: false
    runAsGroup: 0
    runAsUser: 0
service:
  main:
    ports:
      main:
        port: 8001
        protocol: tcp
        targetPort: 8001
