# yaml-language-server: $schema=./values.schema.json
image:
  repository: oci.trueforge.org/containerforge/flood
  pullPolicy: IfNotPresent
  tag: "4.13.9@sha256:dbbabec93ae6f97eb9dd57a6e40657ef22e5599936ff07f4c06a0b68fb07bb46"
workload:
  main:
    podSpec:
      containers:
        main:
          env:
            FLOOD_OPTION_RUNDIR: /data
service:
  main:
    ports:
      main:
        port: 10036
        targetPort: 3000
persistence:
  data:
    enabled: true
    mountPath: /data
  config:
    enabled: true
    mountPath: /config
