# yaml-language-server: $schema=./values.schema.json
image:
  repository: oci.trueforge.org/containerforge/flood
  pullPolicy: IfNotPresent
  tag: "4.15.0@sha256:085bde86f415c43e803e093cd97aa748576bbb6fe77f50aa28002270a389669d"
workload:
  main:
    podSpec:
      containers:
        main:
          env:
            FLOOD_OPTION_RUNDIR: /data
service:
  main:
    ports:
      main:
        port: 10036
        targetPort: 3000
persistence:
  data:
    enabled: true
    mountPath: /data
  config:
    enabled: true
    mountPath: /config
