# yaml-language-server: $schema=./values.schema.json
image:
  repository: oci.trueforge.org/containerforge/flood
  pullPolicy: IfNotPresent
  tag: "4.12.6@sha256:c11e80d2e473e77dc790a06a5185941ad0f01f0e5e93b2bcbf7252559773931f"
workload:
  main:
    podSpec:
      containers:
        main:
          env:
            FLOOD_OPTION_RUNDIR: /data
service:
  main:
    ports:
      main:
        port: 10036
        targetPort: 3000
persistence:
  data:
    enabled: true
    mountPath: /data
