# yaml-language-server: $schema=./values.schema.json
image:
  pullPolicy: IfNotPresent
  repository: docker.io/accetto/ubuntu-vnc-xfce-firefox-g3
  tag: latest@sha256:38563afb7587f574079e6d48b096a0899670eb6a6738dadf8e0e81b562ddd983
persistence:
  internalshare:
    enabled: true
    mountPath: /UNRAID_SHARE

securityContext:
  container:
    readOnlyRootFilesystem: false
    runAsGroup: 0
    runAsUser: 0
service:
  main:
    ports:
      main:
        port: 6901
        protocol: http
        targetPort: 6901
  webuivnc:
    enabled: true
    ports:
      webuivnc:
        enabled: true
        port: 5901
        protocol: tcp
        targetPort: 5901
workload:
  main:
    podSpec:
      containers:
        main:
          env:
            VNC_PW: unraid
            VNC_RESOLUTION: 1360x768
