# yaml-language-server: $schema=./values.schema.json
image:
  repository: docker.io/jeessy/ddns-go
  pullPolicy: IfNotPresent
  tag: v6.17.6@sha256:036ceace323dbfe65c5033a3de688065689f0a1d296a54447b456c0a29985bf8
securityContext:
  container:
    readOnlyRootFilesystem: false
    runAsNonRoot: false
    runAsUser: 0
    runAsGroup: 0
service:
  main:
    ports:
      main:
        targetPort: 9876
        protocol: http
        port: 10168
workload:
  main:
    podSpec:
      containers:
        main:
          probes:
            liveness:
              type: http
              path: /
            readiness:
              type: http
              path: /
            startup:
              type: http
              path: /
          env: {}
persistence:
  data:
    enabled: true
    mountPath: /root
