# yaml-language-server: $schema=./values.schema.json
image:
  repository: docker.io/jeessy/ddns-go
  pullPolicy: IfNotPresent
  tag: v6.16.12@sha256:f674ac31eb5937a6bec300a0268640daec0d92aaf3e185e29f03081dad031cc0
securityContext:
  container:
    readOnlyRootFilesystem: false
    runAsNonRoot: false
    runAsUser: 0
    runAsGroup: 0
service:
  main:
    ports:
      main:
        targetPort: 9876
        protocol: http
        port: 10168
workload:
  main:
    podSpec:
      containers:
        main:
          probes:
            liveness:
              type: http
              path: /
            readiness:
              type: http
              path: /
            startup:
              type: http
              path: /
          env: {}
persistence:
  data:
    enabled: true
    mountPath: /root
