# yaml-language-server: $schema=./values.schema.json
image:
  repository: docker.io/jeessy/ddns-go
  pullPolicy: IfNotPresent
  tag: v6.17.5@sha256:2d5f159e7330bc1655b5be44f482616b9d2da400e58124dfc88ff9de7341b82e
securityContext:
  container:
    readOnlyRootFilesystem: false
    runAsNonRoot: false
    runAsUser: 0
    runAsGroup: 0
service:
  main:
    ports:
      main:
        targetPort: 9876
        protocol: http
        port: 10168
workload:
  main:
    podSpec:
      containers:
        main:
          probes:
            liveness:
              type: http
              path: /
            readiness:
              type: http
              path: /
            startup:
              type: http
              path: /
          env: {}
persistence:
  data:
    enabled: true
    mountPath: /root
