# yaml-language-server: $schema=./values.schema.json
image:
  repository: ghcr.io/sbondco/watcharr
  tag: v4.2.0@sha256:45770e117982580d2a9a760756ea5d447c1f65cfec69646c6509473ffb232072
  pullPolicy: IfNotPresent

securityContext:
  container:
    readOnlyRootFilesystem: false
    runAsNonRoot: false
    runAsUser: 0
    runAsGroup: 0

service:
  main:
    ports:
      main:
        protocol: http
        targetPort: 3080
        port: 10684

watcharr:
  mode: prod
  jellyfin_host: ""
  signup_enabled: true
  tmdb_key: ""
  debug: false

workload:
  main:
    podSpec:
      containers:
        main:
          env:
            JELLYFIN_HOST: "{{ .Values.watcharr.jellyfin_host }}"
            SIGNUP_ENABLED: "{{ .Values.watcharr.signup_enabled }}"
            TMDB_KEY: "{{ .Values.watcharr.tmdb_key }}"
            DEBUG: "{{ .Values.watcharr.debug }}"
            MODE: "{{ .Values.watcharr.mode }}"
            JWT_SECRET:
              secretKeyRef:
                name: watcharr-secrets
                key: JWT_SECRET

persistence:
  data:
    enabled: true
    mountPath: "/data"
