# yaml-language-server: $schema=./values.schema.json
image:
  repository: ghcr.io/linuxserver/grocy
  tag: 4.6.0@sha256:1efa34ad8fbfff8a7c146e00b5af0cbd768352dfbb23acca0bad35796190d7ff
  pullPolicy: IfNotPresent
service:
  main:
    ports:
      main:
        port: 10013
        targetPort: 80
persistence:
  config:
    enabled: true
    mountPath: "/config"

securityContext:
  container:
    readOnlyRootFilesystem: false
    runAsNonRoot: false
    runAsUser: 0
    runAsGroup: 0
