# yaml-language-server: $schema=./values.schema.json
image:
  repository: ghcr.io/linuxserver/grocy
  tag: 4.6.0@sha256:971fb0b4dac073652915c3c90e540a97d17075f40e2998d2850351c2dc9f1305
  pullPolicy: IfNotPresent
service:
  main:
    ports:
      main:
        port: 10013
        targetPort: 80
persistence:
  config:
    enabled: true
    mountPath: "/config"

securityContext:
  container:
    readOnlyRootFilesystem: false
    runAsNonRoot: false
    runAsUser: 0
    runAsGroup: 0
