# yaml-language-server: $schema=./values.schema.json
image:
  repository: ghcr.io/linuxserver/grocy
  tag: 4.6.0@sha256:e84bfdb1de28a664e6f7b38f78551bd17a3e3ade4fdb0b9f6da4b0fbb306a7a8
  pullPolicy: IfNotPresent
service:
  main:
    ports:
      main:
        port: 10013
        targetPort: 80
persistence:
  config:
    enabled: true
    mountPath: "/config"

securityContext:
  container:
    readOnlyRootFilesystem: false
    runAsNonRoot: false
    runAsUser: 0
    runAsGroup: 0
