# yaml-language-server: $schema=./values.schema.json
image:
  repository: oci.trueforge.org/containerforge/kavita
  pullPolicy: IfNotPresent
  tag: "0.8.8.3@sha256:2b5bf4faaa746e298638c4cf6198f458aa0278f8deacd5515a9a8f8ef1dbe822"
securityContext:
  container:
    readOnlyRootFilesystem: false
    runAsNonRoot: false
    runAsUser: 0
    runAsGroup: 0
service:
  main:
    ports:
      main:
        targetPort: 5000
        port: 10189
persistence:
  config:
    enabled: true
    mountPath: "/config"
  manga:
    enabled: true
    mountPath: "/manga"
  tmp:
    enabled: false
