# yaml-language-server: $schema=./values.schema.json
image:
  pullPolicy: IfNotPresent
  repository: lscr.io/linuxserver/rdesktop
  tag: ubuntu-kde@sha256:cfc2c81d1220ba52645cde6bd317e1a5777b10b96a70ab6215acc9d246b4a7b1
ubuntuXFCEImage:
  repository: lscr.io/linuxserver/rdesktop
  tag: ubuntu-xfce@sha256:f37437bf34de5cf6634b9ffaf1224589954a19abee95f6f0626080fc9473e799
  pullPolicy: Always
fedoraXFCEImage:
  repository: lscr.io/linuxserver/rdesktop
  tag: fedora-xfce@sha256:eb37f58646a901dc7727cf448cae36daaefaba79de33b5058dab79aa4c04aefb
  pullPolicy: Always
archXFCEImage:
  repository: lscr.io/linuxserver/rdesktop
  tag: arch-xfce@sha256:eb37f58646a901dc7727cf448cae36daaefaba79de33b5058dab79aa4c04aefb
  pullPolicy: Always
alpineKDEImage:
  repository: lscr.io/linuxserver/rdesktop
  tag: alpine-kde@sha256:eb37f58646a901dc7727cf448cae36daaefaba79de33b5058dab79aa4c04aefb
  pullPolicy: Always
ubuntuKDEImage:
  repository: lscr.io/linuxserver/rdesktop
  tag: ubuntu-kde@sha256:cfc2c81d1220ba52645cde6bd317e1a5777b10b96a70ab6215acc9d246b4a7b1
  pullPolicy: Always
fedoraKDEImage:
  repository: lscr.io/linuxserver/rdesktop
  tag: fedora-kde@sha256:eb37f58646a901dc7727cf448cae36daaefaba79de33b5058dab79aa4c04aefb
  pullPolicy: Always
archKDEImage:
  repository: lscr.io/linuxserver/rdesktop
  tag: arch-kde@sha256:eb37f58646a901dc7727cf448cae36daaefaba79de33b5058dab79aa4c04aefb
  pullPolicy: Always
alpineMATEImage:
  repository: lscr.io/linuxserver/rdesktop
  tag: alpine-mate@sha256:eb37f58646a901dc7727cf448cae36daaefaba79de33b5058dab79aa4c04aefb
  pullPolicy: Always
ubuntuMATEImage:
  repository: lscr.io/linuxserver/rdesktop
  tag: ubuntu-mate@sha256:15700a4a0d4e71239532f536ded22ee5a0c01c8dd06b89e8824e6ed835d90b73
  pullPolicy: Always
fedoraMATEImage:
  repository: lscr.io/linuxserver/rdesktop
  tag: fedora-mate@sha256:eb37f58646a901dc7727cf448cae36daaefaba79de33b5058dab79aa4c04aefb
  pullPolicy: Always
archMATEImage:
  repository: lscr.io/linuxserver/rdesktop
  tag: arch-mate@sha256:eb37f58646a901dc7727cf448cae36daaefaba79de33b5058dab79aa4c04aefb
  pullPolicy: Always
alpineI3Image:
  repository: lscr.io/linuxserver/rdesktop
  tag: alpine-i3@sha256:eb37f58646a901dc7727cf448cae36daaefaba79de33b5058dab79aa4c04aefb
  pullPolicy: Always
ubuntuI3Image:
  repository: lscr.io/linuxserver/rdesktop
  tag: ubuntu-i3@sha256:2f43715f91d34541ec3958250ccafd2f1e7d3982317b25d88f46930f02de4699
  pullPolicy: Always
fedoraI3Image:
  repository: lscr.io/linuxserver/rdesktop
  tag: fedora-i3@sha256:eb37f58646a901dc7727cf448cae36daaefaba79de33b5058dab79aa4c04aefb
  pullPolicy: Always
archI3Image:
  repository: lscr.io/linuxserver/rdesktop
  tag: arch-i3@sha256:eb37f58646a901dc7727cf448cae36daaefaba79de33b5058dab79aa4c04aefb
  pullPolicy: Always
alpineOpenBoxImage:
  repository: lscr.io/linuxserver/rdesktop
  tag: alpine-openbox@sha256:eb37f58646a901dc7727cf448cae36daaefaba79de33b5058dab79aa4c04aefb
  pullPolicy: Always
ubuntuOpenBoxImage:
  repository: lscr.io/linuxserver/rdesktop
  tag: ubuntu-openbox@sha256:eac79c5839f5ff05fd5fb55cc0d3b2cba3f06f7a7c002304aed657303667ed1c
  pullPolicy: Always
fedoraOpenBoxImage:
  repository: lscr.io/linuxserver/rdesktop
  tag: fedora-openbox@sha256:eb37f58646a901dc7727cf448cae36daaefaba79de33b5058dab79aa4c04aefb
  pullPolicy: Always
archOpenBoxImage:
  repository: lscr.io/linuxserver/rdesktop
  tag: arch-openbox@sha256:eb37f58646a901dc7727cf448cae36daaefaba79de33b5058dab79aa4c04aefb
  pullPolicy: Always
alpineICEWMImage:
  repository: lscr.io/linuxserver/rdesktop
  tag: alpine-icewm@sha256:eb37f58646a901dc7727cf448cae36daaefaba79de33b5058dab79aa4c04aefb
  pullPolicy: Always
ubuntuICEWMImage:
  repository: lscr.io/linuxserver/rdesktop
  tag: ubuntu-icewm@sha256:91abc71f67eace6b490e81b2bfe0c1cd6a238e73c314a81f3e13c29d35f54083
  pullPolicy: Always
fedoraICEWMImage:
  repository: lscr.io/linuxserver/rdesktop
  tag: fedora-icewm@sha256:eb37f58646a901dc7727cf448cae36daaefaba79de33b5058dab79aa4c04aefb
  pullPolicy: Always
archICEWMImage:
  repository: lscr.io/linuxserver/rdesktop
  tag: arch-icewm@sha256:eb37f58646a901dc7727cf448cae36daaefaba79de33b5058dab79aa4c04aefb
  pullPolicy: Always
workload:
  main:
    podSpec:
      containers:
        main:
          imageSelector: image
service:
  main:
    ports:
      main:
        port: 3389
        protocol: tcp
        targetPort: 3389
persistence:
  config:
    enabled: true
    mountPath: /config

securityContext:
  container:
    readOnlyRootFilesystem: false
    runAsNonRoot: false
    runAsGroup: 0
    runAsUser: 0
updated: true
