# yaml-language-server: $schema=./values.schema.json
image:
  pullPolicy: IfNotPresent
  repository: lscr.io/linuxserver/rdesktop
  tag: ubuntu-kde@sha256:c965359b000dd146a301afd09574e4e68d4d21e0de01e078c8b0c0d86fe8095d
ubuntuXFCEImage:
  repository: lscr.io/linuxserver/rdesktop
  tag: ubuntu-xfce@sha256:4a8c6d0df1931dafb87df7506378a9ee3d6554cb255f9ee496353ac4195bd1ab
  pullPolicy: Always
fedoraXFCEImage:
  repository: lscr.io/linuxserver/rdesktop
  tag: fedora-xfce@sha256:eb37f58646a901dc7727cf448cae36daaefaba79de33b5058dab79aa4c04aefb
  pullPolicy: Always
archXFCEImage:
  repository: lscr.io/linuxserver/rdesktop
  tag: arch-xfce@sha256:eb37f58646a901dc7727cf448cae36daaefaba79de33b5058dab79aa4c04aefb
  pullPolicy: Always
alpineKDEImage:
  repository: lscr.io/linuxserver/rdesktop
  tag: alpine-kde@sha256:eb37f58646a901dc7727cf448cae36daaefaba79de33b5058dab79aa4c04aefb
  pullPolicy: Always
ubuntuKDEImage:
  repository: lscr.io/linuxserver/rdesktop
  tag: ubuntu-kde@sha256:c965359b000dd146a301afd09574e4e68d4d21e0de01e078c8b0c0d86fe8095d
  pullPolicy: Always
fedoraKDEImage:
  repository: lscr.io/linuxserver/rdesktop
  tag: fedora-kde@sha256:eb37f58646a901dc7727cf448cae36daaefaba79de33b5058dab79aa4c04aefb
  pullPolicy: Always
archKDEImage:
  repository: lscr.io/linuxserver/rdesktop
  tag: arch-kde@sha256:eb37f58646a901dc7727cf448cae36daaefaba79de33b5058dab79aa4c04aefb
  pullPolicy: Always
alpineMATEImage:
  repository: lscr.io/linuxserver/rdesktop
  tag: alpine-mate@sha256:eb37f58646a901dc7727cf448cae36daaefaba79de33b5058dab79aa4c04aefb
  pullPolicy: Always
ubuntuMATEImage:
  repository: lscr.io/linuxserver/rdesktop
  tag: ubuntu-mate@sha256:89a7527233c7d6a26c639c6e5933fe3e0ee5516dd67059a5c80d88b1683a5a76
  pullPolicy: Always
fedoraMATEImage:
  repository: lscr.io/linuxserver/rdesktop
  tag: fedora-mate@sha256:eb37f58646a901dc7727cf448cae36daaefaba79de33b5058dab79aa4c04aefb
  pullPolicy: Always
archMATEImage:
  repository: lscr.io/linuxserver/rdesktop
  tag: arch-mate@sha256:eb37f58646a901dc7727cf448cae36daaefaba79de33b5058dab79aa4c04aefb
  pullPolicy: Always
alpineI3Image:
  repository: lscr.io/linuxserver/rdesktop
  tag: alpine-i3@sha256:eb37f58646a901dc7727cf448cae36daaefaba79de33b5058dab79aa4c04aefb
  pullPolicy: Always
ubuntuI3Image:
  repository: lscr.io/linuxserver/rdesktop
  tag: ubuntu-i3@sha256:131847ec90a9aa3af048693de19a0b3e6b4a0a7ad8888e5db962a8e78a8f7aba
  pullPolicy: Always
fedoraI3Image:
  repository: lscr.io/linuxserver/rdesktop
  tag: fedora-i3@sha256:eb37f58646a901dc7727cf448cae36daaefaba79de33b5058dab79aa4c04aefb
  pullPolicy: Always
archI3Image:
  repository: lscr.io/linuxserver/rdesktop
  tag: arch-i3@sha256:eb37f58646a901dc7727cf448cae36daaefaba79de33b5058dab79aa4c04aefb
  pullPolicy: Always
alpineOpenBoxImage:
  repository: lscr.io/linuxserver/rdesktop
  tag: alpine-openbox@sha256:eb37f58646a901dc7727cf448cae36daaefaba79de33b5058dab79aa4c04aefb
  pullPolicy: Always
ubuntuOpenBoxImage:
  repository: lscr.io/linuxserver/rdesktop
  tag: ubuntu-openbox@sha256:e2038fdfd01a228eb6c1aad3f2da7739915a7b44b4da4a03becb13cd61596173
  pullPolicy: Always
fedoraOpenBoxImage:
  repository: lscr.io/linuxserver/rdesktop
  tag: fedora-openbox@sha256:eb37f58646a901dc7727cf448cae36daaefaba79de33b5058dab79aa4c04aefb
  pullPolicy: Always
archOpenBoxImage:
  repository: lscr.io/linuxserver/rdesktop
  tag: arch-openbox@sha256:eb37f58646a901dc7727cf448cae36daaefaba79de33b5058dab79aa4c04aefb
  pullPolicy: Always
alpineICEWMImage:
  repository: lscr.io/linuxserver/rdesktop
  tag: alpine-icewm@sha256:eb37f58646a901dc7727cf448cae36daaefaba79de33b5058dab79aa4c04aefb
  pullPolicy: Always
ubuntuICEWMImage:
  repository: lscr.io/linuxserver/rdesktop
  tag: ubuntu-icewm@sha256:0eeffbbf0fa4ed7f53b0643d2f836762ba53e9441c7606629bfb0af1b6f540ed
  pullPolicy: Always
fedoraICEWMImage:
  repository: lscr.io/linuxserver/rdesktop
  tag: fedora-icewm@sha256:eb37f58646a901dc7727cf448cae36daaefaba79de33b5058dab79aa4c04aefb
  pullPolicy: Always
archICEWMImage:
  repository: lscr.io/linuxserver/rdesktop
  tag: arch-icewm@sha256:eb37f58646a901dc7727cf448cae36daaefaba79de33b5058dab79aa4c04aefb
  pullPolicy: Always
workload:
  main:
    podSpec:
      containers:
        main:
          imageSelector: image
service:
  main:
    ports:
      main:
        port: 3389
        protocol: tcp
        targetPort: 3389
persistence:
  config:
    enabled: true
    mountPath: /config

securityContext:
  container:
    readOnlyRootFilesystem: false
    runAsNonRoot: false
    runAsGroup: 0
    runAsUser: 0
updated: true
