image:
  pullPolicy: IfNotPresent
  repository: lscr.io/linuxserver/rdesktop
  tag: latest@sha256:eb37f58646a901dc7727cf448cae36daaefaba79de33b5058dab79aa4c04aefb
ubuntuXFCEImage:
  repository: lscr.io/linuxserver/rdesktop
  tag: ubuntu-xfce@sha256:48c4e27bd0caeb3b368c026f273e6a1c7b9c248906acd9a0a4e626bdd2624366
  pullPolicy: Always
fedoraXFCEImage:
  repository: lscr.io/linuxserver/rdesktop
  tag: fedora-xfce@sha256:eb37f58646a901dc7727cf448cae36daaefaba79de33b5058dab79aa4c04aefb
  pullPolicy: Always
archXFCEImage:
  repository: lscr.io/linuxserver/rdesktop
  tag: arch-xfce@sha256:eb37f58646a901dc7727cf448cae36daaefaba79de33b5058dab79aa4c04aefb
  pullPolicy: Always
alpineKDEImage:
  repository: lscr.io/linuxserver/rdesktop
  tag: alpine-kde@sha256:eb37f58646a901dc7727cf448cae36daaefaba79de33b5058dab79aa4c04aefb
  pullPolicy: Always
ubuntuKDEImage:
  repository: lscr.io/linuxserver/rdesktop
  tag: ubuntu-kde@sha256:ee66faf50e2d6e46c22e3c41801359a5f06e2d7ebc170deb7c3ac74b321c80ee
  pullPolicy: Always
fedoraKDEImage:
  repository: lscr.io/linuxserver/rdesktop
  tag: fedora-kde@sha256:eb37f58646a901dc7727cf448cae36daaefaba79de33b5058dab79aa4c04aefb
  pullPolicy: Always
archKDEImage:
  repository: lscr.io/linuxserver/rdesktop
  tag: arch-kde@sha256:eb37f58646a901dc7727cf448cae36daaefaba79de33b5058dab79aa4c04aefb
  pullPolicy: Always
alpineMATEImage:
  repository: lscr.io/linuxserver/rdesktop
  tag: alpine-mate@sha256:eb37f58646a901dc7727cf448cae36daaefaba79de33b5058dab79aa4c04aefb
  pullPolicy: Always
ubuntuMATEImage:
  repository: lscr.io/linuxserver/rdesktop
  tag: ubuntu-mate@sha256:2c4ab5acedb39ebde7dc984b0f8064e3e934d5edff0eb6eeddca6fa479beb55c
  pullPolicy: Always
fedoraMATEImage:
  repository: lscr.io/linuxserver/rdesktop
  tag: fedora-mate@sha256:eb37f58646a901dc7727cf448cae36daaefaba79de33b5058dab79aa4c04aefb
  pullPolicy: Always
archMATEImage:
  repository: lscr.io/linuxserver/rdesktop
  tag: arch-mate@sha256:eb37f58646a901dc7727cf448cae36daaefaba79de33b5058dab79aa4c04aefb
  pullPolicy: Always
alpineI3Image:
  repository: lscr.io/linuxserver/rdesktop
  tag: alpine-i3@sha256:eb37f58646a901dc7727cf448cae36daaefaba79de33b5058dab79aa4c04aefb
  pullPolicy: Always
ubuntuI3Image:
  repository: lscr.io/linuxserver/rdesktop
  tag: ubuntu-i3@sha256:0bd418363b91eed00cce3cce8138b0fa31ab7fb050c367fbfd4e195d36954481
  pullPolicy: Always
fedoraI3Image:
  repository: lscr.io/linuxserver/rdesktop
  tag: fedora-i3@sha256:eb37f58646a901dc7727cf448cae36daaefaba79de33b5058dab79aa4c04aefb
  pullPolicy: Always
archI3Image:
  repository: lscr.io/linuxserver/rdesktop
  tag: arch-i3@sha256:eb37f58646a901dc7727cf448cae36daaefaba79de33b5058dab79aa4c04aefb
  pullPolicy: Always
alpineOpenBoxImage:
  repository: lscr.io/linuxserver/rdesktop
  tag: alpine-openbox@sha256:eb37f58646a901dc7727cf448cae36daaefaba79de33b5058dab79aa4c04aefb
  pullPolicy: Always
ubuntuOpenBoxImage:
  repository: lscr.io/linuxserver/rdesktop
  tag: ubuntu-openbox@sha256:0db429b5d7c3ec72ae0ecd7eb329a64a7d3ea5dcf84ad6d9feec6000ecfa9754
  pullPolicy: Always
fedoraOpenBoxImage:
  repository: lscr.io/linuxserver/rdesktop
  tag: fedora-openbox@sha256:eb37f58646a901dc7727cf448cae36daaefaba79de33b5058dab79aa4c04aefb
  pullPolicy: Always
archOpenBoxImage:
  repository: lscr.io/linuxserver/rdesktop
  tag: arch-openbox@sha256:eb37f58646a901dc7727cf448cae36daaefaba79de33b5058dab79aa4c04aefb
  pullPolicy: Always
alpineICEWMImage:
  repository: lscr.io/linuxserver/rdesktop
  tag: alpine-icewm@sha256:eb37f58646a901dc7727cf448cae36daaefaba79de33b5058dab79aa4c04aefb
  pullPolicy: Always
ubuntuICEWMImage:
  repository: lscr.io/linuxserver/rdesktop
  tag: ubuntu-icewm@sha256:27509cd148c84ac185506721be77d60bcaaaf6068a2efa64ca4528a3d39384f8
  pullPolicy: Always
fedoraICEWMImage:
  repository: lscr.io/linuxserver/rdesktop
  tag: fedora-icewm@sha256:eb37f58646a901dc7727cf448cae36daaefaba79de33b5058dab79aa4c04aefb
  pullPolicy: Always
archICEWMImage:
  repository: lscr.io/linuxserver/rdesktop
  tag: arch-icewm@sha256:eb37f58646a901dc7727cf448cae36daaefaba79de33b5058dab79aa4c04aefb
  pullPolicy: Always
workload:
  main:
    podSpec:
      containers:
        main:
          imageSelector: image
service:
  main:
    ports:
      main:
        port: 3389
        protocol: tcp
        targetPort: 3389
persistence:
  config:
    enabled: true
    mountPath: /config

securityContext:
  container:
    readOnlyRootFilesystem: false
    runAsNonRoot: false
    runAsGroup: 0
    runAsUser: 0
updated: true
