# yaml-language-server: $schema=./values.schema.json
image:
  repository: ghcr.io/stirling-tools/s-pdf
  pullPolicy: IfNotPresent
  tag: 2.14.1-ultra-lite@sha256:65c7f37796b8f3a0ee519f3f10228de0667d3df1a8aaa65f6d1a7fce212643d8
fatImage:
  repository: ghcr.io/stirling-tools/s-pdf
  pullPolicy: IfNotPresent
  tag: 2.14.1-fat@sha256:e09e109a19ff2538b11176932a724766d07ad11ba63b6c25e8e25e12f1cc5235
fullImage:
  repository: ghcr.io/stirling-tools/s-pdf
  pullPolicy: IfNotPresent
  tag: 2.14.1@sha256:986ae1d17bd41661351006526332a29a1ff7ca6799e69a51a8bb549c55941044
securityContext:
  container:
    runAsNonRoot: false
    readOnlyRootFilesystem: false
    runAsUser: 0
    runAsGroup: 0
service:
  main:
    ports:
      main:
        protocol: http
        targetPort: 8080
        port: 18080
workload:
  main:
    podSpec:
      containers:
        main:
          # checkout the difference between the images.
          # https://github.com/Stirling-Tools/Stirling-PDF/blob/main/Version-groups.md
          imageSelector: image
          env:
            # enable to add login support
            DOCKER_ENABLE_SECURITY: false
            # uncomment to set the intial auth
            # default auth below
            # SECURITY_INITIALLOGIN_USERNAME: admin
            # SECURITY_INITIALLOGIN_PASSWORD: stirling
            # Download Calibre onto Stirling-PDF to enable PDF to/from book and advanced HTML conversion
            INSTALL_BOOK_AND_ADVANCED_HTML_OPS: false
            LANGS: en_US
persistence:
  configs:
    enabled: true
    mountPath: "/configs"
  tessdata:
    enabled: true
    mountPath: "/usr/share/tessdata"
  custom-files:
    enabled: true
    mountPath: "/customFiles"
  logs:
    enabled: true
    mountPath: "/logs"
