# yaml-language-server: $schema=./values.schema.json
image:
  repository: ghcr.io/stirling-tools/s-pdf
  pullPolicy: IfNotPresent
  tag: 2.9.0-ultra-lite@sha256:114eb7f4193f428eb16ac26f412280330e37145832d274b1b9ad9feee1f45eda
fatImage:
  repository: ghcr.io/stirling-tools/s-pdf
  pullPolicy: IfNotPresent
  tag: 2.9.0-fat@sha256:82f88f27b700c7d3b79540d67e08fe79d5d4a9c6df7de6130593ecf6b600bca9
fullImage:
  repository: ghcr.io/stirling-tools/s-pdf
  pullPolicy: IfNotPresent
  tag: 2.9.0@sha256:aac75dc5bc941049b937999808227e6a016d01cda7bf891eb711d161812a8f99
securityContext:
  container:
    runAsNonRoot: false
    readOnlyRootFilesystem: false
    runAsUser: 0
    runAsGroup: 0
service:
  main:
    ports:
      main:
        protocol: http
        targetPort: 8080
        port: 18080
workload:
  main:
    podSpec:
      containers:
        main:
          # checkout the difference between the images.
          # https://github.com/Stirling-Tools/Stirling-PDF/blob/main/Version-groups.md
          imageSelector: image
          env:
            # enable to add login support
            DOCKER_ENABLE_SECURITY: false
            # uncomment to set the intial auth
            # default auth below
            # SECURITY_INITIALLOGIN_USERNAME: admin
            # SECURITY_INITIALLOGIN_PASSWORD: stirling
            # Download Calibre onto Stirling-PDF to enable PDF to/from book and advanced HTML conversion
            INSTALL_BOOK_AND_ADVANCED_HTML_OPS: false
            LANGS: en_US
persistence:
  configs:
    enabled: true
    mountPath: "/configs"
  tessdata:
    enabled: true
    mountPath: "/usr/share/tessdata"
  custom-files:
    enabled: true
    mountPath: "/customFiles"
  logs:
    enabled: true
    mountPath: "/logs"
