# yaml-language-server: $schema=./values.schema.json
image:
  repository: ghcr.io/stirling-tools/s-pdf
  pullPolicy: IfNotPresent
  tag: 2.13.0-ultra-lite@sha256:0efb7551527eba62e807800f8b33fb1849d2196db96386f08126956e29d1ae6d
fatImage:
  repository: ghcr.io/stirling-tools/s-pdf
  pullPolicy: IfNotPresent
  tag: 2.13.0-fat@sha256:c2face7b30f29ba751b22736d58d77685260dc2f8afe47484e95b2ec5a9de2d1
fullImage:
  repository: ghcr.io/stirling-tools/s-pdf
  pullPolicy: IfNotPresent
  tag: 2.13.0@sha256:dc2d06bc68bb5a023d3635060ba0070381446bff02011143c7e46ea0c184755c
securityContext:
  container:
    runAsNonRoot: false
    readOnlyRootFilesystem: false
    runAsUser: 0
    runAsGroup: 0
service:
  main:
    ports:
      main:
        protocol: http
        targetPort: 8080
        port: 18080
workload:
  main:
    podSpec:
      containers:
        main:
          # checkout the difference between the images.
          # https://github.com/Stirling-Tools/Stirling-PDF/blob/main/Version-groups.md
          imageSelector: image
          env:
            # enable to add login support
            DOCKER_ENABLE_SECURITY: false
            # uncomment to set the intial auth
            # default auth below
            # SECURITY_INITIALLOGIN_USERNAME: admin
            # SECURITY_INITIALLOGIN_PASSWORD: stirling
            # Download Calibre onto Stirling-PDF to enable PDF to/from book and advanced HTML conversion
            INSTALL_BOOK_AND_ADVANCED_HTML_OPS: false
            LANGS: en_US
persistence:
  configs:
    enabled: true
    mountPath: "/configs"
  tessdata:
    enabled: true
    mountPath: "/usr/share/tessdata"
  custom-files:
    enabled: true
    mountPath: "/customFiles"
  logs:
    enabled: true
    mountPath: "/logs"
