# yaml-language-server: $schema=./values.schema.json
image:
  repository: ghcr.io/linuxserver/ddclient
  pullPolicy: IfNotPresent
  tag: 4.0.0@sha256:783d5339c5404a1190c3886f3b0c1975254c973ab7d9403f818d2ebcf3c49ffe
securityContext:
  container:
    runAsNonRoot: false
    readOnlyRootFilesystem: false
    runAsUser: 0
    runAsGroup: 0
service:
  main:
    enabled: false
    ports:
      main:
        enabled: false
workload:
  main:
    podSpec:
      containers:
        main:
          probes:
            liveness:
              enabled: false
            readiness:
              enabled: false
            startup:
              enabled: false
          env: {}
persistence:
  config:
    enabled: true
    mountPath: /config
