# yaml-language-server: $schema=./values.schema.json
image:
  repository: ghcr.io/linuxserver/ddclient
  pullPolicy: IfNotPresent
  tag: 4.0.0@sha256:5bf3fdd6ac7df67ae271a467a4669f0e30aad68e5c279978dea7a1142f60a6e6
securityContext:
  container:
    runAsNonRoot: false
    readOnlyRootFilesystem: false
    runAsUser: 0
    runAsGroup: 0
service:
  main:
    enabled: false
    ports:
      main:
        enabled: false
workload:
  main:
    podSpec:
      containers:
        main:
          probes:
            liveness:
              enabled: false
            readiness:
              enabled: false
            startup:
              enabled: false
          env: {}
persistence:
  config:
    enabled: true
    mountPath: /config
