# yaml-language-server: $schema=./values.schema.json
image:
  repository: ghcr.io/linuxserver/ddclient
  pullPolicy: IfNotPresent
  tag: 4.0.0@sha256:6509ac9ca19bb9bac9a1647d9e54fc27b36766f8c2b3ff0da7053103621fe33e
securityContext:
  container:
    runAsNonRoot: false
    readOnlyRootFilesystem: false
    runAsUser: 0
    runAsGroup: 0
service:
  main:
    enabled: false
    ports:
      main:
        enabled: false
workload:
  main:
    podSpec:
      containers:
        main:
          probes:
            liveness:
              enabled: false
            readiness:
              enabled: false
            startup:
              enabled: false
          env: {}
persistence:
  config:
    enabled: true
    mountPath: /config
