# yaml-language-server: $schema=./values.schema.json
image:
  repository: docker.io/jgraph/drawio
  tag: 29.6.4@sha256:ddfab7f2504bf7095d5a02f2e3c91aac5d0380ade0681cc4cae9bbdba82751ec
  pullPolicy: IfNotPresent
securityContext:
  container:
    readOnlyRootFilesystem: false
    runAsNonRoot: false
    runAsUser: 0
    runAsGroup: 0
service:
  main:
    ports:
      main:
        port: 10214
        targetPort: 8080
workload:
  main:
    podSpec:
      containers:
        main:
          probes:
            liveness:
              type: http
              path: /
            readiness:
              type: http
              path: /
            startup:
              type: http
              path: /
          env: {}
