# yaml-language-server: $schema=./values.schema.json
image:
  repository: docker.io/jgraph/drawio
  tag: 29.7.9@sha256:eb95727a8a7bb7e65008b0cbd5d526e5eb775fe464a7424139bf40bb1eb38025
  pullPolicy: IfNotPresent
securityContext:
  container:
    readOnlyRootFilesystem: false
    runAsNonRoot: false
    runAsUser: 0
    runAsGroup: 0
service:
  main:
    ports:
      main:
        port: 10214
        targetPort: 8080
workload:
  main:
    podSpec:
      containers:
        main:
          probes:
            liveness:
              type: http
              path: /
            readiness:
              type: http
              path: /
            startup:
              type: http
              path: /
          env: {}
