# yaml-language-server: $schema=./values.schema.json
image:
  repository: docker.io/jgraph/drawio
  tag: 30.3.8@sha256:29058caaaaae24574c2c08cd12c1db9fbfc31884c297770737384d4a11f679e6
  pullPolicy: IfNotPresent
securityContext:
  container:
    readOnlyRootFilesystem: false
    runAsNonRoot: false
    runAsUser: 0
    runAsGroup: 0
service:
  main:
    ports:
      main:
        port: 10214
        targetPort: 8080
workload:
  main:
    podSpec:
      containers:
        main:
          probes:
            liveness:
              type: http
              path: /
            readiness:
              type: http
              path: /
            startup:
              type: http
              path: /
          env: {}
