# yaml-language-server: $schema=./values.schema.json
image:
  pullPolicy: IfNotPresent
  repository: docker.io/farmos/farmos
  tag: latest@sha256:8bcce70fe19bd351bdb6372174998de80527345d8df8bfec788871ab8134b1ee
persistence:
  sitesdirectory:
    enabled: true
    mountPath: /var/www/html/sites

securityContext:
  container:
    readOnlyRootFilesystem: false
    runAsGroup: 0
    runAsUser: 0
service:
  main:
    ports:
      main:
        port: 80
        protocol: tcp
        targetPort: 80
