# yaml-language-server: $schema=./values.schema.json
image:
  pullPolicy: IfNotPresent
  repository: docker.io/farmos/farmos
  tag: latest@sha256:ee5cdf150a7b5bf49020615c6b45e4c1a99758650fa9f6ff052b74e274ace98a
persistence:
  sitesdirectory:
    enabled: true
    mountPath: /var/www/html/sites

securityContext:
  container:
    readOnlyRootFilesystem: false
    runAsGroup: 0
    runAsUser: 0
service:
  main:
    ports:
      main:
        port: 80
        protocol: tcp
        targetPort: 80
