# yaml-language-server: $schema=./values.schema.json
image:
  pullPolicy: IfNotPresent
  repository: docker.io/farmos/farmos
  tag: latest@sha256:2c71465c859523de8f8a411ab9ad11883225bef3ef569c0de0352aa1118f6aa4
persistence:
  sitesdirectory:
    enabled: true
    mountPath: /var/www/html/sites

securityContext:
  container:
    readOnlyRootFilesystem: false
    runAsGroup: 0
    runAsUser: 0
service:
  main:
    ports:
      main:
        port: 80
        protocol: tcp
        targetPort: 80
