image:
  pullPolicy: IfNotPresent
  repository: docker.io/vstavrinov/acestream-service
  tag: 2.1.1.1@sha256:36683f89bd1e8ac7a6e4faed0af1342018dcb4d551d695eb957d201473ed7839
persistence:
  acestreamcache:
    enabled: true
    mountPath: /srv/acestream/.ACEStream

securityContext:
  container:
    readOnlyRootFilesystem: false
    runAsGroup: 0
    runAsUser: 0
service:
  main:
    ports:
      main:
        port: 8008
        protocol: tcp
workload:
  main:
    podSpec:
      containers:
        main:
          env:
            ENTRY: "{{ .Values.service.main.ports.main.port }}"
            PORT: "{{ .Values.service.main.ports.main.port }}"
            SCHEME: http
