# yaml-language-server: $schema=./values.schema.json
image:
  repository: oci.trueforge.org/containerforge/code-server
  pullPolicy: IfNotPresent
  tag: "4.116.0@sha256:0f25a23088f86e9f639c3cb593bd33a29939b736a9f543b47ded0c57ace1cb74"
securityContext:
  container:
    readOnlyRootFilesystem: false
    allowPrivilegeEscalation: true
    runAsNonRoot: false
    runAsUser: 0
    runAsGroup: 0
service:
  main:
    ports:
      main:
        port: 10063
        protocol: http
        targetPort: 8443
workload:
  main:
    podSpec:
      containers:
        main:
          probes:
            liveness:
              type: http
              path: /
            readiness:
              type: http
              path: /
            startup:
              type: http
              path: /
          env:
            PROXY_DOMAIN: ""
          args:
            - --user-data-dir
            - "/config/.vscode"
            - --auth
            - none
persistence:
  config:
    enabled: true
    mountPath: /config
