# yaml-language-server: $schema=./values.schema.json
image:
  repository: oci.trueforge.org/containerforge/code-server
  pullPolicy: IfNotPresent
  tag: "4.130.0@sha256:6a9179acb55cd6d45e94fce5465902ca1047169ac99f7db372f7b84728b18b34"
securityContext:
  container:
    readOnlyRootFilesystem: false
    allowPrivilegeEscalation: true
    runAsNonRoot: false
    runAsUser: 0
    runAsGroup: 0
service:
  main:
    ports:
      main:
        port: 10063
        protocol: http
        targetPort: 8443
workload:
  main:
    podSpec:
      containers:
        main:
          probes:
            liveness:
              type: http
              path: /
            readiness:
              type: http
              path: /
            startup:
              type: http
              path: /
          env:
            PROXY_DOMAIN: ""
          args:
            - --user-data-dir
            - "/config/.vscode"
            - --auth
            - none
persistence:
  config:
    enabled: true
    mountPath: /config
