# yaml-language-server: $schema=./values.schema.json
image:
  repository: docker.io/thomst08/requestrr
  pullPolicy: IfNotPresent
  tag: v2.1.10@sha256:4e0b3f9d770d166043ea8d064cd57869548153b954ee19919b50e823eb78c817

securityContext:
  container:
    runAsNonRoot: false
    readOnlyRootFilesystem: false
    runAsUser: 0
    runAsGroup: 0

service:
  main:
    ports:
      main:
        targetPort: 4545
        port: 4545

persistence:
  config:
    enabled: true
    mountPath: "/root/config"
  varrun:
    enabled: true
