# yaml-language-server: $schema=./values.schema.json
image:
  repository: ghcr.io/archivebox/archivebox
  pullPolicy: IfNotPresent
  tag: 0.9.73@sha256:d4720d86c0e91577bccaee59fa238d22a9cfc0674aa594c80f739f0738270af9

config:
  admin_username: "admin"
  admin_password: "changeme"

service:
  main:
    ports:
      main:
        port: 9598
        protocol: http
        targetPort: 5797

workload:
  main:
    podSpec:
      containers:
        main:
          probes:
            liveness:
              type: http
              path: /health/
          env:
            ADMIN_USERNAME: "{{ .Values.config.admin_username }}"
            ADMIN_PASSWORD: "{{ .Values.config.admin_password }}"
            DATA_DIR: "/data/archivebox"

persistence:
  data:
    enabled: true
    mountPath: "/data"
  config:
    enabled: true
    mountPath: "/opt/archivebox"
  home:
    enabled: true
    mountPath: "/home/archivebox"
