# yaml-language-server: $schema=./values.schema.json
image:
  repository: docker.io/archivebox/archivebox
  pullPolicy: IfNotPresent
  tag: latest@sha256:1a5a37331091d9df865ead2b9c231aa5a892fc26fe0422ce6140d9e2d9532327

config:
  admin_username: "admin"
  admin_password: "changeme"

securityContext:
  container:
    readOnlyRootFilesystem: false
    runAsNonRoot: false
    runAsGroup: 0
    runAsUser: 0

service:
  main:
    ports:
      main:
        port: 9598
        protocol: http
        targetPort: 8000

workload:
  main:
    podSpec:
      containers:
        main:
          probes:
            liveness:
              type: http
              path: /health/
          env:
            ADMIN_USERNAME: "{{ .Values.config.admin_username }}"
            ADMIN_PASSWORD: "{{ .Values.config.admin_password }}"

persistence:
  data:
    enabled: true
    mountPath: "/data"
