# yaml-language-server: $schema=./values.schema.json
image:
  repository: docker.io/archivebox/archivebox
  pullPolicy: IfNotPresent
  tag: latest@sha256:56057dbe5ab387441e96c25a531d8934768bc977f94b9a91428f6913945e9b0d

config:
  admin_username: "admin"
  admin_password: "changeme"

securityContext:
  container:
    readOnlyRootFilesystem: false

service:
  main:
    ports:
      main:
        port: 9598
        protocol: http
        targetPort: 8000

workload:
  main:
    podSpec:
      containers:
        main:
          probes:
            liveness:
              type: http
              path: /health/
          env:
            ADMIN_USERNAME: "{{ .Values.config.admin_username }}"
            ADMIN_PASSWORD: "{{ .Values.config.admin_password }}"
            DATA_DIR: "/data"

persistence:
  data:
    enabled: true
    mountPath: "/data"
