# yaml-language-server: $schema=./values.schema.json
image:
  repository: docker.io/shokoanime/server
  pullPolicy: IfNotPresent
  tag: v5.3.2@sha256:14acb848d8e67e05a3365c36114df1c6dcdc4ae3aca574f4ee9b163599f1df44
service:
  main:
    ports:
      main:
        port: 8111
        protocol: http
        targetPort: 8111
persistence:
  appdata:
    enabled: true
    mountPath: /home/shoko/.shoko/

securityContext:
  container:
    readOnlyRootFilesystem: false
    runAsNonRoot: false
    runAsGroup: 0
    runAsUser: 0
