# yaml-language-server: $schema=./values.schema.json
image:
  repository: ghcr.io/agregarr/agregarr
  pullPolicy: IfNotPresent
  tag: v2.4.1@sha256:6022aef7ad580478bf100ee4b11f19ad689bb780d241e78e33a3ccc6b5feb569
securityContext:
  container:
    readOnlyRootFilesystem: false
    runAsNonRoot: false
    runAsGroup: 0
    runAsUser: 0
service:
  main:
    ports:
      main:
        protocol: http
        port: 7171
        targetPort: 7171
persistence:
  config:
    enabled: true
    mountPath: "/app/config"
