# yaml-language-server: $schema=./values.schema.json
image:
  repository: ghcr.io/linuxserver/filezilla
  tag: 3.69.6@sha256:c74d8e56d7a48d7e643e06f4f8119790df0eacbb0340268323704d349c94231f
  pullPolicy: IfNotPresent

securityContext:
  container:
    readOnlyRootFilesystem: false
    runAsUser: 0
    runAsGroup: 0

workload:
  main:
    podSpec:
      containers:
        main:
          securityContext:

service:
  main:
    ports:
      main:
        port: 10035
        protocol: http
        targetPort: 3000

persistence:
  config:
    enabled: true
    mountPath: "/config"
  varrun:
    enabled: false
