# yaml-language-server: $schema=./values.schema.json
image:
  repository: ghcr.io/linuxserver/filezilla
  tag: 3.68.1@sha256:0383fb6db15d0bdaa6b1efbc4bfffe36fcda0f4d6d0893e8d4dcd3a4fb88342b
  pullPolicy: IfNotPresent

securityContext:
  container:
    readOnlyRootFilesystem: false
    runAsUser: 0
    runAsGroup: 0

workload:
  main:
    podSpec:
      containers:
        main:
          securityContext:

service:
  main:
    ports:
      main:
        port: 10035
        protocol: http
        targetPort: 3000

persistence:
  config:
    enabled: true
    mountPath: "/config"
  varrun:
    enabled: false
