# yaml-language-server: $schema=./values.schema.json
image:
  repository: ghcr.io/linuxserver/filezilla
  tag: 3.69.6@sha256:50b432f8354d7f6bcf9fc7e479cff3f356834ea33c24f5cd726ce0023d702622
  pullPolicy: IfNotPresent

securityContext:
  container:
    readOnlyRootFilesystem: false
    runAsUser: 0
    runAsGroup: 0

workload:
  main:
    podSpec:
      containers:
        main:
          securityContext:

service:
  main:
    ports:
      main:
        port: 10035
        protocol: http
        targetPort: 3000

persistence:
  config:
    enabled: true
    mountPath: "/config"
  varrun:
    enabled: false
