# yaml-language-server: $schema=./values.schema.json
image:
  repository: docker.io/danmed/tasmobackupv1
  tag: 1.08.00@sha256:7f9efb47d49d8edb3e564badcdfecd2eea997a55ae01c77ea583dd8c407768ae
  pullPolicy: IfNotPresent

env:
  DBNAME: data/tasmobackup
  DBTYPE: sqlite

securityContext:
  container:
    readOnlyRootFilesystem: false
    runAsNonRoot: false
    runAsUser: 0
    runAsGroup: 0

workload:
  main:
    podSpec:
      containers:
        main:
          env:
            DBNAME: data/tasmobackup
            DBTYPE: sqlite
service:
  main:
    ports:
      main:
        port: 8259
        protocol: http
        targetPort: 80

persistence:
  data:
    enabled: true
    mountPath: /var/www/html/data
