# yaml-language-server: $schema=./values.schema.json
image:
  repository: docker.io/danmed/tasmobackupv1
  tag: 1.06.10@sha256:ff7129cd9af79fdf76a98b38bece260c87d8b36446cca8c1f881a10d074e5780
  pullPolicy: IfNotPresent

env:
  DBNAME: data/tasmobackup
  DBTYPE: sqlite

securityContext:
  container:
    readOnlyRootFilesystem: false
    runAsNonRoot: false
    runAsUser: 0
    runAsGroup: 0

workload:
  main:
    podSpec:
      containers:
        main:
          env:
            DBNAME: data/tasmobackup
            DBTYPE: sqlite
service:
  main:
    ports:
      main:
        port: 8259
        protocol: http
        targetPort: 80

persistence:
  data:
    enabled: true
    mountPath: /var/www/html/data
