image:
  repository: ghcr.io/linuxserver/pylon
  pullPolicy: IfNotPresent
  tag: 2.10.0@sha256:c6861ff7f9f9f21d2d7ad343e54013d6938d33e32b98cfc311ba16ca0379c43b
service:
  main:
    ports:
      main:
        targetPort: 3131
        port: 3131
persistence:
  code:
    enabled: true
    mountPath: "/code"
  varrun:
    enabled: true

securityContext:
  container:
    runAsNonRoot: false
    readOnlyRootFilesystem: false
    runAsUser: 0
    runAsGroup: 0
workload:
  main:
    podSpec:
      containers:
        main:
          env:
            GITURL: ""
            PYUSER: ""
            PYPASS: ""
