# yaml-language-server: $schema=./values.schema.json
image:
  pullPolicy: IfNotPresent
  repository: docker.io/glauth/glauth
  tag: latest@sha256:bb86be46186952579b023df88085e16b309d17c0e66756f0e79adc0698c8a4db
persistence:
  config:
    enabled: true
    mountPath: /app/config

securityContext:
  container:
    readOnlyRootFilesystem: false
    runAsGroup: 0
    runAsUser: 0
service:
  ldapport:
    enabled: true
    ports:
      ldapport:
        enabled: true
        port: 389
        protocol: tcp
        targetPort: 389
  ldapsport:
    enabled: true
    ports:
      ldapsport:
        enabled: true
        port: 636
        protocol: tcp
        targetPort: 636
  main:
    ports:
      main:
        port: 5555
        protocol: http
        targetPort: 5555
