# yaml-language-server: $schema=./values.schema.json
image:
  pullPolicy: IfNotPresent
  repository: docker.io/glauth/glauth
  tag: latest@sha256:6d448805cf54fc2ca3bca2b87f89dffe571a354a69a667b5a910111be3cf430e
persistence:
  config:
    enabled: true
    mountPath: /app/config

securityContext:
  container:
    readOnlyRootFilesystem: false
    runAsGroup: 0
    runAsUser: 0
service:
  ldapport:
    enabled: true
    ports:
      ldapport:
        enabled: true
        port: 389
        protocol: tcp
        targetPort: 389
  ldapsport:
    enabled: true
    ports:
      ldapsport:
        enabled: true
        port: 636
        protocol: tcp
        targetPort: 636
  main:
    ports:
      main:
        port: 5555
        protocol: http
        targetPort: 5555
