# yaml-language-server: $schema=./values.schema.json
image:
  pullPolicy: IfNotPresent
  repository: docker.io/fletchto99/hexo-dev-blog
  tag: latest@sha256:c1286587e594b3801dbd6d645a0bd2aa788c62b3675a98dc4aa396666ef56479
persistence:
  config:
    enabled: true
    mountPath: /config

securityContext:
  container:
    readOnlyRootFilesystem: false
    runAsGroup: 0
    runAsUser: 0
service:
  main:
    ports:
      main:
        port: 10306
        protocol: http
        targetPort: 8080
workload:
  main:
    podSpec:
      containers:
        main:
          env:
            HEXO_PLUGINS: ""
