# yaml-language-server: $schema=./values.schema.json
image:
  pullPolicy: IfNotPresent
  repository: docker.io/fletchto99/hexo-dev-blog
  tag: latest@sha256:ba11e2edd097fe8b6a58943b498da1ffdd4ba7fe92497b7d602809fa4525d547
persistence:
  config:
    enabled: true
    mountPath: /config

securityContext:
  container:
    readOnlyRootFilesystem: false
    runAsGroup: 0
    runAsUser: 0
service:
  main:
    ports:
      main:
        port: 10306
        protocol: http
        targetPort: 8080
workload:
  main:
    podSpec:
      containers:
        main:
          env:
            HEXO_PLUGINS: ""
