# yaml-language-server: $schema=./values.schema.json
image:
  pullPolicy: IfNotPresent
  repository: docker.io/fletchto99/hexo-dev-blog
  tag: latest@sha256:3319943ae744d2d41b67ba14ef8c363b4720090d6a6d0af1c582b20ea25b85ad
persistence:
  config:
    enabled: true
    mountPath: /config

securityContext:
  container:
    readOnlyRootFilesystem: false
    runAsGroup: 0
    runAsUser: 0
service:
  main:
    ports:
      main:
        port: 10306
        protocol: http
        targetPort: 8080
workload:
  main:
    podSpec:
      containers:
        main:
          env:
            HEXO_PLUGINS: ""
