# yaml-language-server: $schema=./values.schema.json
image:
  repository: ghcr.io/linuxserver/budge
  tag: 0.0.9@sha256:74765cd9d2b22142b87f7c558c3f479b7945250e1108c8f3c28c7b67bb36d1d3
  pullPolicy: IfNotPresent
securityContext:
  container:
    readOnlyRootFilesystem: false
    runAsNonRoot: false
    runAsUser: 0
    runAsGroup: 0
service:
  main:
    ports:
      main:
        port: 10165
        protocol: http
        targetPort: 80
workload:
  main:
    podSpec:
      containers:
        main:
          env:
            NODE_ENV: "production"
persistence:
  config:
    enabled: true
    mountPath: /config
