# yaml-language-server: $schema=./values.schema.json
image:
  repository: ghcr.io/linuxserver/budge
  tag: 0.0.9@sha256:187a8087588bd1d8dc6601a81a771549fcfe3cb72388633acb5e19dea11f338e
  pullPolicy: IfNotPresent
securityContext:
  container:
    readOnlyRootFilesystem: false
    runAsNonRoot: false
    runAsUser: 0
    runAsGroup: 0
service:
  main:
    ports:
      main:
        port: 10165
        protocol: http
        targetPort: 80
workload:
  main:
    podSpec:
      containers:
        main:
          env:
            NODE_ENV: "production"
persistence:
  config:
    enabled: true
    mountPath: /config
