# yaml-language-server: $schema=./values.schema.json
image:
  repository: ghcr.io/linuxserver/budge
  tag: 0.0.9@sha256:504d8607be689f7f3944d9f8d2d3a6c8f9f1542c4309a0f8bbb585a962e9f12f
  pullPolicy: IfNotPresent
securityContext:
  container:
    readOnlyRootFilesystem: false
    runAsNonRoot: false
    runAsUser: 0
    runAsGroup: 0
service:
  main:
    ports:
      main:
        port: 10165
        protocol: http
        targetPort: 80
workload:
  main:
    podSpec:
      containers:
        main:
          env:
            NODE_ENV: "production"
persistence:
  config:
    enabled: true
    mountPath: /config
