# yaml-language-server: $schema=./values.schema.json
image:
  repository: ghcr.io/linuxserver/openvscode-server
  pullPolicy: IfNotPresent
  tag: 1.109.5@sha256:e6785e89a0a5e4b6caf142b19194798df098da3fb11ae698050999cdcb0b7124
# secretEnv:
#   CONNECTION_TOKEN: "somerandomstring"
#   CONNECTION_SECRET: ""
#   SUDO_PASSWORD: ""
service:
  main:
    ports:
      main:
        targetPort: 3000
        port: 10135
persistence:
  config:
    enabled: true
    mountPath: "/config"
  varrun:
    enabled: true

securityContext:
  container:
    runAsNonRoot: false
    readOnlyRootFilesystem: false
    runAsUser: 0
    runAsGroup: 0
