# yaml-language-server: $schema=./values.schema.json
image:
  repository: ghcr.io/linuxserver/openvscode-server
  pullPolicy: IfNotPresent
  tag: 1.109.5@sha256:966533aa4ab554cca5121cd8d11f57ea9704a2b0284b1549cd730ef594c1c93f
# secretEnv:
#   CONNECTION_TOKEN: "somerandomstring"
#   CONNECTION_SECRET: ""
#   SUDO_PASSWORD: ""
service:
  main:
    ports:
      main:
        targetPort: 3000
        port: 10135
persistence:
  config:
    enabled: true
    mountPath: "/config"
  varrun:
    enabled: true

securityContext:
  container:
    runAsNonRoot: false
    readOnlyRootFilesystem: false
    runAsUser: 0
    runAsGroup: 0
