# yaml-language-server: $schema=./values.schema.json
image:
  pullPolicy: IfNotPresent
  repository: docker.io/towfiqi/serpbear
  tag: latest@sha256:1e356e33a63e6b544622074cf82c001060e283137f3f90caee0256cbc6c9ea33
persistence:
  data:
    enabled: true
    mountPath: /app/data

serpbear:
  api_key: ""
  app_url: http://localhost:10605
  password: secret
  session_duration: 24
  user: admin
service:
  main:
    ports:
      main:
        port: 10605
        protocol: http
        targetPort: 3000
workload:
  main:
    podSpec:
      containers:
        main:
          envFrom:
            - secretRef:
                name: serpbear-secret
