# yaml-language-server: $schema=./values.schema.json
image:
  repository: docker.io/haveagitgat/tdarr
  pullPolicy: IfNotPresent
  tag: 2.65.01@sha256:94bc18b3e9d3e9a7ae6fe75e86ff080a83905d32c0581529b2de6324fa2dcb53
service:
  main:
    ports:
      main:
        port: 8265
  comm:
    enabled: true
    ports:
      comm:
        enabled: true
        port: 8266
persistence:
  configs:
    enabled: true
    mountPath: "/app/configs"
  server:
    enabled: true
    mountPath: "/app/server"
  logs:
    enabled: true
    mountPath: "/app/logs"
  transcode-cache:
    enabled: true
    mountPath: "/temp"
  media:
    enabled: true
    mountPath: "/media"
  varrun:
    enabled: true

securityContext:
  container:
    readOnlyRootFilesystem: false
    runAsNonRoot: false
    runAsUser: 0
    runAsGroup: 0
workload:
  main:
    podSpec:
      containers:
        main:
          env:
            webUIPort: "{{ .Values.service.main.ports.main.port }}"
            serverPort: "{{ .Values.service.comm.ports.comm.port }}"
            # User Defined
            internalNode: true
            serverIP: "127.0.0.1"
            nodeID: "Internal Node"
