# yaml-language-server: $schema=./values.schema.json
image:
  repository: ghcr.io/linuxserver/webgrabplus
  pullPolicy: IfNotPresent
  tag: 5.5.3@sha256:daef585e4440946336a65cc624aa1d619e34f89eb706ce8447fbf0ea811fd038
service:
  main:
    enabled: false
    ports:
      main:
        enabled: false
persistence:
  varrun:
    enabled: true
  config:
    enabled: true
    mountPath: "/config"
  data:
    enabled: true
    mountPath: "/data"

securityContext:
  container:
    runAsNonRoot: false
    readOnlyRootFilesystem: false
    runAsUser: 0
    runAsGroup: 0
workload:
  main:
    podSpec:
      containers:
        main:
          probes:
            liveness:
              enabled: false
            readiness:
              enabled: false
            startup:
              enabled: false
