# yaml-language-server: $schema=./values.schema.json
image:
  repository: ghcr.io/linuxserver/webgrabplus
  pullPolicy: IfNotPresent
  tag: 5.6.0@sha256:7a966134bfd5563ba727aaea0a9a7c3d2fa8b657725b65950c8fd1b12619c4d4
service:
  main:
    enabled: false
    ports:
      main:
        enabled: false
persistence:
  varrun:
    enabled: true
  config:
    enabled: true
    mountPath: "/config"
  data:
    enabled: true
    mountPath: "/data"

securityContext:
  container:
    runAsNonRoot: false
    readOnlyRootFilesystem: false
    runAsUser: 0
    runAsGroup: 0
workload:
  main:
    podSpec:
      containers:
        main:
          probes:
            liveness:
              enabled: false
            readiness:
              enabled: false
            startup:
              enabled: false
