# yaml-language-server: $schema=./values.schema.json
image:
  repository: ghcr.io/linuxserver/webgrabplus
  pullPolicy: IfNotPresent
  tag: 5.5.3@sha256:83eeff62fd07556ecfa53845bbc0f1c6eb00544c5e55358bd182b4f9e2ff01ef
service:
  main:
    enabled: false
    ports:
      main:
        enabled: false
persistence:
  varrun:
    enabled: true
  config:
    enabled: true
    mountPath: "/config"
  data:
    enabled: true
    mountPath: "/data"

securityContext:
  container:
    runAsNonRoot: false
    readOnlyRootFilesystem: false
    runAsUser: 0
    runAsGroup: 0
workload:
  main:
    podSpec:
      containers:
        main:
          probes:
            liveness:
              enabled: false
            readiness:
              enabled: false
            startup:
              enabled: false
