# yaml-language-server: $schema=./values.schema.json
image:
  pullPolicy: IfNotPresent
  repository: ghcr.io/sethforprivacy/simple-monerod
  tag: v0.18.5.1@sha256:d8929c733eb3eeb8baff4b0ab8424391874fa1e7278520b8e2096390b85a27b9

monero:
  rpcbindip: "0.0.0.0"
  rpcbindport: "18089"
  publicnode: true
  noigd: true
  enablednsblocklist: true
  pruneblockchain: true

workload:
  main:
    podSpec:
      containers:
        main:
          env:
            HOME: /home/monero

securityContext:
  container:
    readOnlyRootFilesystem: false
    runAsGroup: 0
    runAsUser: 0

service:
  main:
    ports:
      main:
        port: 18080
        protocol: tcp
        targetPort: 18080
  rpc:
    enabled: true
    ports:
      rpc:
        enabled: true
        port: 18089
        protocol: tcp
        targetPort: 18089

persistence:
  blockchainstorage:
    enabled: true
    mountPath: /home/monero/.bitmonero
