# yaml-language-server: $schema=./values.schema.json
image:
  pullPolicy: IfNotPresent
  repository: ghcr.io/sethforprivacy/simple-monerod
  tag: v0.18.4.6@sha256:ed9299d73634a13f10de85e63d104276bf5e4ce5175ee4cc16f64f4bbeacbbd4

monero:
  rpcbindip: "0.0.0.0"
  rpcbindport: "18089"
  publicnode: true
  noigd: true
  enablednsblocklist: true
  pruneblockchain: true

securityContext:
  container:
    readOnlyRootFilesystem: false
    runAsGroup: 0
    runAsUser: 0

service:
  main:
    ports:
      main:
        port: 18080
        protocol: tcp
        targetPort: 18080
  rpc:
    enabled: true
    ports:
      rpc:
        enabled: true
        port: 18089
        protocol: tcp
        targetPort: 18089

persistence:
  blockchainstorage:
    enabled: true
    mountPath: /home/monero/.bitmonero
