# yaml-language-server: $schema=./values.schema.json
image:
  pullPolicy: IfNotPresent
  repository: ghcr.io/sethforprivacy/simple-monerod
  tag: v0.18.4.6@sha256:3c96f72d9b903623f13cc2a8460ec58ff440b2b58cfc797e11a02983e0cf155e

monero:
  rpcbindip: "0.0.0.0"
  rpcbindport: "18089"
  publicnode: true
  noigd: true
  enablednsblocklist: true
  pruneblockchain: true

securityContext:
  container:
    readOnlyRootFilesystem: false
    runAsGroup: 0
    runAsUser: 0

service:
  main:
    ports:
      main:
        port: 18080
        protocol: tcp
        targetPort: 18080
  rpc:
    enabled: true
    ports:
      rpc:
        enabled: true
        port: 18089
        protocol: tcp
        targetPort: 18089

persistence:
  blockchainstorage:
    enabled: true
    mountPath: /home/monero/.bitmonero
