# yaml-language-server: $schema=./values.schema.json
image:
  repository: ghcr.io/autobrr/autobrr
  pullPolicy: IfNotPresent
  tag: v1.87.0@sha256:1a72b15b3cc3899082de38fbc05efab0dc0498135be359aa280078876c68f455

service:
  main:
    ports:
      main:
        protocol: http
        port: 7474

autobrr:
  # ERROR | DEBUG |INFO | WARN | TRACE
  log_level: DEBUG

workload:
  main:
    podSpec:
      containers:
        main:
          probes:
            liveness:
              type: http
            readiness:
              type: http
            startup:
              type: tcp

persistence:
  config:
    enabled: true
    mountPath: /config
  autobrr-config:
    enabled: true
    type: configmap
    objectName: autobrr-config
    mountPath: /config/config.toml
    subPath: config.toml
    readOnly: true
