# yaml-language-server: $schema=./values.schema.json
image:
  repository: ghcr.io/autobrr/autobrr
  pullPolicy: IfNotPresent
  tag: v1.76.0@sha256:f0f4d73fcd77700b1c98233562cd94a78b9bf685a7594a0aac4f8a9436b5044d

service:
  main:
    ports:
      main:
        protocol: http
        port: 7474

autobrr:
  # ERROR | DEBUG |INFO | WARN | TRACE
  log_level: DEBUG

workload:
  main:
    podSpec:
      containers:
        main:
          probes:
            liveness:
              type: http
            readiness:
              type: http
            startup:
              type: tcp

persistence:
  config:
    enabled: true
    mountPath: /config
  autobrr-config:
    enabled: true
    type: configmap
    objectName: autobrr-config
    mountPath: /config/config.toml
    subPath: config.toml
    readOnly: true
