# yaml-language-server: $schema=./values.schema.json
image:
  repository: ghcr.io/autobrr/autobrr
  pullPolicy: IfNotPresent
  tag: v1.82.0@sha256:b666903f1bba48e380b211da779ffd89f34f8ebfa2f32b1c4b1e60f8882df2bf

service:
  main:
    ports:
      main:
        protocol: http
        port: 7474

autobrr:
  # ERROR | DEBUG |INFO | WARN | TRACE
  log_level: DEBUG

workload:
  main:
    podSpec:
      containers:
        main:
          probes:
            liveness:
              type: http
            readiness:
              type: http
            startup:
              type: tcp

persistence:
  config:
    enabled: true
    mountPath: /config
  autobrr-config:
    enabled: true
    type: configmap
    objectName: autobrr-config
    mountPath: /config/config.toml
    subPath: config.toml
    readOnly: true
