# yaml-language-server: $schema=./values.schema.json
image:
  repository: oci.trueforge.org/containerforge/nzbhydra2
  pullPolicy: IfNotPresent
  tag: 8.5.2@sha256:63d9e59450c4eeafe1e1542e765b6cfe1238cb1eb287340c22a294ba36ec67f5
service:
  main:
    ports:
      main:
        port: 5076
        targetPort: 5076
persistence:
  config:
    enabled: true
    mountPath: "/config"

securityContext:
  container:
    readOnlyRootFilesystem: false
workload:
  main:
    podSpec:
      containers:
        main:
          probes:
            liveness:
              custom: true
              enabled: true
              spec:
                failureThreshold: 5
                httpGet:
                  path: /actuator/health/livenessState
                  port: main
                initialDelaySeconds: 30
                periodSeconds: 10
                timeoutSeconds: 10
            readiness:
              custom: true
              enabled: true
              spec:
                failureThreshold: 5
                httpGet:
                  path: /actuator/health/readinessState
                  port: main
                initialDelaySeconds: 30
                periodSeconds: 10
                timeoutSeconds: 10
            startup:
              custom: true
              enabled: true
              spec:
                failureThreshold: 5
                httpGet:
                  path: /actuator/health/readinessState
                  port: main
                initialDelaySeconds: 30
                periodSeconds: 10
                timeoutSeconds: 10
