# yaml-language-server: $schema=./values.schema.json
image:
  repository: oci.trueforge.org/containerforge/nzbhydra2
  pullPolicy: IfNotPresent
  tag: 8.9.0@sha256:e4e1a2512b3290f2bdbcba643947c6530f03aa1d0f937fe1aefe205c5e18f9b7
service:
  main:
    ports:
      main:
        port: 5076
        targetPort: 5076
persistence:
  config:
    enabled: true
    mountPath: "/config"

securityContext:
  container:
    readOnlyRootFilesystem: false
workload:
  main:
    podSpec:
      containers:
        main:
          probes:
            liveness:
              custom: true
              enabled: true
              spec:
                failureThreshold: 5
                httpGet:
                  path: /actuator/health/livenessState
                  port: main
                initialDelaySeconds: 30
                periodSeconds: 10
                timeoutSeconds: 10
            readiness:
              custom: true
              enabled: true
              spec:
                failureThreshold: 5
                httpGet:
                  path: /actuator/health/readinessState
                  port: main
                initialDelaySeconds: 30
                periodSeconds: 10
                timeoutSeconds: 10
            startup:
              custom: true
              enabled: true
              spec:
                failureThreshold: 5
                httpGet:
                  path: /actuator/health/readinessState
                  port: main
                initialDelaySeconds: 30
                periodSeconds: 10
                timeoutSeconds: 10
