# yaml-language-server: $schema=./values.schema.json
image:
  repository: ghcr.io/jordan-dalby/bytestash
  tag: 1.5.12@sha256:eb4f736b8cd45443be0ed6d8da3ee49b76dbf27f4d3925b81b3c407207e62531
  pullPolicy: IfNotPresent
service:
  main:
    ports:
      main:
        port: 5000
        protocol: http
persistence:
  data:
    enabled: true
    mountPath: "/data/snippets"

workload:
  main:
    podSpec:
      containers:
        main:
          env:
            BASE_PATH: ""
            JWT_SECRET: "bytestash JWT secret"
            TOKEN_EXPIRY: "24h"
            ALLOW_NEW_ACCOUNTS: "false"
            DEBUG: "false"
            DISABLE_ACCOUNTS: "false"
            DISABLE_INTERNAL_ACCOUNTS: "false"
            OIDC_ENABLED: "false"
            OIDC_DISPLAY_NAME: ""
            OIDC_ISSUER_URL: ""
            OIDC_CLIENT_ID: ""
            OIDC_CLIENT_SECRET: ""
            OIDC_SCOPES: ""
