# yaml-language-server: $schema=./values.schema.json
image:
  repository: docker.io/yourselfhosted/slash
  pullPolicy: IfNotPresent
  tag: 1.0.0-rc.3@sha256:c34a45a0197f1822cf7bd1796ead899efb77b7ff8b926f825ad82362fdc3d093
service:
  main:
    ports:
      main:
        protocol: http
        port: 5231
workload:
  main:
    podSpec:
      containers:
        main:
          env:
            SLASH_PORT: "{{ .Values.service.main.ports.main.port }}"
persistence:
  config:
    enabled: true
    mountPath: "/var/opt/slash"
