# yaml-language-server: $schema=./values.schema.json
image:
  repository: docker.io/gabekangas/owncast
  tag: 0.3.0@sha256:efca3c284ac1d6d7d775d193e74f92f718774a4aa0d621f55dce449222ca5bff
  pullPolicy: IfNotPresent
service:
  main:
    ports:
      main:
        port: 10088
        targetPort: 8080
  rtmp:
    enabled: true
    # externalTrafficPolicy: Local
    ports:
      rtmp:
        enabled: true
        port: 1935
        targetPort: 1935
persistence:
  config:
    enabled: true
    mountPath: "/app/data"

securityContext:
  container:
    readOnlyRootFilesystem: false
    runAsNonRoot: false
    runAsUser: 0
    runAsGroup: 0
