image:
  repository: fyb3roptik/threadfin
  tag: 1.3.0@sha256:7131896922fd1965e064e6ce4dbcf28ca9a8c5ae21960eee56577764485b674e
  pullPolicy: IfNotPresent
service:
  main:
    ports:
      main:
        port: 34400
persistence:
  config:
    enabled: true
    mountPath: "/home/threadfin/conf"
  temp:
    enabled: true
    mountPath: "/tmp/threadfin"
    type: emptyDir
