# yaml-language-server: $schema=./values.schema.json
image:
  repository: docker.io/gotson/komga
  tag: 1.26.3@sha256:6c2a967bbe9acefd05933b2eb498f34afe96a83c6f7f8ab0acb512a1bb3ab50f
  pullPolicy: IfNotPresent
workload:
  main:
    podSpec:
      containers:
        main:
          env:
            SERVER_PORT: "{{ .Values.service.main.ports.main.port }}"
          probes:
            liveness:
              port: "{{ .Values.service.main.ports.main.port }}"
              path: /actuator/health
            readiness:
              port: "{{ .Values.service.main.ports.main.port }}"
              path: /actuator/health
            startup:
              type: tcp
              port: "{{ .Values.service.main.ports.main.port }}"
service:
  main:
    ports:
      main:
        port: 10085
persistence:
  config:
    enabled: true
    mountPath: "/config"
  data:
    enabled: true
    mountPath: "/data"
