# yaml-language-server: $schema=./values.schema.json
image:
  repository: ghcr.io/gotson/komga
  tag: 1.28.1@sha256:d8f772dce7b3dcd8baa0ce7481bd890e68446065ab6c8eb2cb5b24df62fb3c4f
  pullPolicy: IfNotPresent
workload:
  main:
    podSpec:
      containers:
        main:
          env:
            SERVER_PORT: "{{ .Values.service.main.ports.main.port }}"
          probes:
            liveness:
              port: "{{ .Values.service.main.ports.main.port }}"
              path: /actuator/health
            readiness:
              port: "{{ .Values.service.main.ports.main.port }}"
              path: /actuator/health
            startup:
              type: tcp
              port: "{{ .Values.service.main.ports.main.port }}"
service:
  main:
    ports:
      main:
        port: 10085
persistence:
  config:
    enabled: true
    mountPath: "/config"
  data:
    enabled: true
    mountPath: "/data"
