# yaml-language-server: $schema=./values.schema.json
image:
  pullPolicy: IfNotPresent
  repository: docker.io/shawly/ps3netsrv
  tag: v1.12.0@sha256:4a7efaa36cf5a09117780ee4afed7dac08eb95e2f1ed1ac0cc9d87f11c1b509f
securityContext:
  container:
    readOnlyRootFilesystem: false
    runAsUser: 0
    runAsGroup: 0
service:
  main:
    ports:
      main:
        port: 38008
        targetPort: 38008
        protocol: tcp

persistence:
  games:
    enabled: true
    mountPath: /games
