# yaml-language-server: $schema=./values.schema.json
image:
  pullPolicy: IfNotPresent
  repository: docker.io/shawly/ps3netsrv
  tag: v2.0.1@sha256:fc5b15f2d6fdd9a761ec72985ad5681907ff8d794dbe0698a7001c575d92f581
securityContext:
  container:
    readOnlyRootFilesystem: false
    runAsUser: 0
    runAsGroup: 0
service:
  main:
    ports:
      main:
        port: 38008
        targetPort: 38008
        protocol: tcp

persistence:
  games:
    enabled: true
    mountPath: /games
