# yaml-language-server: $schema=./values.schema.json
image:
  pullPolicy: IfNotPresent
  repository: docker.io/shawly/ps3netsrv
  tag: v2.0.1@sha256:dae2ae1160ada3151d2f69e120d68349d9b7664b72d6eecad2f37cd9d3d9b461
securityContext:
  container:
    readOnlyRootFilesystem: false
    runAsUser: 0
    runAsGroup: 0
service:
  main:
    ports:
      main:
        port: 38008
        targetPort: 38008
        protocol: tcp

persistence:
  games:
    enabled: true
    mountPath: /games
