# yaml-language-server: $schema=./values.schema.json
image:
  repository: docker.io/docuseal/docuseal
  tag: 3.0.3@sha256:4d029dd71693924fe4c03e4caf01428b9c967cb10708ceab993aa6dfb556e9b0
  pullPolicy: IfNotPresent
securityContext:
  container:
    readOnlyRootFilesystem: false
    runAsNonRoot: false
    runAsUser: 0
    runAsGroup: 0
service:
  main:
    ports:
      main:
        port: 10310
        protocol: http
        targetPort: 3000

workload:
  main:
    podSpec:
      containers:
        main:
          env:
            DATABASE_URL:
              secretKeyRef:
                name: cnpg-main-urls
                key: std
          probes:
            liveness:
              type: http
              path: /
            readiness:
              type: http
              path: /
            startup:
              type: http
              path: /

persistence:
  data:
    enabled: true
    mountPath: /data

cnpg:
  main:
    enabled: true
    user: docuseal
    database: docuseal
