image:
  repository: docker.io/docuseal/docuseal
  tag: 2.0.7@sha256:7af0ac52f714af91f41de2d4069a4d2dcf8a167ff88065267fd0a8ed074fdfe9
  pullPolicy: IfNotPresent
securityContext:
  container:
    readOnlyRootFilesystem: false
    runAsNonRoot: false
    runAsUser: 0
    runAsGroup: 0
service:
  main:
    ports:
      main:
        port: 10310
        protocol: http
        targetPort: 3000

workload:
  main:
    podSpec:
      containers:
        main:
          env:
            DATABASE_URL:
              secretKeyRef:
                name: cnpg-main-urls
                key: std
          probes:
            liveness:
              type: http
              path: /
            readiness:
              type: http
              path: /
            startup:
              type: http
              path: /

persistence:
  data:
    enabled: true
    mountPath: /data

cnpg:
  main:
    enabled: true
    user: docuseal
    database: docuseal
