# yaml-language-server: $schema=./values.schema.json
image:
  repository: docker.io/docuseal/docuseal
  tag: 3.1.1@sha256:0db707ba6dda8c5a937fec1a1722af4f926a4e575c0edaf994cab91a4333e6a5
  pullPolicy: IfNotPresent
securityContext:
  container:
    readOnlyRootFilesystem: false
    runAsNonRoot: false
    runAsUser: 0
    runAsGroup: 0
service:
  main:
    ports:
      main:
        port: 10310
        protocol: http
        targetPort: 3000

workload:
  main:
    podSpec:
      containers:
        main:
          env:
            DATABASE_URL:
              secretKeyRef:
                name: cnpg-main-urls
                key: std
          probes:
            liveness:
              type: http
              path: /
            readiness:
              type: http
              path: /
            startup:
              type: http
              path: /

persistence:
  data:
    enabled: true
    mountPath: /data

cnpg:
  main:
    enabled: true
    user: docuseal
    database: docuseal
