# yaml-language-server: $schema=./values.schema.json
image:
  repository: ghcr.io/linuxserver/znc
  pullPolicy: IfNotPresent
  tag: 1.10.1@sha256:d1a78cc0edf2fc856b482d8fd0f7b387301452c694d0f49a870eaa8472a4d8a7
service:
  main:
    ports:
      main:
        targetPort: 6501
        port: 6501
persistence:
  varrun:
    enabled: true
  config:
    enabled: true
    mountPath: "/config"

securityContext:
  container:
    runAsNonRoot: false
    readOnlyRootFilesystem: false
    runAsUser: 0
    runAsGroup: 0
