# yaml-language-server: $schema=./values.schema.json
image:
  repository: ghcr.io/linuxserver/znc
  pullPolicy: IfNotPresent
  tag: 1.10.3@sha256:d2bceb0d55c84bb053039724787297b9a8ba4f532182d27eabd47d6e88a5a268
service:
  main:
    ports:
      main:
        targetPort: 6501
        port: 6501
persistence:
  varrun:
    enabled: true
  config:
    enabled: true
    mountPath: "/config"

securityContext:
  container:
    runAsNonRoot: false
    readOnlyRootFilesystem: false
    runAsUser: 0
    runAsGroup: 0
