# yaml-language-server: $schema=./values.schema.json
image:
  pullPolicy: IfNotPresent
  repository: docker.io/phasecorex/red-discordbot
  tag: full@sha256:62e3ebf3e37af0305be19a3f22c3194e9e8047df10b83d668c758fe5aa5b4f67
persistence:
  data:
    enabled: true
    mountPath: /data

securityContext:
  container:
    readOnlyRootFilesystem: false
    runAsGroup: 0
    runAsUser: 0
service:
  main:
    enabled: false
    ports:
      main:
        enabled: false
workload:
  main:
    podSpec:
      containers:
        main:
          env:
            PREFIX: ""
            TOKEN: ""
          probes:
            liveness:
              enabled: false
            readiness:
              enabled: false
            startup:
              enabled: false
