# yaml-language-server: $schema=./values.schema.json
image:
  pullPolicy: IfNotPresent
  repository: docker.io/phasecorex/red-discordbot
  tag: full@sha256:c7d788f2c93eb4ad63c0bd707076d55b7a926a2d1ecbf198925c8954850cd628
persistence:
  data:
    enabled: true
    mountPath: /data

securityContext:
  container:
    readOnlyRootFilesystem: false
    runAsGroup: 0
    runAsUser: 0
service:
  main:
    enabled: false
    ports:
      main:
        enabled: false
workload:
  main:
    podSpec:
      containers:
        main:
          env:
            PREFIX: ""
            TOKEN: ""
          probes:
            liveness:
              enabled: false
            readiness:
              enabled: false
            startup:
              enabled: false
