# yaml-language-server: $schema=./values.schema.json
image:
  pullPolicy: IfNotPresent
  repository: lscr.io/linuxserver/webtop
  tag: latest@sha256:d43f989b9795c03b59cb7f01bad3e9298f7f27b0ba2b248bbeeb32f8a6f87a06
ubuntuXFCEImage:
  repository: lscr.io/linuxserver/webtop
  tag: ubuntu-xfce@sha256:e37c63a87ae2d78c04f2e4ec383e79f2b9b3a6a7ad6980922abb7cec9565fc71
  pullPolicy: Always
fedoraXFCEImage:
  repository: lscr.io/linuxserver/webtop
  tag: fedora-xfce@sha256:33e45058d56bd6ab26e69ff38732890d1621ad863990368848a6afc4a8b693b3
  pullPolicy: Always
archXFCEImage:
  repository: lscr.io/linuxserver/webtop
  tag: arch-xfce@sha256:455c08199eea757a4b17d478880a682ec044f24ab0c586cf062a0f33ea7c7173
  pullPolicy: Always
alpineKDEImage:
  repository: lscr.io/linuxserver/webtop
  tag: alpine-kde@sha256:e7db689543b9efef103e4d6a4acc8c5d31809a0f2ba27786a8e9cdc51ab40c17
  pullPolicy: Always
ubuntuKDEImage:
  repository: lscr.io/linuxserver/webtop
  tag: ubuntu-kde@sha256:7bb625c02c53b13165f846758d9c01acba6a30ef37a2da497b8b757f163b39e5
  pullPolicy: Always
fedoraKDEImage:
  repository: lscr.io/linuxserver/webtop
  tag: fedora-kde@sha256:f52b484a2d28ef0ae3b175f366e38210445d9394dc5a9e16b8d00f21b1fb2d56
  pullPolicy: Always
archKDEImage:
  repository: lscr.io/linuxserver/webtop
  tag: arch-kde@sha256:294d397d7eaa1ef7e85a3ebf50efb32c0d731f2f28ea5c27c6f17a3a6307a8dd
  pullPolicy: Always
alpineMATEImage:
  repository: lscr.io/linuxserver/webtop
  tag: alpine-mate@sha256:1c83e4bfa385e496415b6f94c6b1bff3e96303dd177ecd8565dd4fbd00b91d3b
  pullPolicy: Always
ubuntuMATEImage:
  repository: lscr.io/linuxserver/webtop
  tag: ubuntu-mate@sha256:e2f6c66aba08062d15a7917d4ab68d6b352a1e7112fe431fcc6c0dd9dfcf79df
  pullPolicy: Always
fedoraMATEImage:
  repository: lscr.io/linuxserver/webtop
  tag: fedora-mate@sha256:46bd7bee7262ba09adb118a08939a67d10d2d4b82ff111e420e7c76cec89a15e
  pullPolicy: Always
archMATEImage:
  repository: lscr.io/linuxserver/webtop
  tag: arch-mate@sha256:39fb80999382158c0966e339977238e3ceadc63a3fdba554c777eaf1380312ef
  pullPolicy: Always
alpineI3Image:
  repository: lscr.io/linuxserver/webtop
  tag: alpine-i3@sha256:0f2ca6c6f2552e7786c5dc02c88b06ffc0a00d4945320e4c2444084185a5950d
  pullPolicy: Always
ubuntuI3Image:
  repository: lscr.io/linuxserver/webtop
  tag: ubuntu-i3@sha256:70d9dd313d5ccd983582205d39d3fb27fb1cf43e539296620e225ce41a9475b5
  pullPolicy: Always
fedoraI3Image:
  repository: lscr.io/linuxserver/webtop
  tag: fedora-i3@sha256:04436785163fcc1262782f1032dfec2bc9296d96b6375c8e76d2469f38ed885b
  pullPolicy: Always
archI3Image:
  repository: lscr.io/linuxserver/webtop
  tag: arch-i3@sha256:3c12974952348cebe8e08b6940a8c483112a528396fb21b04dd176e2eb196b3f
  pullPolicy: Always
alpineOpenBoxImage:
  repository: lscr.io/linuxserver/webtop
  tag: alpine-openbox@sha256:32d2f78a5d2359569c8a625d080ed53ecead477ccca707c55c1afc9c6e0765f9
  pullPolicy: Always
ubuntuOpenBoxImage:
  repository: lscr.io/linuxserver/webtop
  tag: ubuntu-openbox@sha256:539248133c65e3d2d70dff67c8f9ff297186615487972491451210b1b9ee4d71
  pullPolicy: Always
fedoraOpenBoxImage:
  repository: lscr.io/linuxserver/webtop
  tag: fedora-openbox@sha256:c40f887d9c03c5966debdfb8d9a6fb1a446cd5cb5dadde6195ca35a068742409
  pullPolicy: Always
archOpenBoxImage:
  repository: lscr.io/linuxserver/webtop
  tag: arch-openbox@sha256:7f079e913b5696455889f795aff7c3acea1ab581de313ec63a797604c805d12d
  pullPolicy: Always
alpineICEWMImage:
  repository: lscr.io/linuxserver/webtop
  tag: alpine-icewm@sha256:440aebeafa9b9101d03f633be9a504d75917fcb7d6847842f67aa033c46f06f3
  pullPolicy: Always
ubuntuICEWMImage:
  repository: lscr.io/linuxserver/webtop
  tag: ubuntu-icewm@sha256:26f960e120edc080a12dfd76944acae0296eb7b69d79c437ef329836cc09e47a
  pullPolicy: Always
fedoraICEWMImage:
  repository: lscr.io/linuxserver/webtop
  tag: fedora-icewm@sha256:871a0acf70fb754216f11b0c98fec51ab6871fc00f12a9a20eae0202cf7b1644
  pullPolicy: Always
archICEWMImage:
  repository: lscr.io/linuxserver/webtop
  tag: arch-icewm@sha256:54d9079d38aee34063206fb5b233ea7c8801108756fb61aa0680eabdfad91dcd
  pullPolicy: Always
service:
  main:
    ports:
      main:
        port: 33000
        protocol: http
persistence:
  config:
    enabled: true
    mountPath: /config

securityContext:
  container:
    readOnlyRootFilesystem: false
    runAsNonRoot: false
    runAsGroup: 0
    runAsUser: 0
workload:
  main:
    podSpec:
      containers:
        main:
          imageSelector: image
          env:
            KEYBOARD: "en-us-qwerty"
            CUSTOM_PORT: "{{ .Values.service.main.ports.main.port }}"
updated: true
