annotations:
  artifacthub.io/links: |-
    - name: support
    url: https://discord.com/invite/tVsPTHWTtr
  truecharts.org/train: incubator
  trueforge.org/category: operators
  trueforge.org/max_helm_version: "4.1"
  trueforge.org/max_kubernetes_version: 1.35.0
  trueforge.org/min_helm_version: "3.14"
  trueforge.org/train: incubator
apiVersion: v2
appVersion: 0.45.0
dependencies:
  - name: common
    version: 29.5.3
    repository: oci://oci.trueforge.org/truecharts
    condition: ""
    alias: ""
    tags: []
    import-values: []
deprecated: false
description: Headlamp is a user-friendly Kubernetes UI focused on extensibility
home: https://truecharts.org/charts/incubator/headlamp
icon: https://truecharts.org/img/hotlink-ok/chart-icons/headlamp.webp
keywords:
  - headlamp
  - kubernetes
  - UI
kubeVersion: '>=1.33.0-0'
maintainers:
  - name: TrueCharts
    email: info@truecharts.org
    url: https://truecharts.org
name: headlamp
sources:
  - https://ghcr.io/headlamp-k8s/headlamp
  - https://github.com/kubernetes-sigs/headlamp
  - https://github.com/trueforge-org/containers/tree/main/apps/node
  - https://github.com/trueforge-org/truecharts/tree/master/charts/incubator/headlamp
  - https://github.com/trueforge/truecharts/tree/master/charts/incubator/headlamp
  - https://headlamp.dev
type: application
version: 0.1.0

