# yaml-language-server: $schema=./values.schema.json
image:
  repository: ghcr.io/linuxserver/mstream
  pullPolicy: IfNotPresent
  tag: 6.6.0@sha256:305f6c36ccee59237b6d5f84aa5d0a98ec554683ff51c2a4459bc28a3c91960c
service:
  main:
    ports:
      main:
        port: 10041
        targetPort: 3000
persistence:
  config:
    enabled: true
    mountPath: "/config"
  varrun:
    enabled: true

securityContext:
  container:
    readOnlyRootFilesystem: false
    runAsNonRoot: false
    runAsUser: 0
    runAsGroup: 0
