# yaml-language-server: $schema=./values.schema.json
image:
  repository: ghcr.io/linuxserver/mstream
  pullPolicy: IfNotPresent
  tag: 6.3.0@sha256:7987dfc04b997baa85d02a1e4fae4e156551d1e38cd46a89c3fab90091248504
service:
  main:
    ports:
      main:
        port: 10041
        targetPort: 3000
persistence:
  config:
    enabled: true
    mountPath: "/config"
  varrun:
    enabled: true

securityContext:
  container:
    readOnlyRootFilesystem: false
    runAsNonRoot: false
    runAsUser: 0
    runAsGroup: 0
