# yaml-language-server: $schema=./values.schema.json
image:
  repository: ghcr.io/linuxserver/mstream
  pullPolicy: IfNotPresent
  tag: 6.18.1@sha256:52972e0dfb38bb78e35dfbde2f5bcc0100e6aef48846912936102a93ce3514e7
service:
  main:
    ports:
      main:
        port: 10041
        targetPort: 3000
persistence:
  config:
    enabled: true
    mountPath: "/config"
  varrun:
    enabled: true

securityContext:
  container:
    readOnlyRootFilesystem: false
    runAsNonRoot: false
    runAsUser: 0
    runAsGroup: 0
