# yaml-language-server: $schema=./values.schema.json
image:
  repository: ghcr.io/linuxserver/orcaslicer
  pullPolicy: IfNotPresent
  tag: 2.4.1@sha256:c6d19d36e6c3b466e8e1fa815468423f165e465b56068abbf8dc7d03c7cce87d
securityContext:
  container:
    readOnlyRootFilesystem: false
    runAsNonRoot: false
    runAsUser: 0
    runAsGroup: 0
service:
  main:
    ports:
      main:
        port: 3000
persistence:
  config:
    enabled: true
    mountPath: /config
