# yaml-language-server: $schema=./values.schema.json
image:
  repository: ghcr.io/linuxserver/orcaslicer
  pullPolicy: IfNotPresent
  tag: 2.3.2@sha256:7b98fd28550fda7940e92392c6b963fc7c159651640b440458b98e6426ec5af0
securityContext:
  container:
    readOnlyRootFilesystem: false
    runAsNonRoot: false
    runAsUser: 0
    runAsGroup: 0
service:
  main:
    ports:
      main:
        port: 3000
persistence:
  config:
    enabled: true
    mountPath: /config
