# yaml-language-server: $schema=./values.schema.json
image:
  repository: ghcr.io/linuxserver/orcaslicer
  pullPolicy: IfNotPresent
  tag: 2.3.2@sha256:62de5bc4d44b2d46292c4089e3c479723608bdee9323acbd0727446c8a1d7674
securityContext:
  container:
    readOnlyRootFilesystem: false
    runAsNonRoot: false
    runAsUser: 0
    runAsGroup: 0
service:
  main:
    ports:
      main:
        port: 3000
persistence:
  config:
    enabled: true
    mountPath: /config
