# yaml-language-server: $schema=./values.schema.json
image:
  repository: docker.io/foxxmd/multi-scrobbler
  tag: latest@sha256:7681cf6c6a936627d7d6b571850aab38e6728188cc5a21bd3ac509c2201b41d6
  pullPolicy: IfNotPresent

securityContext:
  container:
    readOnlyRootFilesystem: false
    runAsNonRoot: false
    runAsGroup: 0
    runAsUser: 0

service:
  main:
    ports:
      main:
        port: 9078
        targetPort: 9078

persistence:
  config:
    enabled: true
    mountPath: /config
