# yaml-language-server: $schema=./values.schema.json
image:
  repository: docker.io/foxxmd/multi-scrobbler
  tag: latest@sha256:992ad822817d490017d2c0098b53bda0f1032379ed604fc2089974c0930d1d42
  pullPolicy: IfNotPresent

securityContext:
  container:
    readOnlyRootFilesystem: false
    runAsNonRoot: false
    runAsGroup: 0
    runAsUser: 0

service:
  main:
    ports:
      main:
        port: 9078
        targetPort: 9078

persistence:
  config:
    enabled: true
    mountPath: /config
