# yaml-language-server: $schema=./values.schema.json
image:
  repository: docker.io/foxxmd/multi-scrobbler
  tag: latest@sha256:705b6890b742e436886872a142da66ec3dd8e572e4cf8b91721212086700221f
  pullPolicy: IfNotPresent

securityContext:
  container:
    readOnlyRootFilesystem: false
    runAsNonRoot: false
    runAsGroup: 0
    runAsUser: 0

service:
  main:
    ports:
      main:
        port: 9078
        targetPort: 9078

persistence:
  config:
    enabled: true
    mountPath: /config
