# yaml-language-server: $schema=./values.schema.json
image:
  repository: oci.trueforge.org/containerforge/it-tools
  pullPolicy: IfNotPresent
  tag: 2024.10.22@sha256:3c34b39c690d74f8f7e3e3aaed9354b0b82059d9dafe274b3f74c0e46114c67a
service:
  main:
    ports:
      main:
        protocol: http
        targetPort: 8080
        port: 18082
persistence:
  cache:
    enabled: true
    type: emptyDir
    mountPath: "/var/cache/nginx"
  config:
    enabled: true
    type: emptyDir
    mountPath: /config
