# yaml-language-server: $schema=./values.schema.json
image:
  repository: oci.trueforge.org/containerforge/it-tools
  pullPolicy: IfNotPresent
  tag: 2024.10.22@sha256:5e592931bc6b91b5606d733310cde76ca20ac86398daea19d84e9255856cf7d3
service:
  main:
    ports:
      main:
        protocol: http
        targetPort: 8080
        port: 18082
persistence:
  cache:
    enabled: true
    type: emptyDir
    mountPath: "/var/cache/nginx"
  config:
    enabled: true
    type: emptyDir
    mountPath: /config
