# yaml-language-server: $schema=./values.schema.json
image:
  repository: ghcr.io/actualbudget/actual
  pullPolicy: IfNotPresent
  tag: 26.8.1@sha256:6478d9ddfc0924479c09e6699c205e354c6f2216dfe7de3c0fb7b590d6edcdc5
securityContext:
  container:
    readOnlyRootFilesystem: false
    runAsNonRoot: false
    runAsGroup: 0
    runAsUser: 0
workload:
  main:
    podSpec:
      containers:
        main:
          probes:
            liveness:
              type: http
              path: /
            readiness:
              type: http
              path: /
            startup:
              type: http
              path: /
          env: {}
service:
  main:
    ports:
      main:
        port: 10293
        protocol: http
        targetPort: 5006
persistence:
  data:
    enabled: true
    mountPath: /data
