# yaml-language-server: $schema=./values.schema.json
image:
  repository: ghcr.io/actualbudget/actual
  pullPolicy: IfNotPresent
  tag: 26.9.0@sha256:552beab3dec8c93d46b8b9245612d63c3f123b8a45063a474f53e229b17621d3
securityContext:
  container:
    readOnlyRootFilesystem: false
    runAsNonRoot: false
    runAsGroup: 0
    runAsUser: 0
workload:
  main:
    podSpec:
      containers:
        main:
          probes:
            liveness:
              type: http
              path: /
            readiness:
              type: http
              path: /
            startup:
              type: http
              path: /
          env: {}
service:
  main:
    ports:
      main:
        port: 10293
        protocol: http
        targetPort: 5006
persistence:
  data:
    enabled: true
    mountPath: /data
