# yaml-language-server: $schema=./values.schema.json
image:
  repository: ghcr.io/actualbudget/actual
  pullPolicy: IfNotPresent
  tag: 26.3.0@sha256:eb8bc26f53025e07e464594c12d77c52c4b95840c8dadd9b95c4f0c4660f8ad2
securityContext:
  container:
    readOnlyRootFilesystem: false
    runAsNonRoot: false
    runAsGroup: 0
    runAsUser: 0
workload:
  main:
    podSpec:
      containers:
        main:
          probes:
            liveness:
              type: http
              path: /
            readiness:
              type: http
              path: /
            startup:
              type: http
              path: /
          env: {}
service:
  main:
    ports:
      main:
        port: 10293
        protocol: http
        targetPort: 5006
persistence:
  data:
    enabled: true
    mountPath: /data
