# yaml-language-server: $schema=./values.schema.json
image:
  pullPolicy: IfNotPresent
  repository: docker.io/f0rc3/barcodebuddy
  tag: latest@sha256:17952104b6d2bb13869ad35f67d51f8f7a6eda0f95e765d22a2bf5e6c4ab53d6
persistence:
  config:
    enabled: true
    mountPath: /config

securityContext:
  container:
    readOnlyRootFilesystem: false
    runAsGroup: 0
    runAsUser: 0
service:
  main:
    ports:
      main:
        port: 8450
        protocol: tcp
        targetPort: 80
