# yaml-language-server: $schema=./values.schema.json
image:
  pullPolicy: IfNotPresent
  repository: seaduboi/broadcast-box
  tag: latest@sha256:1d5ec0b0ba79cf3eae652c0b60e37707e43401623a0ab42e8791823bb0298617
service:
  main:
    ports:
      main:
        port: 8080
        protocol: http
        targetPort: 8080
      webrtc:
        enabled: true
        port: 60006
        protocol: udp
        targetPort: 60006
workload:
  main:
    podSpec:
      containers:
        main:
          env:
            NETWORK_TEST_ON_START: false
            INCLUDE_PUBLIC_IP_IN_NAT_1_TO_1_IP: true
            UDP_MUX_PORT: "{{ .Values.service.main.ports.webrtc.port }}"
securityContext:
  container:
    readOnlyRootFilesystem: false
    runAsGroup: 0
    runAsUser: 0
