# yaml-language-server: $schema=./values.schema.json
image:
  pullPolicy: IfNotPresent
  repository: seaduboi/broadcast-box
  tag: latest@sha256:16f381f8f854c8863ea56f71d86613df66503754763cbc4ab45f1812e9328d0e
service:
  main:
    ports:
      main:
        port: 8080
        protocol: http
        targetPort: 8080
      webrtc:
        enabled: true
        port: 60006
        protocol: udp
        targetPort: 60006
workload:
  main:
    podSpec:
      containers:
        main:
          env:
            NETWORK_TEST_ON_START: false
            INCLUDE_PUBLIC_IP_IN_NAT_1_TO_1_IP: true
            UDP_MUX_PORT: "{{ .Values.service.main.ports.webrtc.port }}"
securityContext:
  container:
    readOnlyRootFilesystem: false
    runAsGroup: 0
    runAsUser: 0
