# yaml-language-server: $schema=./values.schema.json

image:
  repository: ghcr.io/itzg/minecraft-server
  tag: 2026.4.2-java25@sha256:13b19d4134d236de47320e937d456b38bbc148db2bbab4a81064a3e71dbe37ad
  pullPolicy: Always

# ---- Java 25 ----
j25jdkImage:
  repository: ghcr.io/itzg/minecraft-server
  tag: 2026.4.2-java25-jdk@sha256:ec37ba8d1862c02a67a0ac0b6674dc7dc8534b3bcdcf59ff1aa065ca931d44ba
  pullPolicy: Always

# ---- Java 21 (Recommended for modern MC versions) ----
j21Image:
  repository: ghcr.io/itzg/minecraft-server
  tag: 2026.4.2-java21@sha256:55d2d31aed9848756c0051dea0b001a36ea0fa2afdce892f1aab0655a6dff87b
  pullPolicy: Always

j21alpineImage:
  repository: ghcr.io/itzg/minecraft-server
  tag: 2026.4.2-java21-alpine@sha256:aa6c211ce486ff1c2e0d169b7d234392fc1586e7cf7e22e3b39135f5fd6e60e9
  pullPolicy: Always

j21jdkImage:
  repository: ghcr.io/itzg/minecraft-server
  tag: 2026.4.2-java21-jdk@sha256:de7cb378034f6c7b8bd16550e895b663e1c364b55edccb6beadb2385952ab384
  pullPolicy: Always

# ---- Java 17 (Safe & Supported) ----
j17Image:
  repository: ghcr.io/itzg/minecraft-server
  tag: 2026.4.2-java17@sha256:dea8184ce4d3c5459ec8aca1fa2acd4215395321ff0817cdf5be8493980700fa
  pullPolicy: Always

j17jdkImage:
  repository: ghcr.io/itzg/minecraft-server
  tag: 2024.6.1-java17-jdk@sha256:2c43fcede436aff9f50b1adf4448d55d221651be471ef41412232c141bfa89f6
  pullPolicy: Always

# ---- Java 16 ----
j16Image:
  repository: ghcr.io/itzg/minecraft-server
  tag: 2026.4.2-java16@sha256:40e7699a657110d004a8df2818beacb69f11ab7b7c889b676c51cfb38f62580f
  pullPolicy: Always

# ---- Java 11 ----
j11Image:
  repository: ghcr.io/itzg/minecraft-server
  tag: 2026.4.2-java11@sha256:6fa6a3c6cfca89daf6293efc86c50fc9d49faa7483780a7ffbfe53bac34b08c2
  pullPolicy: Always

# ---- Java 8 (Use plain java8 only) ----
j8Image:
  repository: ghcr.io/itzg/minecraft-server
  tag: 2026.4.2-java8@sha256:8731baf0f4862c7038ffb8dae002757a22e2650eea4ba74ae24d9bcf6aa59676
  pullPolicy: Always

service:
  main:
    enabled: true
    ports:
      main:
        enabled: true
        protocol: tcp
        port: 25565
      query:
        enabled: true
        protocol: udp
        port: 25565
  rcon:
    enabled: true
    ports:
      rcon:
        enabled: true
        port: 25575
  ssh:
    enabled: true
    ports:
      ssh:
        enabled: true
        protocol: tcp
        targetPort: 2222
        port: 2222

workload:
  main:
    podSpec:
      containers:
        main:
          imageSelector: image
          probes:
            liveness:
              enabled: true
              type: exec
              command:
                - mc-health
            readiness:
              enabled: true
              type: exec
              command:
                - mc-health
            startup:
              enabled: true
              type: exec
              command:
                - mc-health
          env:
            SERVER_PORT: "{{ .Values.service.main.ports.main.port }}"
            QUERY_PORT: "{{ .Values.service.main.ports.query.port }}"
            RCON_PORT: "{{ .Values.service.rcon.ports.rcon.port }}"
            ENABLE_QUERY: "true"
            ENABLE_SSH: "false"
            EULA: "TRUE"
            GUI: "FALSE"
            OVERRIDE_SERVER_PROPERTIES: true
            VERSION: "LATEST"
            TYPE: "VANILLA"
            DIFFICULTY: easy
            MAX_PLAYERS: 20
            MAX_WORLD_SIZE: 10000
            ALLOW_NETHER: true
            ANNOUNCE_PLAYER_ACHIEVEMENTS: true
            ENABLE_COMMAND_BLOCK: false
            FORCE_GAMEMODE: false
            GENERATE_STRUCTURES: true
            HARDCORE: false
            MAX_BUILD_HEIGHT: 256
            MAX_TICK_TIME: 60000
            SPAWN_ANIMALS: true
            SPAWN_MONSTERS: true
            SPAWN_NPCS: true
            VIEW_DISTANCE: 16
            MODE: survival
            MOTD: "Welcome to Minecraft on TrueNAS Scale!"
            PVP: false
            LEVEL_TYPE: DEFAULT
            LEVEL: world
            ONLINE_MODE: true
            MEMORY: 2048M
            RCON_PASSWORD: "secretrconpass"
            # PACKWIZ_URL: ""
            # CUSTOM_SERVER: ""
            # QUILT_LOADER_VERSION: ""
            # QUILT_LAUNCHER: ""
            # QUILT_LAUNCHER_URL: ""
            # PUFFERFISH_BUILD: "lastSuccessfulBuild"
            # FORGEVERSION: ""
            # FORGE_INSTALLER: ""
            # FORGE_INSTALLER_URL: ""
            # FABRIC_LOADER_VERSION: ""
            # FABRIC_INSTALLER: ""
            # FABRIC_INSTALLER_URL: ""
            # SPIGOT_DOWNLOAD_URL: ""
            # BUILD_FROM_SOURCE: false
            # BUKKIT_DOWNLOAD_URL: ""
            # PAPERBUILD: ""
            # PAPER_DOWNLOAD_URL: ""
            # AIRPLANE_BUILD: "lastSuccessfulBuild"
            # MAGMA_CHANNEL: "stable"
            # MOHIST_BUILD: ""
            # CANYON_BUILD: ""
            # SPONGEBRANCH: "STABLE"
            # SPONGEVERSION: ""
            # LIMBO_BUILD: "LATEST"
            # LIMBO_SCHEMA_FILENAME: "default.schem"
            # CRUCIBLE_RELEASE: "latest"
            # FTB_MODPACK_ID: ""
            # FTB_MODPACK_VERSION_ID: ""
            # CF_SERVER_MOD: ""
            # CF_BASE_DIR: ""
            # USE_MODPACK_START_SCRIPT: true
            # FTB_LEGACYJAVAFIXER: false
            # WHITELIST: ""
            # OPS: ""
            # ICON: ""
            # SEED: ""
            # GENERATOR_SETTINGS: ""
            # WORLD: ""
            # FORCE_REDOWNLOAD: false
            # USE_FLARE_FLAGS: false
            # USE_AIKAR_FLAGS: true
            # USE_SIMD_FLAGS: false
            # JVM_OPTS: ""
            # JVM_XX_OPTS: ""
            # CF_API_KEY
            # CF_PAGE_URL
            # CF_SLUG
            # CF_EXCLUDE_INCLUDE_FILE
            # CF_EXCLUDE_MODS
            # CF_FORCE_INCLUDE_MODS
            # CF_FORCE_SYNCHRONIZE
            # CF_OVERRIDES_SKIP_EXISTING
            # CF_PARALLEL_DOWNLOADS
            # CF_SET_LEVEL_FROM

persistence:
  data:
    enabled: true
    mountPath: /data
