# yaml-language-server: $schema=./values.schema.json

image:
  repository: ghcr.io/itzg/minecraft-server
  tag: 2026.7.2-java25@sha256:6ec1110e4d9236d00ae9436a3e4a5929583e5b19cc94b756a7c603f7cf647a77
  pullPolicy: Always

# ---- Java 25 ----
j25jdkImage:
  repository: ghcr.io/itzg/minecraft-server
  tag: 2026.7.2-java25-jdk@sha256:dad24c143e16d03bb6f5e1517f8451f80e82657711d312f2fd52cd0c3023d6d9
  pullPolicy: Always

# ---- Java 21 (Recommended for modern MC versions) ----
j21Image:
  repository: ghcr.io/itzg/minecraft-server
  tag: 2026.7.2-java21@sha256:7f69fd6688e03495c8a8f5a46e8a8e82001b4465f4b55bdcd024c02c3624d8c8
  pullPolicy: Always

j21alpineImage:
  repository: ghcr.io/itzg/minecraft-server
  tag: 2026.7.2-java21-alpine@sha256:34668aa8ff83368de484200c8f19af9f7f776dc988778b7755c57627c45b3d0b
  pullPolicy: Always

j21jdkImage:
  repository: ghcr.io/itzg/minecraft-server
  tag: 2026.7.2-java21-jdk@sha256:5fa9a3be8e50c550fe9225acb1b66f31e7d15cb85e95c9e9e198bd0779a0f1e3
  pullPolicy: Always

# ---- Java 17 (Safe & Supported) ----
j17Image:
  repository: ghcr.io/itzg/minecraft-server
  tag: 2026.7.2-java17@sha256:6cc2fc4f1ad839a70feebb300202bbc45ad9ddfa863aba95eadf63ab97e4c01d
  pullPolicy: Always

j17jdkImage:
  repository: ghcr.io/itzg/minecraft-server
  tag: 2024.6.1-java17-jdk@sha256:2c43fcede436aff9f50b1adf4448d55d221651be471ef41412232c141bfa89f6
  pullPolicy: Always

# ---- Java 16 ----
j16Image:
  repository: ghcr.io/itzg/minecraft-server
  tag: 2026.7.2-java16@sha256:7c28aa3274484c464c09ff78153f472f1ec1c6d25b39f97d57dc0ed3a26e53eb
  pullPolicy: Always

# ---- Java 11 ----
j11Image:
  repository: ghcr.io/itzg/minecraft-server
  tag: 2026.7.2-java11@sha256:14303733ce0c00e549fe9c9d8ab1e304964d38bd6d508303bcc724b4ad36be38
  pullPolicy: Always

# ---- Java 8 (Use plain java8 only) ----
j8Image:
  repository: ghcr.io/itzg/minecraft-server
  tag: 2026.7.2-java8@sha256:ab1c496da24182ebb29c4d28c1590497c9b3738e3d6a04a27569992cf0e2c80d
  pullPolicy: Always

service:
  main:
    enabled: true
    ports:
      main:
        enabled: true
        protocol: tcp
        port: 25565
      query:
        enabled: true
        protocol: udp
        port: 25565
  rcon:
    enabled: true
    ports:
      rcon:
        enabled: true
        port: 25575
  ssh:
    enabled: true
    ports:
      ssh:
        enabled: true
        protocol: tcp
        targetPort: 2222
        port: 2222

workload:
  main:
    podSpec:
      containers:
        main:
          imageSelector: image
          probes:
            liveness:
              enabled: true
              type: exec
              command:
                - mc-health
            readiness:
              enabled: true
              type: exec
              command:
                - mc-health
            startup:
              enabled: true
              type: exec
              command:
                - mc-health
          env:
            SERVER_PORT: "{{ .Values.service.main.ports.main.port }}"
            QUERY_PORT: "{{ .Values.service.main.ports.query.port }}"
            RCON_PORT: "{{ .Values.service.rcon.ports.rcon.port }}"
            ENABLE_QUERY: "true"
            ENABLE_SSH: "false"
            EULA: "TRUE"
            GUI: "FALSE"
            OVERRIDE_SERVER_PROPERTIES: true
            VERSION: "LATEST"
            TYPE: "VANILLA"
            DIFFICULTY: easy
            MAX_PLAYERS: 20
            MAX_WORLD_SIZE: 10000
            ALLOW_NETHER: true
            ANNOUNCE_PLAYER_ACHIEVEMENTS: true
            ENABLE_COMMAND_BLOCK: false
            FORCE_GAMEMODE: false
            GENERATE_STRUCTURES: true
            HARDCORE: false
            MAX_BUILD_HEIGHT: 256
            MAX_TICK_TIME: 60000
            SPAWN_ANIMALS: true
            SPAWN_MONSTERS: true
            SPAWN_NPCS: true
            VIEW_DISTANCE: 16
            MODE: survival
            MOTD: "Welcome to Minecraft on TrueNAS Scale!"
            PVP: false
            LEVEL_TYPE: DEFAULT
            LEVEL: world
            ONLINE_MODE: true
            MEMORY: 2048M
            RCON_PASSWORD: "secretrconpass"
            # PACKWIZ_URL: ""
            # CUSTOM_SERVER: ""
            # QUILT_LOADER_VERSION: ""
            # QUILT_LAUNCHER: ""
            # QUILT_LAUNCHER_URL: ""
            # PUFFERFISH_BUILD: "lastSuccessfulBuild"
            # FORGEVERSION: ""
            # FORGE_INSTALLER: ""
            # FORGE_INSTALLER_URL: ""
            # FABRIC_LOADER_VERSION: ""
            # FABRIC_INSTALLER: ""
            # FABRIC_INSTALLER_URL: ""
            # SPIGOT_DOWNLOAD_URL: ""
            # BUILD_FROM_SOURCE: false
            # BUKKIT_DOWNLOAD_URL: ""
            # PAPERBUILD: ""
            # PAPER_DOWNLOAD_URL: ""
            # AIRPLANE_BUILD: "lastSuccessfulBuild"
            # MAGMA_CHANNEL: "stable"
            # MOHIST_BUILD: ""
            # CANYON_BUILD: ""
            # SPONGEBRANCH: "STABLE"
            # SPONGEVERSION: ""
            # LIMBO_BUILD: "LATEST"
            # LIMBO_SCHEMA_FILENAME: "default.schem"
            # CRUCIBLE_RELEASE: "latest"
            # FTB_MODPACK_ID: ""
            # FTB_MODPACK_VERSION_ID: ""
            # CF_SERVER_MOD: ""
            # CF_BASE_DIR: ""
            # USE_MODPACK_START_SCRIPT: true
            # FTB_LEGACYJAVAFIXER: false
            # WHITELIST: ""
            # OPS: ""
            # ICON: ""
            # SEED: ""
            # GENERATOR_SETTINGS: ""
            # WORLD: ""
            # FORCE_REDOWNLOAD: false
            # USE_FLARE_FLAGS: false
            # USE_AIKAR_FLAGS: true
            # USE_SIMD_FLAGS: false
            # JVM_OPTS: ""
            # JVM_XX_OPTS: ""
            # CF_API_KEY
            # CF_PAGE_URL
            # CF_SLUG
            # CF_EXCLUDE_INCLUDE_FILE
            # CF_EXCLUDE_MODS
            # CF_FORCE_INCLUDE_MODS
            # CF_FORCE_SYNCHRONIZE
            # CF_OVERRIDES_SKIP_EXISTING
            # CF_PARALLEL_DOWNLOADS
            # CF_SET_LEVEL_FROM

persistence:
  data:
    enabled: true
    mountPath: /data
