# yaml-language-server: $schema=./values.schema.json

image:
  repository: ghcr.io/itzg/minecraft-server
  tag: 2026.4.1-java25@sha256:1544b0bd94b2734a5b12cb38e73751cc5dee4d7f6ab5b751afcb6ecc4b8f1460
  pullPolicy: Always

# ---- Java 25 ----
j25jdkImage:
  repository: ghcr.io/itzg/minecraft-server
  tag: 2026.4.1-java25-jdk@sha256:e7219d479e8ecbab3ed5a3485d2fefb97114e6e48eababf6616cb03960ab9adc
  pullPolicy: Always

# ---- Java 21 (Recommended for modern MC versions) ----
j21Image:
  repository: ghcr.io/itzg/minecraft-server
  tag: 2026.4.1-java21@sha256:4e425ce4f3a0cbf8b2c33d798ac1e7b59e8637b7a64272de7c810025aa11913a
  pullPolicy: Always

j21alpineImage:
  repository: ghcr.io/itzg/minecraft-server
  tag: 2026.4.1-java21-alpine@sha256:6acc035e2965efd267f81ad27cac8509b50052feff113ed2e47c87cf3fb62068
  pullPolicy: Always

j21jdkImage:
  repository: ghcr.io/itzg/minecraft-server
  tag: 2026.4.1-java21-jdk@sha256:c57873f3eabc910c72bfd11f0311746bf740111d8425edb4a726e651460704f3
  pullPolicy: Always

# ---- Java 17 (Safe & Supported) ----
j17Image:
  repository: ghcr.io/itzg/minecraft-server
  tag: 2026.4.1-java17@sha256:5cc640a32d042f5e07e2fb381c0351aac3cf82bf512afa408240bde5c2358899
  pullPolicy: Always

j17jdkImage:
  repository: ghcr.io/itzg/minecraft-server
  tag: 2024.6.1-java17-jdk@sha256:2c43fcede436aff9f50b1adf4448d55d221651be471ef41412232c141bfa89f6
  pullPolicy: Always

# ---- Java 16 ----
j16Image:
  repository: ghcr.io/itzg/minecraft-server
  tag: 2026.4.1-java16@sha256:7acaf091bbb6d48f2a3dd14e6d4976040ca3f9070acb37c0db60d272ab69aaa2
  pullPolicy: Always

# ---- Java 11 ----
j11Image:
  repository: ghcr.io/itzg/minecraft-server
  tag: 2026.4.1-java11@sha256:b5e78ae26622b290cfd45446472e6b34c031048faa1361f6a59a857d120718f8
  pullPolicy: Always

# ---- Java 8 (Use plain java8 only) ----
j8Image:
  repository: ghcr.io/itzg/minecraft-server
  tag: 2026.4.1-java8@sha256:23b762c388abb7b4bea6529646577ca3126f4db7f93ebc3b34043eda9e235d84
  pullPolicy: Always

service:
  main:
    enabled: true
    ports:
      main:
        enabled: true
        protocol: tcp
        port: 25565
      query:
        enabled: true
        protocol: udp
        port: 25565
  rcon:
    enabled: true
    ports:
      rcon:
        enabled: true
        port: 25575
  ssh:
    enabled: true
    ports:
      ssh:
        enabled: true
        protocol: tcp
        targetPort: 2222
        port: 2222

workload:
  main:
    podSpec:
      containers:
        main:
          imageSelector: image
          probes:
            liveness:
              enabled: true
              type: exec
              command:
                - mc-health
            readiness:
              enabled: true
              type: exec
              command:
                - mc-health
            startup:
              enabled: true
              type: exec
              command:
                - mc-health
          env:
            SERVER_PORT: "{{ .Values.service.main.ports.main.port }}"
            QUERY_PORT: "{{ .Values.service.main.ports.query.port }}"
            RCON_PORT: "{{ .Values.service.rcon.ports.rcon.port }}"
            ENABLE_QUERY: "true"
            ENABLE_SSH: "false"
            EULA: "TRUE"
            GUI: "FALSE"
            OVERRIDE_SERVER_PROPERTIES: true
            VERSION: "LATEST"
            TYPE: "VANILLA"
            DIFFICULTY: easy
            MAX_PLAYERS: 20
            MAX_WORLD_SIZE: 10000
            ALLOW_NETHER: true
            ANNOUNCE_PLAYER_ACHIEVEMENTS: true
            ENABLE_COMMAND_BLOCK: false
            FORCE_GAMEMODE: false
            GENERATE_STRUCTURES: true
            HARDCORE: false
            MAX_BUILD_HEIGHT: 256
            MAX_TICK_TIME: 60000
            SPAWN_ANIMALS: true
            SPAWN_MONSTERS: true
            SPAWN_NPCS: true
            VIEW_DISTANCE: 16
            MODE: survival
            MOTD: "Welcome to Minecraft on TrueNAS Scale!"
            PVP: false
            LEVEL_TYPE: DEFAULT
            LEVEL: world
            ONLINE_MODE: true
            MEMORY: 2048M
            RCON_PASSWORD: "secretrconpass"
            # PACKWIZ_URL: ""
            # CUSTOM_SERVER: ""
            # QUILT_LOADER_VERSION: ""
            # QUILT_LAUNCHER: ""
            # QUILT_LAUNCHER_URL: ""
            # PUFFERFISH_BUILD: "lastSuccessfulBuild"
            # FORGEVERSION: ""
            # FORGE_INSTALLER: ""
            # FORGE_INSTALLER_URL: ""
            # FABRIC_LOADER_VERSION: ""
            # FABRIC_INSTALLER: ""
            # FABRIC_INSTALLER_URL: ""
            # SPIGOT_DOWNLOAD_URL: ""
            # BUILD_FROM_SOURCE: false
            # BUKKIT_DOWNLOAD_URL: ""
            # PAPERBUILD: ""
            # PAPER_DOWNLOAD_URL: ""
            # AIRPLANE_BUILD: "lastSuccessfulBuild"
            # MAGMA_CHANNEL: "stable"
            # MOHIST_BUILD: ""
            # CANYON_BUILD: ""
            # SPONGEBRANCH: "STABLE"
            # SPONGEVERSION: ""
            # LIMBO_BUILD: "LATEST"
            # LIMBO_SCHEMA_FILENAME: "default.schem"
            # CRUCIBLE_RELEASE: "latest"
            # FTB_MODPACK_ID: ""
            # FTB_MODPACK_VERSION_ID: ""
            # CF_SERVER_MOD: ""
            # CF_BASE_DIR: ""
            # USE_MODPACK_START_SCRIPT: true
            # FTB_LEGACYJAVAFIXER: false
            # WHITELIST: ""
            # OPS: ""
            # ICON: ""
            # SEED: ""
            # GENERATOR_SETTINGS: ""
            # WORLD: ""
            # FORCE_REDOWNLOAD: false
            # USE_FLARE_FLAGS: false
            # USE_AIKAR_FLAGS: true
            # USE_SIMD_FLAGS: false
            # JVM_OPTS: ""
            # JVM_XX_OPTS: ""
            # CF_API_KEY
            # CF_PAGE_URL
            # CF_SLUG
            # CF_EXCLUDE_INCLUDE_FILE
            # CF_EXCLUDE_MODS
            # CF_FORCE_INCLUDE_MODS
            # CF_FORCE_SYNCHRONIZE
            # CF_OVERRIDES_SKIP_EXISTING
            # CF_PARALLEL_DOWNLOADS
            # CF_SET_LEVEL_FROM

persistence:
  data:
    enabled: true
    mountPath: /data
