# yaml-language-server: $schema=./values.schema.json
image:
  repository: docker.io/shlinkio/shlink-web-client
  pullPolicy: IfNotPresent
  tag: 4.8.0@sha256:ec804a7f9dc8d5f64615c780106d4d954ec81648dc2a1393442c68da8e48e102
service:
  main:
    ports:
      main:
        targetPort: 8080
        port: 10154
        protocol: http

securityContext:
  container:
    readOnlyRootFilesystem: false
    runAsNonRoot: false
    runAsUser: 0
    runAsGroup: 0
workload:
  main:
    podSpec:
      containers:
        main:
          env:
            SHLINK_SERVER_URL: ""
            SHLINK_SERVER_API_KEY: ""
            SHLINK_SERVER_NAME: ""
