# yaml-language-server: $schema=./values.schema.json
image:
  repository: docker.io/shlinkio/shlink-web-client
  pullPolicy: IfNotPresent
  tag: 4.8.1@sha256:dc8bf3565a25bd0602ff11ee352920830ce457ab58a2b2c62f2ebb23e8c8b9ee
service:
  main:
    ports:
      main:
        targetPort: 8080
        port: 10154
        protocol: http

securityContext:
  container:
    readOnlyRootFilesystem: false
    runAsNonRoot: false
    runAsUser: 0
    runAsGroup: 0
workload:
  main:
    podSpec:
      containers:
        main:
          env:
            SHLINK_SERVER_URL: ""
            SHLINK_SERVER_API_KEY: ""
            SHLINK_SERVER_NAME: ""
