# yaml-language-server: $schema=./values.schema.json
image:
  pullPolicy: IfNotPresent
  repository: chronograf
  tag: latest@sha256:71af79eb1d102ee2dc2d051f5c4977a867774bfb25ec7412ef9923b281349766
persistence:
  chronograf:
    enabled: true
    mountPath: /var/lib/chronograf

securityContext:
  container:
    readOnlyRootFilesystem: false
    runAsGroup: 0
    runAsUser: 0
service:
  main:
    ports:
      main:
        port: 8888
        protocol: tcp
        targetPort: 8888
