# yaml-language-server: $schema=./values.schema.json
image:
  pullPolicy: IfNotPresent
  repository: chronograf
  tag: latest@sha256:d40aa30936e76a9d77532e9a00382b998eb937370fbe440c274ed20fe158d9aa
persistence:
  chronograf:
    enabled: true
    mountPath: /var/lib/chronograf

securityContext:
  container:
    readOnlyRootFilesystem: false
    runAsGroup: 0
    runAsUser: 0
service:
  main:
    ports:
      main:
        port: 8888
        protocol: tcp
        targetPort: 8888
