# yaml-language-server: $schema=./values.schema.json
image:
  pullPolicy: IfNotPresent
  repository: chronograf
  tag: latest@sha256:1aa585346868ef0859c507b2c8544a175ad308024765929f5df5b64a9679031d
persistence:
  chronograf:
    enabled: true
    mountPath: /var/lib/chronograf

securityContext:
  container:
    readOnlyRootFilesystem: false
    runAsGroup: 0
    runAsUser: 0
service:
  main:
    ports:
      main:
        port: 8888
        protocol: tcp
        targetPort: 8888
