# yaml-language-server: $schema=./values.schema.json
image:
  repository: oci.trueforge.org/containerforge/ubuntu
  tag: 26.04@sha256:ea16b55109312b5eda59cf3cdd576c10979b7532e0a9561de068b9679794ea33
  pullPolicy: IfNotPresent
service:
  main:
    ports:
      main:
        port: 10107
        targetPort: 10107
  api:
    enabled: true
    ports:
      api:
        enabled: true
        targetPort: 10106
        port: 10106
ingress:
  api:
    enabled: false
    targetSelector:
      api: api
persistence:
  config:
    enabled: true
    mountPath: "/data"

securityContext:
  container:
    readOnlyRootFilesystem: false
workload:
  main:
    podSpec:
      containers:
        main:
          probes:
            liveness:
              custom: true
              spec:
                httpGet:
                  scheme: HTTP
                  path: "/minio/health/live"
                  port: 10106
            readiness:
              custom: true
              spec:
                httpGet:
                  scheme: HTTP
                  path: "/minio/health/ready"
                  port: 10106
          args:
            - "server"
            - "/data"
            - "--address"
            - ":10106"
            - "--console-address"
            - ":10107"
          env:
            MINIO_ROOT_USER: "minio"
            MINIO_BROWSER_REDIRECT_URL: ""
            MINIO_SERVER_URL: ""
            MINIO_ROOT_PASSWORD: "changeme"
