# yaml-language-server: $schema=./values.schema.json
image:
  repository: ghcr.io/linuxserver/duckdns
  pullPolicy: IfNotPresent
  tag: latest@sha256:7edcc8555ecbca2ea6e441290a09d172bc531debce7c6771c14551838a3f67f2
securityContext:
  container:
    runAsNonRoot: false
    readOnlyRootFilesystem: false
    runAsUser: 0
    runAsGroup: 0
service:
  main:
    enabled: false
    ports:
      main:
        enabled: false
workload:
  main:
    podSpec:
      containers:
        main:
          probes:
            liveness:
              enabled: false
            readiness:
              enabled: false
            startup:
              enabled: false
          env:
            SUBDOMAINS: ""
            LOG_FILE: false
            TOKEN: ""
persistence:
  config:
    enabled: true
    mountPath: /config
