# yaml-language-server: $schema=./values.schema.json
image:
  repository: ghcr.io/linuxserver/duckdns
  pullPolicy: IfNotPresent
  tag: latest@sha256:79c6ed0240c96fdc01013048e6f76a0eb0cac504d5f0739ca6a6875246aa6f26
securityContext:
  container:
    runAsNonRoot: false
    readOnlyRootFilesystem: false
    runAsUser: 0
    runAsGroup: 0
service:
  main:
    enabled: false
    ports:
      main:
        enabled: false
workload:
  main:
    podSpec:
      containers:
        main:
          probes:
            liveness:
              enabled: false
            readiness:
              enabled: false
            startup:
              enabled: false
          env:
            SUBDOMAINS: ""
            LOG_FILE: false
            TOKEN: ""
persistence:
  config:
    enabled: true
    mountPath: /config
