# yaml-language-server: $schema=./values.schema.json
image:
  repository: ghcr.io/linuxserver/duckdns
  pullPolicy: IfNotPresent
  tag: latest@sha256:13ab71bf3fd9f785be05dcb069727c9e0a9a08a6f8a3bd00b5279aa1e055c3d6
securityContext:
  container:
    runAsNonRoot: false
    readOnlyRootFilesystem: false
    runAsUser: 0
    runAsGroup: 0
service:
  main:
    enabled: false
    ports:
      main:
        enabled: false
workload:
  main:
    podSpec:
      containers:
        main:
          probes:
            liveness:
              enabled: false
            readiness:
              enabled: false
            startup:
              enabled: false
          env:
            SUBDOMAINS: ""
            LOG_FILE: false
            TOKEN: ""
persistence:
  config:
    enabled: true
    mountPath: /config
