# yaml-language-server: $schema=./values.schema.json
image:
  repository: docker.io/aeonlucid/impostor
  pullPolicy: IfNotPresent
  tag: v1.10.9@sha256:a3caaf5119b2ea73559f6323cd0f008fb4e87b946b7205d920418692b28f7f32
nightlyImage:
  repository: docker.io/aeonlucid/impostor
  tag: nightly@sha256:63d1187e3057b7dd66bf5c9bab34b73fcb051f0323b0282958dc9f0b9e7b1fed
  pullPolicy: IfNotPresent
service:
  main:
    ports:
      main:
        protocol: udp
        port: 22023
        targetPort: 22023

workload:
  main:
    podSpec:
      containers:
        main:
          imageSelector: image
          probes:
            liveness:
              enabled: false
            readiness:
              enabled: false
            startup:
              enabled: false
          env:
            IMPOSTOR_Server__PublicIp: "127.0.0.1"
            IMPOSTOR_Server__ListenIp: "0.0.0.0"
            IMPOSTOR_AntiCheat__Enabled: true
            IMPOSTOR_AntiCheat__BanIpFromGame: true
            IMPOSTOR_Debug__GameRecorderEnabled: false
            IMPOSTOR_Debug__GameRecorderPath: ""
updated: true
