# yaml-language-server: $schema=./values.schema.json
image:
  repository: docker.io/aeonlucid/impostor
  pullPolicy: IfNotPresent
  tag: v1.10.6@sha256:6014c28057a6f914af17ec95e7f00d86bd43a3865424f1d8386319756dcb588c
nightlyImage:
  repository: docker.io/aeonlucid/impostor
  tag: nightly@sha256:c3118149f1fdd6a40a3db501f9447adc719feaa6e8927e7a3dc12bedecd124f5
  pullPolicy: IfNotPresent
service:
  main:
    ports:
      main:
        protocol: udp
        port: 22023
        targetPort: 22023

workload:
  main:
    podSpec:
      containers:
        main:
          imageSelector: image
          probes:
            liveness:
              enabled: false
            readiness:
              enabled: false
            startup:
              enabled: false
          env:
            IMPOSTOR_Server__PublicIp: "127.0.0.1"
            IMPOSTOR_Server__ListenIp: "0.0.0.0"
            IMPOSTOR_AntiCheat__Enabled: true
            IMPOSTOR_AntiCheat__BanIpFromGame: true
            IMPOSTOR_Debug__GameRecorderEnabled: false
            IMPOSTOR_Debug__GameRecorderPath: ""
updated: true
