# yaml-language-server: $schema=./values.schema.json
image:
  pullPolicy: IfNotPresent
  repository: docker.io/kylemanna/bitcoind
  tag: latest@sha256:86bbcaa99bf3bf3d5df7fd6d9217b3a41194db4c4e34385064f2cfc9fa7bdf91
persistence:
  blockhainstorage:
    enabled: true
    mountPath: /bitcoin/.bitcoin

securityContext:
  container:
    readOnlyRootFilesystem: false
    runAsGroup: 0
    runAsUser: 0
service:
  main:
    ports:
      main:
        port: 8332
        protocol: tcp
        targetPort: 8332
  port2:
    enabled: true
    ports:
      port2:
        enabled: true
        port: 8333
        protocol: tcp
        targetPort: 8333
