# yaml-language-server: $schema=./values.schema.json
image:
  repository: oci.trueforge.org/containerforge/deluge
  pullPolicy: IfNotPresent
  tag: "2.2.0@sha256:537e5a390e15b91fe2b90caf491432ac2de3aac3218ffcd2b64260493cf92433"
service:
  main:
    ports:
      main:
        port: 8112
        targetPort: 58846
  rpc:
    enabled: true
    ports:
      rpc:
        enabled: true
        port: 58846
        targetPort: 58846
  torrent:
    enabled: true
    ports:
      tcp:
        enabled: true
        port: 6881
        targetPort: 6881
      udp:
        enabled: true
        port: "{{ .Values.service.torrent.ports.tcp.port }}"
        targetPort: "{{ .Values.service.torrent.ports.tcp.targetPort }}"
        protocol: udp
persistence:
  config:
    enabled: true
    mountPath: /config
