# yaml-language-server: $schema=./values.schema.json
image:
  repository: docker.io/601096721/mosdns
  pullPolicy: IfNotPresent
  tag: v5.3.4@sha256:58b5a34a868210b6317d8915b687d7758e1d7061f3598845522d02e3f0d72042
service:
  main:
    ports:
      main:
        targetPort: 53
        port: 53
      dns-upd:
        enabled: true
        protocol: udp
        targetPort: 53
        port: 53
persistence:
  data:
    enabled: true
    mountPath: "/etc/mosdns"

securityContext:
  container:
    readOnlyRootFilesystem: false
    runAsNonRoot: false
    runAsUser: 0
    runAsGroup: 0
workload:
  main:
    podSpec:
      containers:
        main:
          probes:
            liveness:
              type: tcp
            readiness:
              type: tcp
            startup:
              type: tcp
