# yaml-language-server: $schema=./values.schema.json
image:
  repository: oci.trueforge.org/containerforge/mariadb
  pullPolicy: IfNotPresent
  tag: 11.4.8-r0
workload:
  main:
    podSpec:
      containers:
        main:
          env:
            MYSQL_PASSWORD: "{{ .Values.password }}"
            MYSQL_ROOT_PASSWORD: "{{ .Values.rootPassword }}"
            MYSQL_USER: "{{ .Values.mariadbUsername }}"
            MYSQL_DATABASE: "{{ .Values.mariadbDatabase }}"
            MARIADB_EXTRA_FLAGS: "--init-file=/init/passinit.sql"
          probes:
            liveness:
              enabled: true
              type: tcp
              port: "{{ .Values.service.main.ports.main.port }}"
            readiness:
              enabled: true
              type: tcp
              port: "{{ .Values.service.main.ports.main.port }}"
            startup:
              enabled: true
              type: tcp
              port: "{{ .Values.service.main.ports.main.port }}"
service:
  main:
    ports:
      main:
        port: 3306
        targetPort: 3306
securityContext:
  container:
    readOnlyRootFilesystem: false
    runAsGroup: 0
persistence:
  data:
    enabled: true
    mountPath: "/config"
  passinit:
    enabled: true
    type: configmap
    objectName: passinit
    items:
      - key: passinit.sql
        path: passinit.sql
    targetSelector:
      main:
        main:
          subPath: passinit.sql
          mountPath: /init/passinit.sql

configmap:
  passinit:
    enabled: true
    data:
      passinit.sql: |
        ALTER USER root@'%' IDENTIFIED VIA mysql_native_password USING PASSWORD("{{ .Values.rootPassword }}");
        ALTER USER {{ .Values.mariadbUsername }}@'%' IDENTIFIED VIA mysql_native_password USING PASSWORD("{{ .Values.password }}");
        FLUSH PRIVILEGES;

mariadbUsername: "test"
mariadbDatabase: "test"
## DEVNOTE: These password defaults always need to match common
rootPassword: "PLACEHOLDERROOTPASSWORD"
password: "PLACEHOLDERPASSWORD"
