# yaml-language-server: $schema=./values.schema.json
image:
  pullPolicy: IfNotPresent
  repository: docker.io/tracksapp/tracks
  tag: latest@sha256:dd0d3aab5c843368637a6bb7c1fe144776a2b1c490c4d9020fc350fbf8fcb16f
persistence: {}

securityContext:
  container:
    readOnlyRootFilesystem: false
    runAsGroup: 0
    runAsUser: 0
service:
  main:
    ports:
      main:
        port: 3000
        protocol: tcp
        targetPort: 3000
workload:
  main:
    podSpec:
      containers:
        main:
          env:
            BUNDLE_WITHOUT: ""
            DATABASE_ENCODING: utf8
            DATABASE_HOST: 10.0.0.10
            DATABASE_NAME: tracks
            DATABASE_PASSWORD: password
            DATABASE_PORT: "3306"
            DATABASE_TYPE: mysql2
            DATABASE_USERNAME: tracks
            RAILS_ENV: production
