# yaml-language-server: $schema=./values.schema.json
image:
  pullPolicy: IfNotPresent
  repository: docker.io/tracksapp/tracks
  tag: latest@sha256:8862cb910e2e6b91bef183f8446818f79bf83e16fabc049f617cb0d8fc75483f
persistence: {}

securityContext:
  container:
    readOnlyRootFilesystem: false
    runAsGroup: 0
    runAsUser: 0
service:
  main:
    ports:
      main:
        port: 3000
        protocol: tcp
        targetPort: 3000
workload:
  main:
    podSpec:
      containers:
        main:
          env:
            BUNDLE_WITHOUT: ""
            DATABASE_ENCODING: utf8
            DATABASE_HOST: 10.0.0.10
            DATABASE_NAME: tracks
            DATABASE_PASSWORD: password
            DATABASE_PORT: "3306"
            DATABASE_TYPE: mysql2
            DATABASE_USERNAME: tracks
            RAILS_ENV: production
