# yaml-language-server: $schema=./values.schema.json
image:
  repository: oci.trueforge.org/containerforge/duplicati
  tag: 2.3.0@sha256:2d069b78bf3f2c9d928ba1eb7c40c61022a1176ae7920b3a40d65449db7e2d92
  pullPolicy: IfNotPresent
service:
  main:
    ports:
      main:
        port: 8200
        targetPort: 8200
workload:
  main:
    podSpec:
      containers:
        main:
          probes:
            liveness:
              type: http
              path: /
            readiness:
              type: http
              path: /
            startup:
              type: http
              path: /
          env:
            DUPLICATI__WEBSERVICE_PASSWORD: "SuperSecretPassword"
            SETTINGS_ENCRYPTION_KEY: "real_encryption_key"
            # DOTNET_SYSTEM_IO_DISABLEFILELOCKING: true

persistence:
  config:
    enabled: true
    mountPath: /data
