# yaml-language-server: $schema=./values.schema.json
image:
  repository: oci.trueforge.org/containerforge/duplicati
  tag: 2.2.0@sha256:29db1dcb65a8936dd9fede045a30490a7840a5ab6dbb65a9f5a99db3b5686f86
  pullPolicy: IfNotPresent
service:
  main:
    ports:
      main:
        port: 8200
        targetPort: 8200
workload:
  main:
    podSpec:
      containers:
        main:
          probes:
            liveness:
              type: http
              path: /
            readiness:
              type: http
              path: /
            startup:
              type: http
              path: /
          env:
            DUPLICATI__WEBSERVICE_PASSWORD: "SuperSecretPassword"
            SETTINGS_ENCRYPTION_KEY: "real_encryption_key"
            # DOTNET_SYSTEM_IO_DISABLEFILELOCKING: true

persistence:
  config:
    enabled: true
    mountPath: /data
