# yaml-language-server: $schema=./values.schema.json
image:
  repository: docker.io/deluan/navidrome
  pullPolicy: IfNotPresent
  tag: 0.63.1@sha256:7c43af9f651654e97278be871705aae85a4ee0fa4b310337989699a8ada9b3ed
workload:
  main:
    podSpec:
      containers:
        main:
          env:
            ND_MUSICFOLDER: /music
            ND_SCANNER_SCHEDULE: "@every 15m"
            ND_LOGLEVEL: info
            ND_SESSIONTIMEOUT: 24h
            ND_ENABLETRANSCODINGCONFIG: false
service:
  main:
    ports:
      main:
        port: 4533
        targetPort: 4533
persistence:
  data:
    enabled: true
    mountPath: /data
  music:
    enabled: true
    mountPath: /music
