# yaml-language-server: $schema=./values.schema.json
image:
  repository: docker.io/deluan/navidrome
  pullPolicy: IfNotPresent
  tag: 0.63.2@sha256:9012939114fbb1bb641b81cf96dec5ded15f0aafefe8d47a511d7cb919658e40
workload:
  main:
    podSpec:
      containers:
        main:
          env:
            ND_MUSICFOLDER: /music
            ND_SCANNER_SCHEDULE: "@every 15m"
            ND_LOGLEVEL: info
            ND_SESSIONTIMEOUT: 24h
            ND_ENABLETRANSCODINGCONFIG: false
service:
  main:
    ports:
      main:
        port: 4533
        targetPort: 4533
persistence:
  data:
    enabled: true
    mountPath: /data
  music:
    enabled: true
    mountPath: /music
