# yaml-language-server: $schema=./values.schema.json
image:
  repository: docker.io/deluan/navidrome
  pullPolicy: IfNotPresent
  tag: 0.63.0@sha256:60080f8f7bfa039348820852a7f06a5615a0bb4f83bfe541e57cbb0a8650ec9e
workload:
  main:
    podSpec:
      containers:
        main:
          env:
            ND_MUSICFOLDER: /music
            ND_SCANNER_SCHEDULE: "@every 15m"
            ND_LOGLEVEL: info
            ND_SESSIONTIMEOUT: 24h
            ND_ENABLETRANSCODINGCONFIG: false
service:
  main:
    ports:
      main:
        port: 4533
        targetPort: 4533
persistence:
  data:
    enabled: true
    mountPath: /data
  music:
    enabled: true
    mountPath: /music
