# yaml-language-server: $schema=./values.schema.json
image:
  pullPolicy: IfNotPresent
  repository: docker.io/nroi/flexo
  tag: 1.6.12@sha256:760afe7716d41f61f13896f86098cee0844b5599bc45c44d301ca95c852d4e6e

service:
  main:
    ports:
      main:
        port: 7878
        protocol: http
persistence:
  data:
    enabled: true
    type: "emptyDir"
    size: 10Gi
    mountPath: "/var/cache/flexo"
workload:
  main:
    podSpec:
      containers:
        main:
          probes:
            liveness:
              path: "/metrics"
            readiness:
              path: "/metrics"
            startup:
              path: "/metrics"
          env:
            FLEXO_LISTEN_IP_ADDRESS: "0.0.0.0"
            FLEXO_PORT: "{{ .Values.service.main.ports.main.port }}"
