# yaml-language-server: $schema=./values.schema.json
image:
  pullPolicy: IfNotPresent
  repository: docker.io/nroi/flexo
  tag: 1.6.13@sha256:fb53ab1a0aa491a62ae164a5fceea316de465d5284b2b7cb1ffde12ee653ce21

service:
  main:
    ports:
      main:
        port: 7878
        protocol: http
persistence:
  data:
    enabled: true
    type: "emptyDir"
    size: 10Gi
    mountPath: "/var/cache/flexo"
workload:
  main:
    podSpec:
      containers:
        main:
          probes:
            liveness:
              path: "/metrics"
            readiness:
              path: "/metrics"
            startup:
              path: "/metrics"
          env:
            FLEXO_LISTEN_IP_ADDRESS: "0.0.0.0"
            FLEXO_PORT: "{{ .Values.service.main.ports.main.port }}"
