# yaml-language-server: $schema=./values.schema.json
image:
  pullPolicy: IfNotPresent
  repository: docker.io/nroi/flexo
  tag: 1.6.11@sha256:8d70a54f73e3a6d18b3cbfb4a0d781535f4d2ca0628fe929feba029a0bc4c3a4

service:
  main:
    ports:
      main:
        port: 7878
        protocol: http
persistence:
  data:
    enabled: true
    type: "emptyDir"
    size: 10Gi
    mountPath: "/var/cache/flexo"
workload:
  main:
    podSpec:
      containers:
        main:
          probes:
            liveness:
              path: "/metrics"
            readiness:
              path: "/metrics"
            startup:
              path: "/metrics"
          env:
            FLEXO_LISTEN_IP_ADDRESS: "0.0.0.0"
            FLEXO_PORT: "{{ .Values.service.main.ports.main.port }}"
