annotations:
  artifacthub.io/links: |-
    - name: support
    url: https://discord.com/invite/tVsPTHWTtr
  truecharts.org/train: stable
  trueforge.org/category: media
  trueforge.org/max_helm_version: "4.1"
  trueforge.org/max_kubernetes_version: 1.35.0
  trueforge.org/min_helm_version: "3.14"
  trueforge.org/train: stable
apiVersion: v2
appVersion: 0.18.0
dependencies:
  - name: common
    version: 29.21.3
    repository: oci://oci.trueforge.org/truecharts
    condition: ""
    alias: ""
    tags: []
    import-values: []
deprecated: false
description: Self-hosted file converter.
home: https://truecharts.org/charts/stable/convertx
icon: https://truecharts.org/img/hotlink-ok/chart-icons/convertx.webp
keywords:
  - convertx
  - media
kubeVersion: '>=1.33.0-0'
maintainers:
  - name: TrueCharts
    email: info@truecharts.org
    url: https://truecharts.org
name: convertx
sources:
  - https://ghcr.io/c4illin/convertx
  - https://github.com/c4illin/ConvertX
  - https://github.com/trueforge-org/truecharts/tree/master/charts/stable/convertx
type: application
version: 1.1.0

