# yaml-language-server: $schema=./values.schema.json
image:
  repository: ghcr.io/c4illin/convertx
  tag: v0.19.0@sha256:8590a21a16adb8514a8be55b74ad0112bf58ba772328a53f7b40528fcf8fa013
  pullPolicy: IfNotPresent
service:
  main:
    ports:
      main:
        port: 3000
        targetPort: 3000
persistence:
  data:
    enabled: true
    mountPath: /app/data

workload:
  main:
    podSpec:
      containers:
        main:
          env:
            HTTP_ALLOWED: "true"
