# yaml-language-server: $schema=./values.schema.json
image:
  pullPolicy: IfNotPresent
  repository: yourls
  tag: 1.10.4@sha256:d0b8331017770e518faf793aa5b99a72d67e56b6854a5f6d797d39599ffb0bde
securityContext:
  container:
    readOnlyRootFilesystem: false
    runAsGroup: 0
    runAsUser: 0
service:
  main:
    ports:
      main:
        port: 8080
        protocol: tcp
        targetPort: 8080
workload:
  main:
    podSpec:
      containers:
        main:
          env:
            YOURLS_DB_HOST:
              secretKeyRef:
                expandObjectName: false
                name: '{{ printf "%s-%s" .Release.Name "mariadbcreds" }}'
                key: plainhost
            YOURLS_DB_NAME: "{{ .Values.mariadb.mariadbDatabase }}"
            YOURLS_DB_USER: "{{ .Values.mariadb.mariadbUsername }}"
            YOURLS_DB_PASS:
              secretKeyRef:
                expandObjectName: false
                name: '{{ printf "%s-%s" .Release.Name "mariadbcreds" }}'
                key: mariadb-password
            # YOURLS_HOURS_OFFSET: ""
            # protect admin form
            YOURLS_PRIVATE: false
            YOURLS_SITE: "{{ .Values.chartContext.appUrl }}"
            YOURLS_USER: ""
            YOURLS_PASS: ""

mariadb:
  enabled: true
  mariadbUsername: yourls
  mariadbDatabase: yourls
