# yaml-language-server: $schema=./values.schema.json
image:
  repository: docker.io/bitnamisecure/memcached
  pullPolicy: IfNotPresent
  tag: latest@sha256:f9a33838952d7b86d1db9729604edba992025b7499deca0e6abe8ff2b01eaa1a

service:
  main:
    ports:
      main:
        port: 11211
        protocol: tcp
        targetPort: 11211
configmap:
  dashboard:
    enabled: true
    labels:
      grafana_dashboard: "1"
    data:
      memcached.json: >-
        {{ .Files.Get "dashboard.json" | indent 8 }}
