# yaml-language-server: $schema=./values.schema.json
image:
  repository: docker.io/bitnamisecure/memcached
  pullPolicy: IfNotPresent
  tag: latest@sha256:17ac45257e000d72e065390cc75bd7f1b8050c77279b6e0c314ca431d8d3fbfe

service:
  main:
    ports:
      main:
        port: 11211
        protocol: tcp
        targetPort: 11211
configmap:
  dashboard:
    enabled: true
    labels:
      grafana_dashboard: "1"
    data:
      memcached.json: >-
        {{ .Files.Get "dashboard.json" | indent 8 }}
