# yaml-language-server: $schema=./values.schema.json
image:
  repository: docker.io/bitnamisecure/memcached
  pullPolicy: IfNotPresent
  tag: latest@sha256:26a92c6e43929e047f6e469d575520e57e8f3b76e560e164233720d4d8511ed3

service:
  main:
    ports:
      main:
        port: 11211
        protocol: tcp
        targetPort: 11211
configmap:
  dashboard:
    enabled: true
    labels:
      grafana_dashboard: "1"
    data:
      memcached.json: >-
        {{ .Files.Get "dashboard.json" | indent 8 }}
