# yaml-language-server: $schema=./values.schema.json
image:
  pullPolicy: IfNotPresent
  repository: ghcr.io/kiwix/kiwix-serve
  tag: 3.8.2@sha256:12df8dc8fb6d030af38e7733e846d4f4c9a0eb3302777e4e2e52337bf86e2fb7
service:
  main:
    ports:
      main:
        port: 10323
        protocol: http
persistence:
  data:
    enabled: true
    mountPath: /data

securityContext:
  container:
    readOnlyRootFilesystem: false
    runAsNonRoot: false
    runAsGroup: 0
    runAsUser: 0
workload:
  main:
    podSpec:
      containers:
        main:
          env:
            DOWNLOAD: http://download.kiwix.org/zim/wikipedia_en_chemistry_nopic.zim
            PORT: "{{ .Values.service.main.ports.main.port }}"
          args:
            - "*.zim"
