# yaml-language-server: $schema=./values.schema.json
image:
  pullPolicy: IfNotPresent
  repository: docker.io/petersem/posterr
  tag: latest@sha256:292ebe1cb686d326b3014f1a85cbc6e0c5ef4eb4a8501470a0fd775e696b4d26
service:
  main:
    ports:
      main:
        port: 9876
        protocol: http
        targetPort: 3000
persistence:
  config:
    enabled: true
    mountPath: /usr/src/app/config
  custom:
    enabled: true
    mountPath: /usr/src/app/public/custom

securityContext:
  container:
    readOnlyRootFilesystem: false
    runAsNonRoot: false
    runAsGroup: 0
    runAsUser: 0
