# yaml-language-server: $schema=./values.schema.json
image:
  pullPolicy: IfNotPresent
  repository: docker.io/reaparr/reaparr
  tag: 0.38.3@sha256:be12ce50608cb45db7ca0bbdcaf271f98a0134e633fd9733daf4559ddc959819
securityContext:
  container:
    readOnlyRootFilesystem: false
    runAsGroup: 0
    runAsUser: 0
service:
  main:
    ports:
      main:
        protocol: http
        targetPort: 7000
        port: 7000
workload:
  main:
    podSpec:
      containers:
        main:
          env:
            LOG_LEVEL: "INFORMATION"
            LOG_ENV_VARS: false
            UNMASKED: false
persistence:
  config:
    enabled: true
    mountPath: /Config
  downloads:
    enabled: true
    mountPath: /Downloads
