# yaml-language-server: $schema=./values.schema.json
image:
  pullPolicy: IfNotPresent
  repository: docker.io/reaparr/reaparr
  tag: 0.38.1@sha256:767ddf6d4ca6b96521010a7cc8a8b02575b0f7a21dbcef39acc98ead76e9b751
securityContext:
  container:
    readOnlyRootFilesystem: false
    runAsGroup: 0
    runAsUser: 0
service:
  main:
    ports:
      main:
        protocol: http
        targetPort: 7000
        port: 7000
workload:
  main:
    podSpec:
      containers:
        main:
          env:
            LOG_LEVEL: "INFORMATION"
            LOG_ENV_VARS: false
            UNMASKED: false
persistence:
  config:
    enabled: true
    mountPath: /Config
  downloads:
    enabled: true
    mountPath: /Downloads
