# yaml-language-server: $schema=./values.schema.json
image:
  pullPolicy: IfNotPresent
  repository: docker.io/reaparr/reaparr
  tag: 0.38.2@sha256:f5e127d82bb5fab3d65f3618fad2fd300c1f4644e9fe2c6c678455a48649b8de
securityContext:
  container:
    readOnlyRootFilesystem: false
    runAsGroup: 0
    runAsUser: 0
service:
  main:
    ports:
      main:
        protocol: http
        targetPort: 7000
        port: 7000
workload:
  main:
    podSpec:
      containers:
        main:
          env:
            LOG_LEVEL: "INFORMATION"
            LOG_ENV_VARS: false
            UNMASKED: false
persistence:
  config:
    enabled: true
    mountPath: /Config
  downloads:
    enabled: true
    mountPath: /Downloads
