# yaml-language-server: $schema=./values.schema.json
image:
  repository: ghcr.io/linuxserver/firefox
  pullPolicy: IfNotPresent
  tag: 1148.0.2@sha256:4b2668bea63439fb09938ffb805fabfa40bcc9210278840107429952807e7a7b
securityContext:
  container:
    readOnlyRootFilesystem: false
    runAsNonRoot: false
    runAsUser: 0
    runAsGroup: 0
service:
  main:
    ports:
      main:
        protocol: http
        port: 10131
workload:
  main:
    podSpec:
      containers:
        main:
          probes:
            liveness:
              type: http
            readiness:
              type: http
            startup:
              type: http
          env:
            FM_HOME: "/config"
            CUSTOM_PORT: "{{ .Values.service.main.ports.main.port }}"
            TITLE: "TrueChartVNC Client"
persistence:
  config:
    enabled: true
    mountPath: /config
  varrun:
    enabled: false
