# yaml-language-server: $schema=./values.schema.json
image:
  repository: ghcr.io/linuxserver/firefox
  pullPolicy: IfNotPresent
  tag: 1150.0.2@sha256:76a74699d95c2d8b0550b1fc44c8094ea595e209b6f8eeb569c4bb039138dfba
securityContext:
  container:
    readOnlyRootFilesystem: false
    runAsNonRoot: false
    runAsUser: 0
    runAsGroup: 0
service:
  main:
    ports:
      main:
        protocol: http
        port: 10131
workload:
  main:
    podSpec:
      containers:
        main:
          probes:
            liveness:
              type: http
            readiness:
              type: http
            startup:
              type: http
          env:
            FM_HOME: "/config"
            CUSTOM_PORT: "{{ .Values.service.main.ports.main.port }}"
            TITLE: "TrueChartVNC Client"
persistence:
  config:
    enabled: true
    mountPath: /config
  varrun:
    enabled: false
