# yaml-language-server: $schema=./values.schema.json
image:
  repository: ghcr.io/linuxserver/firefox
  pullPolicy: IfNotPresent
  tag: 1150.0.1@sha256:783da937a4c8ba6bec4ae92a24366f6ac8f149a3339a7de3a9cdba640a66a613
securityContext:
  container:
    readOnlyRootFilesystem: false
    runAsNonRoot: false
    runAsUser: 0
    runAsGroup: 0
service:
  main:
    ports:
      main:
        protocol: http
        port: 10131
workload:
  main:
    podSpec:
      containers:
        main:
          probes:
            liveness:
              type: http
            readiness:
              type: http
            startup:
              type: http
          env:
            FM_HOME: "/config"
            CUSTOM_PORT: "{{ .Values.service.main.ports.main.port }}"
            TITLE: "TrueChartVNC Client"
persistence:
  config:
    enabled: true
    mountPath: /config
  varrun:
    enabled: false
