# yaml-language-server: $schema=./values.schema.json
image:
  repository: ghcr.io/linuxserver/librespeed
  tag: 6.2.1@sha256:3d245bb0bc414d0ebe405dcd4f97c660e11b332cea033a73138ce4429064ba8a
  pullPolicy: IfNotPresent
service:
  main:
    ports:
      main:
        port: 10016
        targetPort: 80
persistence:
  config:
    enabled: true
    mountPath: "/config"

securityContext:
  container:
    readOnlyRootFilesystem: false
    runAsNonRoot: false
    runAsUser: 0
    runAsGroup: 0
