# yaml-language-server: $schema=./values.schema.json
image:
  repository: ghcr.io/linuxserver/librespeed
  tag: 6.1.0@sha256:4972660e0a100ea82c34aced4c857e0461554f1c7cde79279fa6313f48d99530
  pullPolicy: IfNotPresent
service:
  main:
    ports:
      main:
        port: 10016
        targetPort: 80
persistence:
  config:
    enabled: true
    mountPath: "/config"

securityContext:
  container:
    readOnlyRootFilesystem: false
    runAsNonRoot: false
    runAsUser: 0
    runAsGroup: 0
