# yaml-language-server: $schema=./values.schema.json
image:
  repository: ghcr.io/linuxserver/librespeed
  tag: 6.1.0@sha256:84e67c40d7b709b337456585478673c318640bc8b9830f65f6e9a4688a813c29
  pullPolicy: IfNotPresent
service:
  main:
    ports:
      main:
        port: 10016
        targetPort: 80
persistence:
  config:
    enabled: true
    mountPath: "/config"

securityContext:
  container:
    readOnlyRootFilesystem: false
    runAsNonRoot: false
    runAsUser: 0
    runAsGroup: 0
