# yaml-language-server: $schema=./values.schema.json
image:
  repository: docker.io/advplyr/audiobookshelf
  tag: 2.33.0@sha256:41047b9985f9c38c92ae8b4b34ffd1d77fca36efdfe49c6b962ff2fc8ccae1e9
  pullPolicy: IfNotPresent
securityContext:
  container:
    readOnlyRootFilesystem: false
    runAsNonRoot: false
    runAsUser: 0
    runAsGroup: 0
service:
  main:
    ports:
      main:
        port: 10223
workload:
  main:
    podSpec:
      containers:
        main:
          probes:
            liveness:
              path: "/ping"
            readiness:
              path: "/ping"
            startup:
              path: "/ping"
          env:
            AUDIOBOOKSHELF_UID: "{{ .Values.securityContext.container.PUID }}"
            AUDIOBOOKSHELF_GID: "{{ .Values.securityContext.pod.fsGroup }}"
            PORT: "{{ .Values.service.main.ports.main.port }}"
            TOKEN_SECRET:
              secretKeyRef:
                name: secrets
                key: TOKEN_SECRET
persistence:
  config:
    enabled: true
    mountPath: /config
  audiobooks:
    enabled: true
    mountPath: /audiobooks
  metadata:
    enabled: true
    mountPath: /metadata

resources:
  limits:
    cpu: 500m
    memory: 750Mi
  requests:
    cpu: 50m
    memory: 125Mi
