# yaml-language-server: $schema=./values.schema.json
image:
  pullPolicy: IfNotPresent
  repository: ghcr.io/meeb/tubesync
  tag: latest@sha256:01be06993a1460e1fea0ed05c77914b4faef40dd8b72c6ebc6e812a538cf98e4
persistence:
  config:
    enabled: true
    mountPath: /config
  downloads:
    enabled: true
    mountPath: /downloads
  varrun:
    enabled: false

securityContext:
  container:
    readOnlyRootFilesystem: false
    runAsGroup: 0
    runAsUser: 0
service:
  main:
    ports:
      main:
        port: 4848
        protocol: tcp
        targetPort: 4848
workload:
  main:
    podSpec:
      containers:
        main:
          env:
            DATABASE_CONNECTION: ""
            http_PASS: ""
            http_USER: ""
            TUBESYNC_DEBUG: "False"
            TUBESYNC_HOSTS: ""
            TUBESYNC_WORKERS: "2"
