# yaml-language-server: $schema=./values.schema.json
image:
  pullPolicy: IfNotPresent
  repository: ghcr.io/meeb/tubesync
  tag: latest@sha256:5890235b30f2a3e48ca1b31a1f0d410087111c76d1367aa2c84c8576bed8f69e
persistence:
  config:
    enabled: true
    mountPath: /config
  downloads:
    enabled: true
    mountPath: /downloads
  varrun:
    enabled: false

securityContext:
  container:
    readOnlyRootFilesystem: false
    runAsGroup: 0
    runAsUser: 0
service:
  main:
    ports:
      main:
        port: 4848
        protocol: tcp
        targetPort: 4848
workload:
  main:
    podSpec:
      containers:
        main:
          env:
            DATABASE_CONNECTION: ""
            http_PASS: ""
            http_USER: ""
            TUBESYNC_DEBUG: "False"
            TUBESYNC_HOSTS: ""
            TUBESYNC_WORKERS: "2"
