image:
  repository: ghcr.io/linuxserver/pwndrop
  pullPolicy: IfNotPresent
  tag: 1.0.1@sha256:c063be7c82af03de8d0bf421b2d16c299369cf1710a52e06307b5e03a1647c4f
service:
  main:
    ports:
      main:
        targetPort: 8080
        port: 10149
persistence:
  config:
    enabled: true
    mountPath: "/config"
  varrun:
    enabled: true

securityContext:
  container:
    runAsNonRoot: false
    readOnlyRootFilesystem: false
    runAsUser: 0
    runAsGroup: 0
