# yaml-language-server: $schema=./values.schema.json
image:
  repository: ghcr.io/linuxserver/pwndrop
  pullPolicy: IfNotPresent
  tag: 1.0.1@sha256:7ca1b5843fcd2f8754fa3a5eaa5014a191f4d15b7a66bd01b9a97e83c34da5e6
service:
  main:
    ports:
      main:
        targetPort: 8080
        port: 10149
persistence:
  config:
    enabled: true
    mountPath: "/config"
  varrun:
    enabled: true

securityContext:
  container:
    runAsNonRoot: false
    readOnlyRootFilesystem: false
    runAsUser: 0
    runAsGroup: 0
