# yaml-language-server: $schema=./values.schema.json
image:
  repository: ghcr.io/linuxserver/pwndrop
  pullPolicy: IfNotPresent
  tag: 1.0.1@sha256:8928c19e914c368dc093cd88ec55ef03a8e326d239c5ff5256f04cc408c752e1
service:
  main:
    ports:
      main:
        targetPort: 8080
        port: 10149
persistence:
  config:
    enabled: true
    mountPath: "/config"
  varrun:
    enabled: true

securityContext:
  container:
    runAsNonRoot: false
    readOnlyRootFilesystem: false
    runAsUser: 0
    runAsGroup: 0
