# yaml-language-server: $schema=./values.schema.json
image:
  repository: ghcr.io/linuxserver/pwndrop
  pullPolicy: IfNotPresent
  tag: 1.0.1@sha256:d17e2fb15a68105b2c91f0d4baea9ca919c33a122684fb1cad9b26c26ac7f795
service:
  main:
    ports:
      main:
        targetPort: 8080
        port: 10149
persistence:
  config:
    enabled: true
    mountPath: "/config"
  varrun:
    enabled: true

securityContext:
  container:
    runAsNonRoot: false
    readOnlyRootFilesystem: false
    runAsUser: 0
    runAsGroup: 0
