# yaml-language-server: $schema=./values.schema.json
image:
  repository: tphakala/birdnet-go
  tag: 20260823@sha256:233b94f1d3b27b261ec8d997364db0cb953f3e3b3362a89e9e22ad4a589143d6 
  pullPolicy: IfNotPresent
service:
  main:
    ports:
      main:
        port: 8080
        targetPort: 8080
persistence:
  config:
    enabled: true
    mountPath: /config
  data:
    enabled: true
    mountPath: /data