# yaml-language-server: $schema=./values.schema.json
image:
  repository: lscr.io/linuxserver/mylar3
  tag: version-v0.10.0@sha256:4e105bb091e587bfa37d3d38b6e924695379e2b043e82037d33101396fa5eafc
  pullPolicy: IfNotPresent
service:
  main:
    ports:
      main:
        port: 8090
        targetPort: 8090
persistence:
  config:
    enabled: true
    mountPath: "/config"
  varrun:
    enabled: true

securityContext:
  container:
    runAsNonRoot: false
    readOnlyRootFilesystem: false
    runAsUser: 0
    runAsGroup: 0
