# yaml-language-server: $schema=./values.schema.json
image:
  repository: lscr.io/linuxserver/mylar3
  tag: version-v0.10.0@sha256:9d393516bafe323dd82c0c5c97f5dcb0818897a394d26371caed62ac8f3c6d37
  pullPolicy: IfNotPresent
service:
  main:
    ports:
      main:
        port: 8090
        targetPort: 8090
persistence:
  config:
    enabled: true
    mountPath: "/config"
  varrun:
    enabled: true

securityContext:
  container:
    runAsNonRoot: false
    readOnlyRootFilesystem: false
    runAsUser: 0
    runAsGroup: 0
