image:
  repository: lscr.io/linuxserver/mylar3
  tag: version-v0.8.2@sha256:7fe6d620a549c1e92834f9e34eca52a209c08e350638a9d80091a2f16695009d
  pullPolicy: IfNotPresent
service:
  main:
    ports:
      main:
        port: 8090
        targetPort: 8090
persistence:
  config:
    enabled: true
    mountPath: "/config"
  varrun:
    enabled: true

securityContext:
  container:
    runAsNonRoot: false
    readOnlyRootFilesystem: false
    runAsUser: 0
    runAsGroup: 0
