# yaml-language-server: $schema=./values.schema.json
image:
  repository: lscr.io/linuxserver/mylar3
  tag: version-v0.9.0@sha256:36049cb1eebe6d23af9a10db061769b634d3cbe536a69b5429049ee130084402
  pullPolicy: IfNotPresent
service:
  main:
    ports:
      main:
        port: 8090
        targetPort: 8090
persistence:
  config:
    enabled: true
    mountPath: "/config"
  varrun:
    enabled: true

securityContext:
  container:
    runAsNonRoot: false
    readOnlyRootFilesystem: false
    runAsUser: 0
    runAsGroup: 0
