# yaml-language-server: $schema=./values.schema.json
image:
  repository: ghcr.io/adferrand/backuppc
  tag: 4@sha256:81bfd8ffb014f7ce65f9354178821ea150e70849f386ba8e12a3cc11cd5532b9
  pullPolicy: IfNotPresent

service:
  main:
    ports:
      main:
        protocol: tcp
        port: 8080

securityContext:
  container:
    runAsNonRoot: false
    readOnlyRootFilesystem: false
    runAsUser: 0
    runAsGroup: 0

workload:
  main:
    podSpec:
      containers:
        main:
          env:
            BACKUPPC_UUID: "{{ .Values.securityContext.container.PUID }}"
            BACKUPPC_GUID: "{{ .Values.securityContext.pod.fsGroup }}"

persistence:
  config:
    enabled: true
    mountPath: /etc/backuppc
  ssh:
    enabled: true
    mountPath: /home/backuppc
  data:
    enabled: true
    mountPath: /data/backuppc
