# yaml-language-server: $schema=./values.schema.json
image:
  repository: ghcr.io/linuxserver/synclounge
  pullPolicy: IfNotPresent
  tag: 5.2.35@sha256:d96749141c9750e841e51c340757d87038a6dcc732a05a6c46d428c14714e3b5
service:
  main:
    ports:
      main:
        targetPort: 8088
        port: 8088
persistence:
  varrun:
    enabled: true

securityContext:
  container:
    runAsNonRoot: false
    readOnlyRootFilesystem: false
    runAsUser: 0
    runAsGroup: 0
workload:
  main:
    podSpec:
      containers:
        main:
          env:
            AUTH_LIST: ""
