# yaml-language-server: $schema=./values.schema.json
image:
  repository: ghcr.io/linuxserver/synclounge
  pullPolicy: IfNotPresent
  tag: 5.2.35@sha256:1388e2f47ac536c06ae73569c5c4e3dd5139a4dfcf0b7051ae6a024f14e2fbaa
service:
  main:
    ports:
      main:
        targetPort: 8088
        port: 8088
persistence:
  varrun:
    enabled: true

securityContext:
  container:
    runAsNonRoot: false
    readOnlyRootFilesystem: false
    runAsUser: 0
    runAsGroup: 0
workload:
  main:
    podSpec:
      containers:
        main:
          env:
            AUTH_LIST: ""
