# yaml-language-server: $schema=./values.schema.json
image:
  repository: ghcr.io/linuxserver/synclounge
  pullPolicy: IfNotPresent
  tag: 5.2.35@sha256:a01d4d16cb688983cfb18d2ffaf15f5503f56a9933de161b5bdb33ceba032f1f
service:
  main:
    ports:
      main:
        targetPort: 8088
        port: 8088
persistence:
  varrun:
    enabled: true

securityContext:
  container:
    runAsNonRoot: false
    readOnlyRootFilesystem: false
    runAsUser: 0
    runAsGroup: 0
workload:
  main:
    podSpec:
      containers:
        main:
          env:
            AUTH_LIST: ""
