image:
  repository: ghcr.io/linuxserver/synclounge
  pullPolicy: IfNotPresent
  tag: 5.2.35@sha256:5bf446c5e725080c31ce2cb1dbcf7fe261323182269d5076a44fc82abac5cfea
service:
  main:
    ports:
      main:
        targetPort: 8088
        port: 8088
persistence:
  varrun:
    enabled: true

securityContext:
  container:
    runAsNonRoot: false
    readOnlyRootFilesystem: false
    runAsUser: 0
    runAsGroup: 0
workload:
  main:
    podSpec:
      containers:
        main:
          env:
            AUTH_LIST: ""
