# yaml-language-server: $schema=./values.schema.json
image:
  repository: ghcr.io/dgtlmoon/changedetection.io
  pullPolicy: IfNotPresent
  tag: 0.60.6@sha256:eb4a9f718801004e006ffef0ce35171f42ec8d45c9b5d20da572bc5febe107ff

service:
  main:
    ports:
      main:
        protocol: http
        targetPort: 5000
        port: 5000

workload:
  main:
    podSpec:
      containers:
        main:
          env:
            BASE_URL: ""
            USE_X_SETTINGS: true
            HIDE_REFERER: true
            FETCH_WORKERS: 10

persistence:
  datastore:
    enabled: true
    mountPath: "/datastore"
