# yaml-language-server: $schema=./values.schema.json
image:
  repository: ghcr.io/dgtlmoon/changedetection.io
  pullPolicy: IfNotPresent
  tag: 0.60.8@sha256:34df3680db1cbffc45ac1e9c1514bc0507dd0c5b5fde47d1992fe6f14a7b40e4

service:
  main:
    ports:
      main:
        protocol: http
        targetPort: 5000
        port: 5000

workload:
  main:
    podSpec:
      containers:
        main:
          env:
            BASE_URL: ""
            USE_X_SETTINGS: true
            HIDE_REFERER: true
            FETCH_WORKERS: 10

persistence:
  datastore:
    enabled: true
    mountPath: "/datastore"
