# yaml-language-server: $schema=./values.schema.json
image:
  repository: ghcr.io/dgtlmoon/changedetection.io
  pullPolicy: IfNotPresent
  tag: 0.55.5@sha256:d89d4187221206f7f9f2c7946e7483815db905ca7d122644081aebd5d23ba391

service:
  main:
    ports:
      main:
        protocol: http
        targetPort: 5000
        port: 5000

workload:
  main:
    podSpec:
      containers:
        main:
          env:
            BASE_URL: ""
            USE_X_SETTINGS: true
            HIDE_REFERER: true
            FETCH_WORKERS: 10

persistence:
  datastore:
    enabled: true
    mountPath: "/datastore"
