# yaml-language-server: $schema=./values.schema.json
image:
  repository: docker.io/tinymediamanager/tinymediamanager
  tag: 5.3.1@sha256:bada62a398e3aabe7a67b0e081c40dc08ce74aa86b7ba63e0a34a1bf278146a4
  pullPolicy: IfNotPresent
service:
  main:
    ports:
      main:
        port: 10179
        targetPort: 4000
persistence:
  data:
    enabled: true
    mountPath: "/data"
  movies:
    enabled: true
    mountPath: "/media/movies"
  tvshows:
    enabled: true
    mountPath: "/media/tvshows"

securityContext:
  container:
    runAsNonRoot: false
    readOnlyRootFilesystem: false
    runAsUser: 0
    runAsGroup: 0
workload:
  main:
    podSpec:
      containers:
        main:
          env:
            PASSWORD: ""
