# yaml-language-server: $schema=./values.schema.json
image:
  repository: docker.io/tinymediamanager/tinymediamanager
  tag: 5.3.0@sha256:e33769b278eefbec646b659342a86a7831869c5a3fa3cca97e7c47f518da4d89
  pullPolicy: IfNotPresent
service:
  main:
    ports:
      main:
        port: 10179
        targetPort: 4000
persistence:
  data:
    enabled: true
    mountPath: "/data"
  movies:
    enabled: true
    mountPath: "/media/movies"
  tvshows:
    enabled: true
    mountPath: "/media/tvshows"

securityContext:
  container:
    runAsNonRoot: false
    readOnlyRootFilesystem: false
    runAsUser: 0
    runAsGroup: 0
workload:
  main:
    podSpec:
      containers:
        main:
          env:
            PASSWORD: ""
