# yaml-language-server: $schema=./values.schema.json
image:
  repository: docker.io/tinymediamanager/tinymediamanager
  tag: 5.2.9@sha256:e2c2b5a66bf500a6a19c654a7c6955e683f3e25283c2c1e32c3e69a6eacb67a3
  pullPolicy: IfNotPresent
service:
  main:
    ports:
      main:
        port: 10179
        targetPort: 4000
persistence:
  data:
    enabled: true
    mountPath: "/data"
  movies:
    enabled: true
    mountPath: "/media/movies"
  tvshows:
    enabled: true
    mountPath: "/media/tvshows"

securityContext:
  container:
    runAsNonRoot: false
    readOnlyRootFilesystem: false
    runAsUser: 0
    runAsGroup: 0
workload:
  main:
    podSpec:
      containers:
        main:
          env:
            PASSWORD: ""
