# yaml-language-server: $schema=./values.schema.json
image:
  repository: docker.io/cloudflare/cloudflared
  pullPolicy: IfNotPresent
  tag: 2026.8.0@sha256:2535e54b16adf1d50630f99d0886471926c5ef3f6b328100ec6589f731c48969
workload:
  main:
    podSpec:
      containers:
        main:
          probes:
            liveness:
              enabled: false
            readiness:
              enabled: false
            startup:
              enabled: false
          args:
            - tunnel
            - --no-autoupdate
            - run
          env:
            TUNNEL_TOKEN: ""
service:
  main:
    enabled: false
    ports:
      main:
        enabled: false
