# yaml-language-server: $schema=./values.schema.json
image:
  repository: docker.io/cloudflare/cloudflared
  pullPolicy: IfNotPresent
  tag: 2026.7.0@sha256:5e49861633763e8933475477c20bae6039ed47f32c1d267a34babc347f28f0df
workload:
  main:
    podSpec:
      containers:
        main:
          probes:
            liveness:
              enabled: false
            readiness:
              enabled: false
            startup:
              enabled: false
          args:
            - tunnel
            - --no-autoupdate
            - run
          env:
            TUNNEL_TOKEN: ""
service:
  main:
    enabled: false
    ports:
      main:
        enabled: false
