# yaml-language-server: $schema=./values.schema.json
image:
  repository: docker.io/cloudflare/cloudflared
  pullPolicy: IfNotPresent
  tag: 2026.5.1@sha256:a5b5e6fd9a372f054b9a843c219bfbcdceb54691605312a8b1ee72978bdf1aa1
workload:
  main:
    podSpec:
      containers:
        main:
          probes:
            liveness:
              enabled: false
            readiness:
              enabled: false
            startup:
              enabled: false
          args:
            - tunnel
            - --no-autoupdate
            - run
          env:
            TUNNEL_TOKEN: ""
service:
  main:
    enabled: false
    ports:
      main:
        enabled: false
