image:
  pullPolicy: IfNotPresent
  repository: ghcr.io/booklore-app/booklore
  tag: v1.8.1@sha256:6b2250cd1a8e13f4e458b5dd2ffe30ed9696482061f27954a97463ffcce677a2
securityContext:
  container:
    readOnlyRootFilesystem: false
    runAsGroup: 0
    runAsUser: 0
service:
  main:
    ports:
      main:
        protocol: http
        port: 6060
workload:
  main:
    podSpec:
      initContainers:
        fix-nginx-run:
          enabled: false
          type: init
          name: fix-nginx-run
          image: alpine:3.22
          command:
            - /bin/sh
            - -c
            - |
              set -e
              mkdir -p /run/nginx
              chown -R 0:0 /run/nginx
              chmod 755 /run /run/nginx
          securityContext:
            runAsUser: 0
            runAsGroup: 0
      containers:
        main:
          env:
            DATABASE_URL:
              secretKeyRef:
                expandObjectName: false
                name: '{{ printf "%s-%s" .Release.Name "mariadbcreds" }}'
                key: jdbc-mariadb
            DATABASE_USERNAME: "{{ .Values.mariadb.mariadbUsername }}"
            DATABASE_PASSWORD: "{{ .Values.mariadb.password }}"
            BOOKLORE_PORT: "{{ .Values.service.main.ports.main.port }}"
persistence:
  run:
    enabled: false
    type: emptyDir
    mountPath: /run
    targetSelector:
      main:
        main:
          mountPath: /run
        fix-nginx-run:
          mountPath: /run
  data:
    enabled: true
    mountPath: /app/data
  varrun:
    enabled: false

mariadb:
  enabled: true
  mariadbUsername: booklore
