image:
  repository: ghcr.io/linuxserver/ubooquity
  pullPolicy: IfNotPresent
  tag: 2.1.5@sha256:890f8d1d4ab5a7a3abc3ca2dd6570b7ef3eb6a8e380b758687a5945b7362d2dc
service:
  main:
    ports:
      main:
        targetPort: 2202
        port: 2202
  admin:
    enabled: true
    ports:
      admin:
        enabled: true
        targetPort: 2203
        port: 2203
persistence:
  varrun:
    enabled: true
  config:
    enabled: true
    mountPath: "/config"
  books:
    enabled: true
    mountPath: "/books"
  comics:
    enabled: true
    mountPath: "/comics"
  files:
    enabled: true
    mountPath: "/files"

securityContext:
  container:
    runAsNonRoot: false
    readOnlyRootFilesystem: false
    runAsUser: 0
    runAsGroup: 0
workload:
  main:
    podSpec:
      containers:
        main:
          probes:
            liveness:
              type: tcp
            readiness:
              type: tcp
            startup:
              type: tcp
          env:
            MAXMEM: 512
