image:
  repository: ghcr.io/linuxserver/smokeping
  pullPolicy: IfNotPresent
  tag: 2.9.0@sha256:5f459ce0d1dcd27346a647517ebbdfd7aa2bb6bb3b3e182870274509099a8512
strategy:
  type: Recreate
service:
  main:
    ports:
      main:
        port: 10030
        targetPort: 80
persistence:
  config:
    enabled: true
    mountPath: "/config"
  data:
    enabled: true
    mountPath: "/data"
  varrun:
    enabled: false

securityContext:
  container:
    capabilities:
      add:
        - NET_RAW
    readOnlyRootFilesystem: false
    runAsNonRoot: false
    allowPrivilegeEscalation: true
    runAsUser: 0
    runAsGroup: 0
workload:
  main:
    podSpec:
      containers:
        main:
          probes:
            liveness:
              type: tcp
            readiness:
              type: tcp
            startup:
              type: tcp
