# yaml-language-server: $schema=./values.schema.json
image:
  repository: ghcr.io/linuxserver/smokeping
  pullPolicy: IfNotPresent
  tag: 2.9.0@sha256:f91de6eeb3384d00c1d92cf0c2b2956692fe64048eb1f6c9207e43b0c479af77
strategy:
  type: Recreate
service:
  main:
    ports:
      main:
        port: 10030
        targetPort: 80
persistence:
  config:
    enabled: true
    mountPath: "/config"
  data:
    enabled: true
    mountPath: "/data"
  varrun:
    enabled: false

securityContext:
  container:
    capabilities:
      add:
        - NET_RAW
    readOnlyRootFilesystem: false
    runAsNonRoot: false
    allowPrivilegeEscalation: true
    runAsUser: 0
    runAsGroup: 0
workload:
  main:
    podSpec:
      containers:
        main:
          probes:
            liveness:
              type: tcp
            readiness:
              type: tcp
            startup:
              type: tcp
