# yaml-language-server: $schema=./values.schema.json
image:
  repository: docker.io/josh5/unmanic
  tag: 0.4.1@sha256:b249cba0d77331fe015794dc06f98cc4c99c50f158cfce43575a1b4f330495a9
  pullPolicy: IfNotPresent
service:
  main:
    ports:
      main:
        port: 10157
        targetPort: 8888
persistence:
  config:
    enabled: true
    mountPath: "/config"
  library:
    enabled: true
    mountPath: "/library"
  remote:
    enabled: true
    mountPath: "/tmp/unmanic/remote_library"
  cache:
    enabled: true
    mountPath: "/tmp/unmanic"
    type: emptyDir
