# yaml-language-server: $schema=./values.schema.json
image:
  pullPolicy: IfNotPresent
  repository: docker.io/krateng/maloja
  tag: latest@sha256:6013039eab0a1c8a0edbc7df7aeb9c9449ccb55186d9efa3bf16704957dbe7ff
persistence:
  config:
    enabled: true
    mountPath: /config

securityContext:
  container:
    readOnlyRootFilesystem: false
    runAsGroup: 0
    runAsUser: 0
service:
  main:
    ports:
      main:
        port: 42010
        protocol: tcp
        targetPort: 42010
workload:
  main:
    podSpec:
      containers:
        main:
          env:
            MALOJA_DATA_DIRECTORY: /config
            MALOJA_HOST: 0.0.0.0
