# yaml-language-server: $schema=./values.schema.json
image:
  pullPolicy: IfNotPresent
  repository: docker.io/krateng/maloja
  tag: latest@sha256:1ccc7f4f78256242ada110efffe255617c974714455199c59a1fb0696ab23734
persistence:
  config:
    enabled: true
    mountPath: /config

securityContext:
  container:
    readOnlyRootFilesystem: false
    runAsGroup: 0
    runAsUser: 0
service:
  main:
    ports:
      main:
        port: 42010
        protocol: tcp
        targetPort: 42010
workload:
  main:
    podSpec:
      containers:
        main:
          env:
            MALOJA_DATA_DIRECTORY: /config
            MALOJA_HOST: 0.0.0.0
