# yaml-language-server: $schema=./values.schema.json
image:
  pullPolicy: IfNotPresent
  repository: oci.trueforge.org/containerforge/duplicacy
  tag: 1.8.0@sha256:1ebb160691f618a9b7c8f55daf459c223259ff9f22201cff354e235588e943ff
securityContext:
  container:
    runAsGroup: 0
    runAsUser: 0
    readOnlyRootFilesystem: false
service:
  main:
    ports:
      main:
        port: 3875
        protocol: http
        targetPort: 3875
persistence:
  config:
    enabled: true
    mountPath: /config
  cache:
    enabled: true
    mountPath: /cache
  logs:
    enabled: true
    mountPath: /logs
