# yaml-language-server: $schema=./values.schema.json
image:
  pullPolicy: IfNotPresent
  repository: oci.trueforge.org/containerforge/duplicacy
  tag: 1.8.0@sha256:5ef586ccc837a3b2fd893923eb6c10d98c2d68db38323cb77a2c7168d5aa92ee
securityContext:
  container:
    runAsGroup: 0
    runAsUser: 0
    readOnlyRootFilesystem: false
service:
  main:
    ports:
      main:
        port: 3875
        protocol: http
        targetPort: 3875
persistence:
  config:
    enabled: true
    mountPath: /config
  cache:
    enabled: true
    mountPath: /cache
  logs:
    enabled: true
    mountPath: /logs
