# yaml-language-server: $schema=./values.schema.json
image:
  pullPolicy: IfNotPresent
  repository: oci.trueforge.org/containerforge/duplicacy
  tag: 1.8.0@sha256:23f03d40939b3a4f09023abb7fda8ac6f94403a8439d57d8448aef8c9105225c
securityContext:
  container:
    runAsGroup: 0
    runAsUser: 0
    readOnlyRootFilesystem: false
service:
  main:
    ports:
      main:
        port: 3875
        protocol: http
        targetPort: 3875
persistence:
  config:
    enabled: true
    mountPath: /config
  cache:
    enabled: true
    mountPath: /cache
  logs:
    enabled: true
    mountPath: /logs
