# yaml-language-server: $schema=./values.schema.json
image:
  pullPolicy: IfNotPresent
  repository: docker.io/shaneisrael/fireshare
  tag: 1.6.9@sha256:ba9374d68b177350d8598cc5bd8e3e66a97cae9985acce2b0aa4b4b7424f80a3

securityContext:
  container:
    readOnlyRootFilesystem: false
    runAsUser: 0
    runAsGroup: 0

workload:
  main:
    podSpec:
      containers:
        main:
          env:
            SECRET_KEY:
              secretKeyRef:
                name: fireshare-secrets
                key: SECRET_KEY
            MINUTES_BETWEEN_VIDEO_SCANS: 5
            ADMIN_PASSWORD: "changeme"
            # TODO ADD LDAP
            # LDAP_ENABLE: false
            # LDAP_URL: ""
            # LDAP_BINDDN: ""
            # LDAP_PASSWORD: ""
            # LDAP_BASEDN: ""
            # LDAP_USER_FILTER: ""
            # LDAP_ADMIN_GROUP: ""

service:
  main:
    ports:
      main:
        port: 10287
        protocol: http
        targetPort: 80

persistence:
  data:
    enabled: true
    mountPath: /data
  processeddata:
    enabled: true
    mountPath: /processed
  videos:
    enabled: true
    mountPath: /videos
  images:
    enabled: true
    mountPath: /images
