# yaml-language-server: $schema=./values.schema.json
image:
  repository: registry
  pullPolicy: IfNotPresent
  tag: 3@sha256:1be55279f18a2fe1a74edf2664cac61c1bea305b7b4642dab412e7affdcb3e33
service:
  main:
    ports:
      main:
        port: 10096
        targetPort: 8080
persistence:
  config:
    enabled: true
    mountPath: "/config"
