# yaml-language-server: $schema=./values.schema.json
image:
  repository: registry
  pullPolicy: IfNotPresent
  tag: 3@sha256:8a7c1aae9db5028cbc1cfe83e5969d270a50e8bc0b72eef3cc5657542ec383c9
service:
  main:
    ports:
      main:
        port: 10096
        targetPort: 8080
persistence:
  config:
    enabled: true
    mountPath: "/config"
