# yaml-language-server: $schema=./values.schema.json
image:
  repository: ghcr.io/linuxserver/calibre
  tag: 9.8.0@sha256:de295215232855535ec110855d2f74946c7d78a596eb3a9d39d191e21dbc6fcc
  pullPolicy: IfNotPresent
securityContext:
  container:
    readOnlyRootFilesystem: false
    runAsNonRoot: false
    runAsUser: 0
    runAsGroup: 0
service:
  main:
    ports:
      main:
        port: 8084
        protocol: tcp
        targetPort: 8080
  webserver:
    enabled: true
    ports:
      webserver:
        enabled: true
        port: 8081
        protocol: http
        targetPort: 8081
ingress:
  webserver:
    enabled: false
    targetSelector:
      webserver: webserver
workload:
  main:
    podSpec:
      containers:
        main:
          env:
            CLI_ARGS:
            PASSWORD: ""
persistence:
  config:
    enabled: true
    mountPath: /config
