# yaml-language-server: $schema=./values.schema.json
image:
  repository: ghcr.io/linuxserver/calibre
  tag: 9.12.0@sha256:8de8a08f9f798fa22639ac7f9b7c78026544aea7a0852fa990da286939e77eb1
  pullPolicy: IfNotPresent
securityContext:
  container:
    readOnlyRootFilesystem: false
    runAsNonRoot: false
    runAsUser: 0
    runAsGroup: 0
service:
  main:
    ports:
      main:
        port: 8084
        protocol: tcp
        targetPort: 8080
  webserver:
    enabled: true
    ports:
      webserver:
        enabled: true
        port: 8081
        protocol: http
        targetPort: 8081
ingress:
  webserver:
    enabled: false
    targetSelector:
      webserver: webserver
workload:
  main:
    podSpec:
      containers:
        main:
          env:
            CLI_ARGS:
            PASSWORD: ""
persistence:
  config:
    enabled: true
    mountPath: /config
