# yaml-language-server: $schema=./values.schema.json
image:
  repository: ghcr.io/linuxserver/resilio-sync
  tag: 3.1.2@sha256:a8a52dc40dbf14c2941abbe76e7b21e251682fc1747008e167ae959c4f0786de
  pullPolicy: IfNotPresent
service:
  main:
    ports:
      main:
        port: 8888
        targetPort: 8888
  bt-tcp:
    enabled: true
    ports:
      bt-tcp:
        enabled: true
        port: 55555
        targetPort: 55555
  bt-udp:
    enabled: true
    ports:
      bt-udp:
        enabled: true
        port: 55555
        targetPort: 55555
        protocol: udp
persistence:
  config:
    enabled: true
    mountPath: "/config"
  data:
    enabled: true
    mountPath: "/sync"
  varrun:
    enabled: true

securityContext:
  container:
    runAsNonRoot: false
    readOnlyRootFilesystem: false
    runAsUser: 0
    runAsGroup: 0
workload:
  main:
    podSpec:
      containers:
        main:
          probes:
            liveness:
              type: tcp
              port: "{{ .Values.service.main.ports.main.targetPort }}"
            readiness:
              type: tcp
              port: "{{ .Values.service.main.ports.main.targetPort }}"
            startup:
              type: tcp
              port: "{{ .Values.service.main.ports.main.targetPort }}"
