# yaml-language-server: $schema=./values.schema.json
image:
  repository: ghcr.io/linuxserver/digikam
  pullPolicy: IfNotPresent
  tag: 9.1.0@sha256:052b8f26062f85f7bd9f10e3b041c5df4917c38e9e6fc50e2860378e8706cd71
securityContext:
  container:
    readOnlyRootFilesystem: false
    runAsNonRoot: false
    runAsUser: 0
    runAsGroup: 0
service:
  main:
    ports:
      main:
        port: 10033
        targetPort: 3000
persistence:
  config:
    enabled: true
    mountPath: /config
