# yaml-language-server: $schema=./values.schema.json
image:
  repository: ghcr.io/linuxserver/digikam
  pullPolicy: IfNotPresent
  tag: 9.1.0@sha256:5884607c4db10e0855886e449d5a79a28cedbd415e0ebd1e6cb263b1900717ac
securityContext:
  container:
    readOnlyRootFilesystem: false
    runAsNonRoot: false
    runAsUser: 0
    runAsGroup: 0
service:
  main:
    ports:
      main:
        port: 10033
        targetPort: 3000
persistence:
  config:
    enabled: true
    mountPath: /config
