# yaml-language-server: $schema=./values.schema.json
image:
  repository: ghcr.io/linuxserver/digikam
  pullPolicy: IfNotPresent
  tag: 9.1.0@sha256:6072c8ce7192fb7037f6928d03045627641f071b24435a715fa189973c9a63d7
securityContext:
  container:
    readOnlyRootFilesystem: false
    runAsNonRoot: false
    runAsUser: 0
    runAsGroup: 0
service:
  main:
    ports:
      main:
        port: 10033
        targetPort: 3000
persistence:
  config:
    enabled: true
    mountPath: /config
