# yaml-language-server: $schema=./values.schema.json
image:
  pullPolicy: IfNotPresent
  repository: ghcr.io/recyclarr/recyclarr
  tag: 8.7.3@sha256:9c6c74d52cfc6f740a5a3624aa83867e171bb70b90453ddb7a4048b8c80445f9
service:
  main:
    enabled: false
    ports:
      main:
        enabled: false
workload:
  main:
    podSpec:
      initContainers:
        initconfig:
          type: install
          enabled: true
          imageSelector: "image"
          command:
            - recyclarr
            - config
            - create
      containers:
        main:
          probes:
            liveness:
              enabled: false
            readiness:
              enabled: false
            startup:
              enabled: false
          env:
            CRON_SCHEDULE: "@daily"
persistence:
  config:
    enabled: true
    mountPath: /config
    targetSelectAll: true
