# yaml-language-server: $schema=./values.schema.json
image:
  repository: ghcr.io/fluidd-core/fluidd
  tag: v1.37.1@sha256:5e3c6afb8097541bc5f15f4c0f959a2af5e8ee01230e8c517080f304a1ec7a79
  pullPolicy: IfNotPresent
securityContext:
  container:
    readOnlyRootFilesystem: false
    runAsNonRoot: false
    runAsUser: 0
    runAsGroup: 0
workload:
  main:
    podSpec:
      containers:
        main:
          probes:
            liveness:
              type: http
              path: /
            readiness:
              type: http
              path: /
            startup:
              type: http
              path: /
          env: {}
service:
  main:
    ports:
      main:
        port: 10224
        targetPort: 80
