# yaml-language-server: $schema=./values.schema.json
image:
  repository: ghcr.io/fluidd-core/fluidd
  tag: v1.37.3@sha256:c22da71a50b757fc721a4daa8d234040f6a39230188367fc0b03a2696e1a75e9
  pullPolicy: IfNotPresent
securityContext:
  container:
    readOnlyRootFilesystem: false
    runAsNonRoot: false
    runAsUser: 0
    runAsGroup: 0
workload:
  main:
    podSpec:
      containers:
        main:
          probes:
            liveness:
              type: http
              path: /
            readiness:
              type: http
              path: /
            startup:
              type: http
              path: /
          env: {}
service:
  main:
    ports:
      main:
        port: 10224
        targetPort: 80
