# yaml-language-server: $schema=./values.schema.json
image:
  repository: ghcr.io/fluidd-core/fluidd
  tag: v1.36.4@sha256:893fc63f4f9f3b3ce7beae209186da3fed592fec6f7efdee8e287d6e774ecef0
  pullPolicy: IfNotPresent
securityContext:
  container:
    readOnlyRootFilesystem: false
    runAsNonRoot: false
    runAsUser: 0
    runAsGroup: 0
workload:
  main:
    podSpec:
      containers:
        main:
          probes:
            liveness:
              type: http
              path: /
            readiness:
              type: http
              path: /
            startup:
              type: http
              path: /
          env: {}
service:
  main:
    ports:
      main:
        port: 10224
        targetPort: 80
