secret:
  pocketid-env:
    enabled: true
    data:
      ENCRYPTION_KEY: Y2ktdGVzdC1lbmNyeXB0aW9uLWtleS1vbmx5IQ==
      DB_CONNECTION_STRING: file:data/pocket-id.db

workload:
  main:
    podSpec:
      containers:
        main:
          env:
            APP_URL: "http://pocket-id.localtest.me"
          envFrom:
            - secretRef:
                name: pocketid-env
