# yaml-language-server: $schema=./values.schema.json
image:
  pullPolicy: IfNotPresent
  repository: docker.io/yacy/yacy_search_server
  tag: latest@sha256:9e8b192f323f5a70091926a39e53277903f26141a298a4f057d3afd8fd4a2562
persistence:
  appdata:
    enabled: true
    mountPath: /opt/yacy_search_server/DATA

securityContext:
  container:
    readOnlyRootFilesystem: false
    runAsGroup: 0
    runAsUser: 0
service:
  https:
    enabled: true
    ports:
      https:
        enabled: true
        port: 8443
        protocol: tcp
        targetPort: 8443
  main:
    ports:
      main:
        port: 8090
        protocol: http
        targetPort: 8090
