# yaml-language-server: $schema=./values.schema.json
image:
  repository: ghcr.io/homebridge/homebridge
  tag: 2026-08-11@sha256:f866476753f3be8dce13d54f93af3401c061b5f9ee1f11b3a11a7ded13655078
  pullPolicy: IfNotPresent

securityContext:
  container:
    readOnlyRootFilesystem: false
    runAsNonRoot: false
    runAsUser: 0
    runAsGroup: 0

workload:
  main:
    podSpec:
      containers:
        main:
          env:
            HOMEBRIDGE_CONFIG_UI: 1

service:
  main:
    ports:
      main:
        protocol: http
        port: 8581

persistence:
  config:
    enabled: true
    mountPath: /homebridge
