# yaml-language-server: $schema=./values.schema.json
image:
  repository: ghcr.io/homebridge/homebridge
  tag: 2026-08-17@sha256:bd34f506b2bc107b6987f7a9cc0dd5854205ca2ffe3bbe563fdf214fbc3fcc65
  pullPolicy: IfNotPresent

securityContext:
  container:
    readOnlyRootFilesystem: false
    runAsNonRoot: false
    runAsUser: 0
    runAsGroup: 0

workload:
  main:
    podSpec:
      containers:
        main:
          env:
            HOMEBRIDGE_CONFIG_UI: 1

service:
  main:
    ports:
      main:
        protocol: http
        port: 8581

persistence:
  config:
    enabled: true
    mountPath: /homebridge
