# yaml-language-server: $schema=./values.schema.json
image:
  repository: ghcr.io/homebridge/homebridge
  tag: 2026-08-08@sha256:e5ec53db9e8ba93d9e4c5341e713085ea833f8ea9fcac901ec0dfc849de258b7
  pullPolicy: IfNotPresent

securityContext:
  container:
    readOnlyRootFilesystem: false
    runAsNonRoot: false
    runAsUser: 0
    runAsGroup: 0

workload:
  main:
    podSpec:
      containers:
        main:
          env:
            HOMEBRIDGE_CONFIG_UI: 1

service:
  main:
    ports:
      main:
        protocol: http
        port: 8581

persistence:
  config:
    enabled: true
    mountPath: /homebridge
