image:
  repository: docker.io/homebridge/homebridge
  tag: 2025-07-15@sha256:fd56aa89aa8d8825a5c89979ef5828545fd8e2e98cee138c3845b0bdf92ac2c6
  pullPolicy: IfNotPresent

securityContext:
  container:
    readOnlyRootFilesystem: false
    runAsNonRoot: false
    runAsUser: 0
    runAsGroup: 0

workload:
  main:
    podSpec:
      containers:
        main:
          env:
            HOMEBRIDGE_CONFIG_UI: 1

service:
  main:
    ports:
      main:
        protocol: http
        port: 8581

persistence:
  config:
    enabled: true
    mountPath: /homebridge
