# yaml-language-server: $schema=./values.schema.json
image:
  repository: oci.trueforge.org/containerforge/seerr
  tag: "3.1.0@sha256:95e84d1729cdac84d25fcc98048b2e3c273cad0ea17a53abadfd22e0cf1d7bac"
  pullPolicy: IfNotPresent
service:
  main:
    ports:
      main:
        port: 10241
persistence:
  config:
    enabled: true
    mountPath: "/app/config"

workload:
  main:
    podSpec:
      containers:
        main:
          env:
            PORT: "{{ .Values.service.main.ports.main.port }}"
            # User Defined
            JELLYFIN_TYPE: ""
            LOG_LEVEL: "info"
