# yaml-language-server: $schema=./values.schema.json
image:
  repository: oci.trueforge.org/containerforge/seerr
  tag: "3.2.0@sha256:7197fe2c1397efac7e6d8d5ddd5fec2e3715425303d90eb4cdb2e5374f458213"
  pullPolicy: IfNotPresent
service:
  main:
    ports:
      main:
        port: 10241
persistence:
  config:
    enabled: true
    mountPath: "/app/config"

workload:
  main:
    podSpec:
      containers:
        main:
          env:
            PORT: "{{ .Values.service.main.ports.main.port }}"
            # User Defined
            JELLYFIN_TYPE: ""
            LOG_LEVEL: "info"
