# yaml-language-server: $schema=./values.schema.json
image:
  repository: oci.trueforge.org/containerforge/seerr
  tag: "3.2.0@sha256:f41a5a0b8bf677ca657cea1feb8ce1fdd376acb812c241f291d52a1d9d11dce0"
  pullPolicy: IfNotPresent
service:
  main:
    ports:
      main:
        port: 10241
persistence:
  config:
    enabled: true
    mountPath: "/app/config"

workload:
  main:
    podSpec:
      containers:
        main:
          env:
            PORT: "{{ .Values.service.main.ports.main.port }}"
            # User Defined
            JELLYFIN_TYPE: ""
            LOG_LEVEL: "info"
