# yaml-language-server: $schema=./values.schema.json
image:
  repository: ghcr.io/linuxserver/healthchecks
  tag: 4.2.20260706@sha256:4426306a6b2f84c5645d4601fef6472821310ff26b7200aeca186e3dc7f32934
  pullPolicy: IfNotPresent
service:
  main:
    ports:
      main:
        port: 10074
        targetPort: 8000
persistence:
  config:
    enabled: true
    mountPath: "/config"

securityContext:
  container:
    readOnlyRootFilesystem: false
    runAsNonRoot: false
    runAsUser: 0
    runAsGroup: 0
workload:
  main:
    podSpec:
      containers:
        main:
          probes:
            liveness:
              type: tcp
            readiness:
              type: tcp
            startup:
              type: tcp
          env:
            REGENERATE_SETTINGS: "True"
            SITE_ROOT: "https://healthchecks.domain"
            SITE_NAME: ""
            SUPERUSER_EMAIL: "email@healthchecks.io"
            SUPERUSER_PASSWORD: "myVeryStrongPassword"
