# yaml-language-server: $schema=./values.schema.json
image:
  repository: ghcr.io/linuxserver/healthchecks
  tag: 4.1.20260323@sha256:9284fb75cc62aafebb01eceef41f1630cc5c97c25ea2e310083e9799f36836f3
  pullPolicy: IfNotPresent
service:
  main:
    ports:
      main:
        port: 10074
        targetPort: 8000
persistence:
  config:
    enabled: true
    mountPath: "/config"

securityContext:
  container:
    readOnlyRootFilesystem: false
    runAsNonRoot: false
    runAsUser: 0
    runAsGroup: 0
workload:
  main:
    podSpec:
      containers:
        main:
          probes:
            liveness:
              type: tcp
            readiness:
              type: tcp
            startup:
              type: tcp
          env:
            REGENERATE_SETTINGS: "True"
            SITE_ROOT: "https://healthchecks.domain"
            SITE_NAME: ""
            SUPERUSER_EMAIL: "email@healthchecks.io"
            SUPERUSER_PASSWORD: "myVeryStrongPassword"
