# yaml-language-server: $schema=./values.schema.json
image:
  repository: docker.io/anirdev/slink
  pullPolicy: IfNotPresent
  tag: v1.12.0@sha256:4de5027ae96f201c1b56a97882386262c275aeb7bb525148cf4ade17f30fc9eb
securityContext:
  container:
    readOnlyRootFilesystem: false
    runAsUser: 0
    runAsGroup: 0
    runAsNonRoot: false
service:
  main:
    ports:
      main:
        protocol: http
        port: 3000
workload:
  main:
    podSpec:
      containers:
        main:
          env:
            ORIGIN: "{{ .Values.chartContext.appUrl }}"
            USER_APPROVAL_REQUIRED: true
            IMAGE_MAX_SIZE: "15M"
persistence:
  database:
    enabled: true
    mountPath: "/app/var/data"
  images:
    enabled: true
    mountPath: "/app/slink/images"
ingress:
  main:
    required: true
