# yaml-language-server: $schema=./values.schema.json
image:
  repository: docker.io/anirdev/slink
  pullPolicy: IfNotPresent
  tag: v1.13.1@sha256:5b6c29592f63edccbef613fbbd3b106f322bf21290d0bb6451d105ca14802b90
securityContext:
  container:
    readOnlyRootFilesystem: false
    runAsUser: 0
    runAsGroup: 0
    runAsNonRoot: false
service:
  main:
    ports:
      main:
        protocol: http
        port: 3000
workload:
  main:
    podSpec:
      containers:
        main:
          env:
            ORIGIN: "{{ .Values.chartContext.appUrl }}"
            USER_APPROVAL_REQUIRED: true
            IMAGE_MAX_SIZE: "15M"
persistence:
  database:
    enabled: true
    mountPath: "/app/var/data"
  images:
    enabled: true
    mountPath: "/app/slink/images"
ingress:
  main:
    required: true
