annotations:
  artifacthub.io/links: |-
    - name: support
    url: https://discord.gg/tVsPTHWTtr
  max_scale_version: 24.04.1
  min_scale_version: 24.04.0
  truecharts.org/train: stable
  truecharts.org/category: network
  truecharts.org/min_kubernetes_version: 1.24.0
  truecharts.org/max_kubernetes_version: 1.32.0
  truecharts.org/min_helm_version: "3.14"
  truecharts.org/max_helm_version: "3.17"


apiVersion: v2
appVersion: "v3.40.3" # Gluetun container version
dependencies:
  - name: common
    version: 28.29.2
    repository: oci://oci.trueforge.org/truecharts
    condition: ""
    alias: ""
    tags: []
    import-values: []
deprecated: false
description: A VPN gateway container supporting WireGuard and OpenVPN with a socks5 proxy, used to route application traffic securely.
home: https://github.com/qdm12/gluetun/
icon: https://raw.githubusercontent.com/qdm12/gluetun/master/logo.png
keywords:
  - vpn
  - wireguard
  - openvpn
  - networking
  - privacy
  - secure-routing
kubeVersion: '>=1.24.0-0'
maintainers:
  - name: The TrueCharts Community
    email: info@truecharts.org
    url: https://truecharts.org

name: gluetun
sources:
  - https://github.com/qdm12/gluetun
  - https://github.com/serjs/socks5-server
  - https://truecharts.org/


type: application
version: 0.1.0
