# yaml-language-server: $schema=./values.schema.json
image:
  repository: ghcr.io/chroma-core/chroma
  pullPolicy: IfNotPresent
  tag: 1.5.7@sha256:fc8dc8e11fb252b3bc610f6affe6e0ac883252519f4f6021a08a2e31d9a295f4

securityContext:
  container:
    runAsNonRoot: false
    readOnlyRootFilesystem: false
    runAsUser: 0
    runAsGroup: 0

service:
  main:
    ports:
      main:
        protocol: http
        targetPort: 8000
        port: 10690

workload:
  main:
    podSpec:
      containers:
        main:
          probes:
            liveness:
              path: "/api/v2/heartbeat"
            readiness:
              path: "/api/v2/heartbeat"
            startup:
              path: "/api/v2/heartbeat"
          env:
            IS_PERSISTENT: true

persistence:
  config:
    enabled: true
    mountPath: "/chroma/chroma"
